### ISSUE TITLE
Analyzing Chamber

### ISSUE THREAD

**Issue by NullMagic** [SonarSonic/Calculator#10]
It appears that the Analyzing Chamber can't be fully automated, any circuit put in it that hasn't first been in the inventory of a player can not be analyzed, and won't even be removed from it via any form of automation. It took me a while to track down the issue, at first I was confused because when I put the circuits directly into a hopper it ran them through just fine, that unfortunately cost me several hours of head scratching, it wasn't until I opened the Analyzing chamber, clicked the circuit, and then immediately dropped it back in without putting it in my inventory that I realized what the issue was, as it still refused to do anything with it, however I then put it in an inventory slot, and then put it back, and it immediately worked.

So, as far as I can tell (and barring some strange and unique cross mod interaction, which is possible though I feel probably unlikely) a circuit must first pass through a player's inventory before it can be processed in the Chamber.

**Comment by SonarSonic** [comment]
Should be fixed in version 1.7.5, which version are you running?

**Comment by NullMagic** [comment]
Ah, 1.7.3, I looked for a closed error report and didn't see one, I clearly should have looked more thoroughly to see if this was noted anywhere else.

**Comment by SonarSonic** [comment]
Yeah It was here http://minecraft.curseforge.com/mc-mods/225104-calculator/issues/1142 :)
