### ISSUE TITLE
End forged tools issue. 1.7.5-1.9.10

### ISSUE THREAD

**Issue by MineWitherMC** [SonarSonic/Calculator#100]
Issue with EFT: when you take one of the tools it immediately "flies" from hotbar into inventory. It happens with versions from 1.7.5 to 1.9.10 and probably some others.

**Comment by MineWitherMC** [comment]
Record of this: https://youtu.be/NqJ--4_ZKYA

**Comment by SonarSonic** [comment]
What inventory mods do you have installed? I've never seen this issue before

**Comment by MineWitherMC** [comment]
Thought that was Inventory Tweaks but getting this even after deleting IT (I don't know what are you calling inv mods though but think I have no more).

22.05.2016, 18:42, "Ollie Lansdell" <notifications@github.com>:

**Comment by SonarSonic** [comment]
Can't recreate this at all :/

**Comment by MineWitherMC** [comment]
Seems to be inventory tweaks issue. Pure environment didn't give this issue for me as long as I don't install IT. I still don't know why issue persists after removing IT...

**Comment by SonarSonic** [comment]
Thanks for letting me know :)
