### ISSUE TITLE
Energy not updating on Calculator Locator/Conductor Mast/etc (1.9.9)

### ISSUE THREAD

**Issue by Axylxys** [SonarSonic/Calculator#101]
I noticed that issue mostly on Calculator Locator and Conductor Mast, though it also happens with the energy bar on various Calculator machines. 

When hovering the mouse on the block, it shows the correct amount of RF it has, but when opening the GUI it's often not accurate at all: the RF/Tick and the energy bar seem to update when they feel like it (and quite rarely). I couldn't find a pattern to even force an update, so that makes it quite hard to see what's the current state of the block.

As a side note, are you interested in a longer and more detailled feedback/suggestion post about the mod as a whole and various issues (not really bugs) ? :)

**Comment by SonarSonic** [comment]
Ahh okay, this will be due to changes to syncing, i'll look into it for you. Yeah that would be useful, feedback is always helpful :)

**Comment by SonarSonic** [comment]
Fixed in dev - this will require an update of Sonar Core not Calculator.
