### ISSUE TITLE
Calculator Locator and various power generation woes

### ISSUE THREAD

**Issue by Axylxys** [SonarSonic/Calculator#104]
With the display bug i always assumed the Calculator Locator had a good power output, but after running into some issues i had a bit of a doubt. I ended up testing it properly with a creative capacitor to see exactly how it outputs... and it was quite a disappointment.

Here's the setup, it should be max size unless i missed something:

http://pasteboard.co/1eEUwsDP.png

It's down to about 20K Rf/t, while it can output 64K as long as it has some battery, and that seems quite low considering the size and overall cost of that monster. With the recipe cost, i thought the Locator to be the designated end game generator, but should i look for a gigantic lightning farm instead ?

With the scaling of RF these days, many mods eat up a lot more RF, a huge Locator is only enough to power up a single MFR Laser drill, and it doesn't even come close to the various reactors and other conversion systems (a mid game Rotarycraft engine could probably output more RF for much cheaper). Despite being a renewable, rather lag-free and no maintenance energy, i find it hard to justify something the size of a building when it can barely power a single machine. So even if it's pretty to have in the landscape, it seems really underwhelming.

Is that working as intended, with the Conductor Mast being the actual true power generator ? With the Locator lore and recipes it seemed like the end game one. Now i'm a bit afraid of building hundreds of Transmitters only to find out i'll never get more than a few thousands RF/t, even if unlike the locator it has some config tweaks to fix that hopefully.

Also that just shows how it can be confusing, i assumed the Locator to be 128K rf/t because of the plug interface, that was quite a nasty surprise when i turned on 6 MFR Laser drills and everything went down. :D

**Comment by SonarSonic** [comment]
When Calculator starting getting big it was excluded from loads of mod packs for being to OP. I still think this generation is fair though. Considering you get power for nothing at all, no extra resources are needed to keep it going. I'm not 100% sure though. I guess i'd want to hear other people opinions on the levels on power generation and consumption in the mod.

**Comment by Axylxys** [comment]
Isn't there a way to make it config-dependant though ? That way anyone could adjust for their own needs, as the RF balance isn't the same over all the mods anyway. Some mods don't scale beyond a few thousand RF/t, while for some 100K RF/t is nothing anyway.

Hopefully more peoples will comment on such issues but, i find the "no effort" part to be more of a comfort with server performance. All the reactors and various power sources can be fully automated anyway with ressources being mostly a non-issue in end game, but having spawners or dozens of machines is much more intensive than simply the plugs. For exemple, an entry-level Mekanism reactor will run with no extra ressource cost and generate about 200K rf/t, up to 400K easily, but at the same time involving a hundred of various machines running just to fuel it.

As a side note, would you mind disclosing some stats on the Conductor Mast ? :) I'd just like to know what sort of power generation i could expect from a big one, as on paper it looks like it could scale higher than the Locator at some point. Thanks !

**Comment by DarkenTheSun** [comment]
Hi Sonar,

I would like to start by saying I love the unique features this mod brings to my world!  I was very hopeful at using the Calculator Locator as a replacement for other power sources, mainly due to the fact that it seems like it really does a good job at keeping the strain down on the server itself.  

It takes just enough to get started and set-up that I felt like I 'earned' the power I would get, especially with doing my own 'engineering' work 6 days a week IRL... Axylxys was very correct about wanting a configurable adjustment for this, I pretty much went right to the config file as soon as I found out just how little I was actually getting from the Locator, and that no matter how big it would be, it would never be enough.  I pretty much just gave up on the Locator for the present time and I'm keeping my fingers crossed that I can have some use for it in the future.

Anyways, keep up the good work and thanks for providing a very unique addition to the game!

**Comment by SonarSonic** [comment]
What if they generated 3x more?

**Comment by Axylxys** [comment]
To be honest i don't think it would be enough. Of course it depends on modpacks but, i assume a solid power generation for end game stuff with a large tech modpack should be around 300-500K rf/t. The RF/t adds up quickly between a large ME system, various turrets, upgraded machines, various power converters, teleporters, automated miners, and of course all the automated systems and ore processing chains.

So ideally i think if Calculator aims to have its own power source, it should be able to scale to that amount. I tried a Lightning Farm and even that doesn't come close, adding up the Locator and the Conductors masts, i think i have about 8 chunks covered with power generation units (plugs, transmitters, weather stations) and it still doesn't produce even close to what i need while not being reliable (even with hundreds of transmitters the Conductors masts always have a 3sec downtime with no output). I find the "no maintenance" aspect to be compensated enough with the large upfront cost and building time as well as the size itself.

The time, size and ressources it takes to build those definitely hint at an end game power source, making it a straight "competitor" to various reactors in mods (not Reika's ones though, those are much harder and generate millions anyway).

That said, it would clearly be OP on some modpacks with a low scaling, it's all down to which mods are in the pack... Sadly i think the RF energy balancing is a bit all over the place between mods. A config option would be the best to accomodate everything, otherwise i feel the Locator should at least be 100K+ Rf/t at max size, and the Conductor Masts should be able to fill up what's missing on their own, as building a giant lightning farm is definitely worth more than what it currently outputs. 

That's just my opinion though, as mods like Mekanism, Reika's mods, Advanced generators and the likes are in all my worlds, and they sure tend to push up the RF range to high amounts.

Another option though, could be an upgrade to Locator plugs. Maybe leave the default one as it is, and add some kind of upgraded plug with a greater output at a greater cost, that could be unlocked via config ? So peoples with a low RF-use modpack could just keep the current one, and other ones with a lot of tech mods could get a stronger version that would keep the comparaison against other power sources.

**Comment by DarkenTheSun** [comment]
TBH here...Axylxys sums this up so well I have nothing more constructive to add to this conversation other than "I agree" and I hope we can get more.  The cost and time involved in building the Locator and Lightning Farms for what it gives me literally made me give up where I was and move back to Mekanism until I can work towards something else...

With that being said, I'm absolutely in love with the Flux Network!

**Comment by SonarSonic** [comment]
4x it is
