### ISSUE TITLE
Conductor Mast - Weather station, odd positioning

### ISSUE THREAD

**Issue by Axylxys** [SonarSonic/Calculator#106]
While building Lightning farms i noticed the "circles" of weather stations are not equal on the 4th row.

I built them starting from the middle, leaving an empty block between each weather station to make squares (or circles visually as they turn to face the mast). It works well for the 3 first rings of stations, then for the 4th one it only works for two sides: i can place 7 of them on south and east side, but only 5 on North and West side. The remaining two per side will face nowhere and do not link to the Mast.

This happens with all the setups i've done (4 of them) and it's definitely not an issue with reaching a max number of stations, as i tried to place those before the other sides. 

Here's a screenshot to show what i mean, featuring my awesome skills with Paint:

http://pasteboard.co/1j4cUu1p.png

You can see all masts having only 5 stations on their north and west sides, as i removed the ones not linking. The holes also show where they should be.

I found that odd enough to be a bug as i can't think of a reason for that, everything is symetrical so they're the same distance from the mast than the one linking, and it's definitely not a number issue as the stations i placed later worked well. Unless there's something i'm missing in there.

Version is still 1.9.9 though, sorry if it has been fixed since then !

**Comment by SonarSonic** [comment]
Fixed in dev
