### ISSUE TITLE
Wireless charging suggestion

### ISSUE THREAD

**Issue by DarkenTheSun** [SonarSonic/Calculator#107]
Hi Sonar!

So I happened across an interesting situation as I was setting up an autocrafting recipe at my main ME terminal last night.  As I was inserting an Energy Module from Mekanism into the crafting recipe, I realized that the Flux Controller had charged it for me while I was making the recipe!

I know this may be a unique situation in which I actually have the wireless charging near my terminal, but would it be possible to have a config option to have only the items in my hotbar charged instead of the entire inventory?  I know it is a matter of personal preference to the person using the mod for what they want, and while I do love the whole inventory charging, I had to keep the item out of my inventory the whole time I was making the recipe, and that will probably be tedious in the long run.  Also, with everything always being charged...I actually haven't needed the whole inventory to be charged now that I've had the Flux Controller!

Thanks for any consideration!

**Comment by Axylxys** [comment]
I think i just got used to having everything RF based being charged anyway, but it would sure be handy to have such a setting. :)

**Comment by SonarSonic** [comment]
Added as a mode on the Flux Controller
![image](https://cloud.githubusercontent.com/assets/10425594/15906312/298d3f76-2db0-11e6-8873-0ca823b93322.png)

**Comment by DarkenTheSun** [comment]
You are amazing! Sometimes the smallest things can make people very happy, thanks!

On Wed, Jun 8, 2016 at 2:35 PM, SonarSonic/Calculator <reply@reply.github.com> wrote:
Closed #107 [https://github.com/SonarSonic/Calculator/issues/107] .

**Comment by SonarSonic** [comment]
No problem :)
