### ISSUE TITLE
Performance issues with big calculator locators

### ISSUE THREAD

**Issue by Skillotic0703** [SonarSonic/Calculator#11]
I'm using calculator 1.7.5

When i look at big calculator locators, it hugely decreases my fps.
I noted that when i built a calculator locator on a flat world to test the atomic multiplier.

**Comment by SonarSonic** [comment]
Thanks, i'll look into that

**Comment by Skillotic0703** [comment]
You're welcome !

**Comment by SonarSonic** [comment]
Should all be fine now. That class needed fixing anyway

**Comment by Skillotic0703** [comment]
Thank you !
