### ISSUE TITLE
[1.10] Reinforced chest - stacks of 256 items are invisible

### ISSUE THREAD

**Issue by kwpugh** [SonarSonic/Calculator#114]
Forge: 1996
Mod: Calculator-1.9.4-3.0.0.jar

The reinforced chest accepts stacks up to 256 items each and the stacks go invisible at 256.

**Comment by SonarSonic** [comment]
interesting. thanks for letting me know

**Comment by SonarSonic** [comment]
I couldn't reproduce this could you possibly provide any further info. Are you using any inventory mods?

**Comment by kwpugh** [comment]
We are using InventoryTweaks.   Is that what you mean by inventory mods?

**Comment by SonarSonic** [comment]
yeah that could possibly be the issue. no mods are 100% stable on 1.10

**Comment by MineWitherMC** [comment]
Inventory tweaks almost "conflicts" with Calculator, you can't see 256-stacks, use Ender Diamond tools etc.

**Comment by hron84** [comment]
Let me invite @Kobata in this thread. Maybe he has some idea about this problem.

**Comment by ErsatzIncline** [comment]
Similar thing is occurring with circuit storage, probably because of similar interaction (again inventory tweaks). Posted under a separate thread sorry.

**Comment by SonarSonic** [comment]
Should be fixed
