### ISSUE TITLE
Carbon Dioxide Generator not working.

### ISSUE THREAD

**Issue by KIdWither** [SonarSonic/Calculator#115]
I can't seem to get the generator working, it is full on power and has coal to burn in the top slot?

**Comment by SonarSonic** [comment]
where is it positioned in relation to the greenhouse?

**Comment by KIdWither** [comment]
4 blocks over to the right from the greenhouse block.

**Comment by KIdWither** [comment]
Sorry two blocks away from green house block

**Comment by SonarSonic** [comment]
Which version is this in?

**Comment by KIdWither** [comment]
The 1.9.4- 3.0.0 in 1.10 minecraft (curse said it was for 1.10). I also noticed that the oxygen is full and that may be the cause, if that is true then how would i get the oxygen out?

**Comment by SonarSonic** [comment]
Fixed in dev
