### ISSUE TITLE
[1.10.2] JEI not working

### ISSUE THREAD

**Issue by tommyTT** [SonarSonic/Calculator#116]
The integration with JEI doesn't work at all which makes it very hard to actually craft anything with the calculators. There seems to be a class missing (see the log).

Forge Version: 12.18.0.2004
Mod Version: 3.0.0
Sonar Core: 3.0.0
JEI: 3.7.3.221

http://paste.ee/p/6nZpu

**Comment by SonarSonic** [comment]
Thanks for reporting should be fixed in the next update

**Comment by SonarSonic** [comment]
Fixed in dev
