### ISSUE TITLE
[1.10.2] Basic Greenhouse not building correctly

### ISSUE THREAD

**Issue by tommyTT** [SonarSonic/Calculator#117]
I tried to use the greenhouse and gave it all the required materials. It started building, but when it comes to placing the stairs it stops. It seems to place multiple stairs in the same place and then stops (the top stairs in the linked picture below). Afterwards it wants more stairs, meaning there are now stairs missing. If I then give it more stairs it complains, that there are blocks in the way ... the ones it placed previously. It looks like there is no resume or manual build mode, which also means I can't use it at the moment.

Forge Version: 12.18.0.2004
Mod Version: 3.0.0
Sonar Core: 3.0.0
JEI: 3.7.3.221

http://paste.ee/p/6nZpu
https://imgur.com/a/yCk3p

**Comment by SonarSonic** [comment]
Fixed in dev
