### ISSUE TITLE
[1.10.2] Generators are missing their recipe

### ISSUE THREAD

**Issue by tommyTT** [SonarSonic/Calculator#119]
The generators are shown in JEI but no recipe is shown. I looked inside the code and there doesn't seem to be a recipe defined there either. Maybe I'm missing something and you have to craft them inside a calculator (see the issue with JEI)?

Forge Version: 12.18.0.2004
Mod Version: 3.0.0
Sonar Core: 3.0.0
JEI: 3.7.3.221

http://paste.ee/p/6nZpu

**Comment by SonarSonic** [comment]
Fixed in dev
