### ISSUE TITLE
Hand Cranked Generator not outputting RF

### ISSUE THREAD

**Issue by BigFriendlyJakey** [SonarSonic/Calculator#120]
I can't progress in the mod; I can generate RF with the had-cranked generator, but it won't output to any blocks that require power (not even the power cube). I is confused.

**Comment by SonarSonic** [comment]
Which version are you running. I'm pretty sure it was working on 3.0.1

**Comment by b0bst3r** [comment]
Can confirm it works fine in 1.9.4-3.0.3
