### ISSUE TITLE
[enhancement] Support the tesla energy api

### ISSUE THREAD

**Issue by Prospector** [SonarSonic/Calculator#121]
I think it would be nice for yet another mod to support it.

**Comment by SonarSonic** [comment]
A couple have people have suggested this. So yes I probably will :)

**Comment by SonarSonic** [comment]
Added in dev

**Comment by SonarSonic** [comment]
https://github.com/SonarSonic/Sonar-Core/commit/65515576483d8a11d8baca654b005a28bd9a9359

Done. All the changes were to Sonar Core as that is where I deal with Energy Stuff
