### ISSUE TITLE
1.10.2 Starch Generator crashed game

### ISSUE THREAD

**Issue by BigFriendlyJakey** [SonarSonic/Calculator#122]
So from my previous issue, I heard you say that 1.8.9 was "dead", so I decided to update :)

Unfortunately, at some point when using the Starch Extractor/Generator thingy (the green one that generates power, lowest tier), the game crashes (report below). Just a bug, completely avoidable, but may freak some people out. My game is fine to launch afterwards. 

> [crash-2016-07-07_23.50.28-server.txt](https://github.com/SonarSonic/Calculator/files/352288/crash-2016-07-07_23.50.28-server.txt)

**Comment by SonarSonic** [comment]
Thanks for reporting. I will fix it soon :)

**Comment by SonarSonic** [comment]
Fixed in dev
