### ISSUE TITLE
Crash when putting coal in generators

### ISSUE THREAD

**Issue by Naosyth** [SonarSonic/Calculator#123]
crash report: http://hastebin.com/raw/furezekati

This specifically happened to me with the Redstone Extractor. After the server came back up, the generator produced perpetual power, which was nice, but I don't want everyone crashing my server to get unlimited power :p

**Comment by SonarSonic** [comment]
Can't seem to access the link, however I think this may be a duplicate to #122 in which case this is already fixed :)

**Comment by Naosyth** [comment]
Whoops, not sure why that link isn't working. Looks like it is the same issue though, thanks for fixing it!
