### ISSUE TITLE
[1.10.2] Severe Lag and Rendering Errors in Chunk with Storage Chambers

### ISSUE THREAD

**Issue by tommyTT** [SonarSonic/Calculator#124]
To reproduce the rendering errors, you start up a new world, place down a storage chamber and a vanilla chest in the same chunk as the chamber. Then you go to the nether and immediately return. The chest becomes invisible (see https://imgur.com/a/PLhux ). 
This is the easiest version of it. In my server world I'm using EnderIO conduits to transfer the items around and they also disappear. I also had some very strange renderings of the other blocks from Calculators (see https://imgur.com/a/qkTlU ). The bad thing is, that the entire game crashes when I try to access the conduits, I can only break and replace them. 
Because I have this all on a server and it has been running for quite a while, I gathered a few circuits. One chamber has over 2.5k of them stored, the other one about 500 stable circuits. Whenever I look at those two blocks from a distance I could interact with them, the framerate drops to 0 FPS. I removed the 2.5k one and placed it down somewhere else and it doesn't show any content any more. For the other one I can open the GUI and see everything but the lag is very very bad. In the log I don't have any Exceptions, so it might not be the same bug? 

Minecraft: 1.10.2
Forge: 12.18.0.2008
Mods:
  Calculator-1.9.4-3.0.2
  jei_1.10.2-3.7.3.222
  moreoverlays-1.6-mc1.9.4
  SonarCore-1.9.4-3.0.2

http://paste.ee/p/GWLWH

**Comment by SonarSonic** [comment]
I couldn't recreate any of these. Might be a 1.10.2 issue only. It's pretty strange, i'm really not that sure how this could be happening. I don't handle the render dispatching for normal block models so I can't exactly do anything to fix the rendering. I think this is just an example of how Forge isn't 100% stable on 1.10 versions.

**Comment by b0bst3r** [comment]
Thank god I saw this was starting to rip my base apart trying to figure out why EnderIO machines and conduits were glitching terribly, having broken all the calculator machines it seems to have stopped.

Here's an example of what was happening http://i.imgur.com/z1PhDOj.png every other block which had a conduit passing through had visually vanished.  Ender IO machine fronts were being turned around and some very other weird stuff like blood from EvilCraft vanished from tanks and AAs chests had vanished.

Yeah this is 1.10.2

Edit - Just noticed this in the log - http://pastebin.ubuntu.com/18924902/

**Comment by SonarSonic** [comment]
Okay I've fixed the issue in the log. Maybe that was causing the problems. Not 100% sure, but I will push the latest beta of Calculator tonight.

**Comment by tommyTT** [comment]
All the circuits from the storage chamber are gone after the update, so I can't test the lag. The rendering issues however seem to also be gone, so maybe they were related.

**Comment by SonarSonic** [comment]
Sorry to hear about that also. Really strange, must have been corrupting the NBT. Does it save properly now??

**Comment by tommyTT** [comment]
I've installed a refined storage system to replace the storage chambers, so I haven't tested it extensively, but a quick check didn't show any problems with saving the data.

**Comment by b0bst3r** [comment]
Been running with all the machines back in place all day with no rendering issues so this looks good.

**Comment by SonarSonic** [comment]
Excellent, hopefully it stays that way :)
