### ISSUE TITLE
[1.10.2] Calculator Plugs rendering after dimension switch

### ISSUE THREAD

**Issue by tommyTT** [SonarSonic/Calculator#125]
I'm setting up a minimal version of the calculator plugs, so it generates power. Every one has a stable circuit in it, the locator is running and it produces 2k RF/t. All the plugs are green. I then go to the nether or any other dimension and return. All the plugs are now red. That had me really worried the first time it happened, but there are no negative effects. When I look in the GUI of the locator, the information is totally inconsistent. It still says, it is a formed multi block but the power storage doesn't fill any more. I then look into one of the plugs (only open the GUI, nothing more) and the plug turn green again. Afterwards I look into the locator again and the numbers now fluctuate, but the power storage seems to fill like it still generates the whole 2k RF/t.

Minecraft: 1.10.2
Forge: 12.18.0.2008
Mods:
Calculator-1.9.4-3.0.2
jei_1.10.2-3.7.3.222
moreoverlays-1.6-mc1.9.4
SonarCore-1.9.4-3.0.2

https://imgur.com/a/bGRes
http://paste.ee/p/VU7WB

**Comment by SonarSonic** [comment]
I can probably do something about that.

**Comment by b0bst3r** [comment]
It's not just dimension switch it's when you leave the area so it unloads it messes up.  I'm on a SMP server and don't really want to push it into testing and have my base destroyed.  So I remove the locator card everytime I leave the area and always come back to red plugs even though they all have stable circuits in them.

**Comment by SonarSonic** [comment]
It's a visual glitch only. Simply the client isn't being told the current state so you don't need to worry about your base being destroyed.

**Comment by Peach774** [comment]
Ah, so it is calculator, okay. Good to know this issue is being worked on.

**Comment by b0bst3r** [comment]
I linked the wrong issue lol it's https://github.com/SonarSonic/Calculator/issues/124

**Comment by SonarSonic** [comment]
Fixed in dev for Calculator Plug and Locator

**Comment by tommyTT** [comment]
I updated to the newest versions versions and all the plugs and the locator are gone.

**Comment by SonarSonic** [comment]
Sorry I had to change the block state implementation. I'm surprised that's happened though... sorry about that.

**Comment by b0bst3r** [comment]
Just a heads up, having seen tommyTTs comment I broke all the plugs and locator before updating and they were still in my inv after the update, so break them prior.

**Comment by b0bst3r** [comment]
Ok so after a couple of days play with the new version there are still some things not working correctly.

The plugs no longer turn red you fixed that but the calculator locator isn't in sync with the plugs after chunks are unloaded/dimensions changed.

You still have to open every plug GUI so that the locator works/updates correctly.  It switches states to 0% stability and active with only 72RF/t unless you open all the plug GUIs.  It does seem to initially open correctly but that maybe just cached info from last time it was opened.

**Comment by SonarSonic** [comment]
That last one is a Client Issue, no risk of Calculator Locator exploding cause of those read-outs. I have also fixed this now btw, should be updating properly in next update.
