### ISSUE TITLE
[1.10.2] Flawless Greenhouse crashes the game

### ISSUE THREAD

**Issue by tommyTT** [SonarSonic/Calculator#126]
After updating to the newest version, my server crashes. It seems to be a problem when using a normal or any other chest. The reinforced chest seems to be okay.

http://paste.ee/p/Z48yi

**Comment by SonarSonic** [comment]
Thanks for reporting. I'll push a SonarCore fix soon.

**Comment by SonarSonic** [comment]
Fixed in dev
