### ISSUE TITLE
[1.10.2] Axe attack speeds out of whack?

### ISSUE THREAD

**Issue by Kazzamkablam** [SonarSonic/Calculator#127]
I just happened to look at stats of axes and noticed following:
(Calculator 3.0.3)

Reinforced axe 2,5 damage, 9 attack speed
Redstone axe: 3,5 damage, 11.5 attack speed
Fire diamond axe 8 damage, 20 attack speed
Electric axe, 11 damage, 22 attack speed
End forged axe, 17 damage, 54??? attack speed (basically making it instant and spammable in 1.10)

Is this intended?

**Comment by SonarSonic** [comment]
Fixed in dev.
