### ISSUE TITLE
Storage chamber not storing circuits

### ISSUE THREAD

**Issue by Skillotic0703** [SonarSonic/Calculator#13]
In 1.7.7 when it finally stores my circuit i can't retrieve it and when i try with shift-clicking, the game crashes !

**Comment by SonarSonic** [comment]
Can you give me a crash report?

**Comment by Skillotic0703** [comment]
http://pastebin.com/eugTmqGk

**Comment by SonarSonic** [comment]
Okay yeah I fixed it, any other final glitches before I release another version?

**Comment by Skillotic0703** [comment]
No

**Comment by Skillotic0703** [comment]
Thank you

**Comment by SonarSonic** [comment]
this only happens when your taking the last circuit out, so if you fill a storage chamber it won't be as bad if it is automated that is

**Comment by Skillotic0703** [comment]
It doesn't work even in 1.7.7 stable and in a new world.
The circuits don't want to go in it with right-clicking, shift-clicking or whatever it is.
