### ISSUE TITLE
[1.10.2] Multiple crashes, looks like Mod Compatability

### ISSUE THREAD

**Issue by Dragnier** [SonarSonic/Calculator#132]
I have several crash reports to add here, but I'm getting odd crashes with the hand cranked generator. The first crash was simply placing the hand cranked generator. That crash referenced both this mod and Waila. After removing Waila and replacing it with The One Probe, the crash referenced FFS - Fancy Fluid Storage along with this mod. 

Disabling FFS allowed the world loaded again but as soon as I shift + right-clicked to add the handle it crashed again and then referenced Quark's right click to edit signs feature. After turning off Quark's feature in configs, I could then add the handle properly and turn it.

However, then right-clicking on the generator to check the contents crashed the game again and that caused the report to only contain this mod and the required Sonar Core.

I will attach all of my crash reports, even though some are potentially duplicates. I just want to provide all the information necessary for this to get fixed. If you find the problem is with another mod, let me know so I can redirect this issue to them.

[crash-2016-07-12_23.07.01-client.txt](https://github.com/SonarSonic/Calculator/files/360655/crash-2016-07-12_23.07.01-client.txt)
[crash-2016-07-12_23.10.22-client.txt](https://github.com/SonarSonic/Calculator/files/360656/crash-2016-07-12_23.10.22-client.txt)
[crash-2016-07-12_23.26.46-client.txt](https://github.com/SonarSonic/Calculator/files/360657/crash-2016-07-12_23.26.46-client.txt)
[crash-2016-07-12_23.30.59-client.txt](https://github.com/SonarSonic/Calculator/files/360659/crash-2016-07-12_23.30.59-client.txt)
[crash-2016-07-12_23.35.04-client.txt](https://github.com/SonarSonic/Calculator/files/360661/crash-2016-07-12_23.35.04-client.txt)
[crash-2016-07-12_23.37.34-client.txt](https://github.com/SonarSonic/Calculator/files/360662/crash-2016-07-12_23.37.34-client.txt)
[crash-2016-07-12_23.40.13-client.txt](https://github.com/SonarSonic/Calculator/files/360658/crash-2016-07-12_23.40.13-client.txt)
[crash-2016-07-12_23.41.57-client.txt](https://github.com/SonarSonic/Calculator/files/360660/crash-2016-07-12_23.41.57-client.txt)

**Comment by SonarSonic** [comment]
It's an API issue, CoFH is clashing, since there is no official version... that's the problem. Let me see what I can do

**Comment by Dragnier** [comment]
Do you use CoFH or Tesla? I only ask because Tesla is current and maintained. Plus, it would be nice to have a mod that actually used it. It's like everyone is stuck on CoFH even though there's another option.

**Comment by AEnterprise** [comment]
there is an official version of the RF api in the COFH RF api repo, been for a while

**Comment by SonarSonic** [comment]
Oh really I was checking the Redstone Flux Git

**Comment by SonarSonic** [comment]
I have support for both CoFH and Tesla :)

**Comment by Dragnier** [comment]
CoFH may have an "official" version, but Tesla is still more flexible and advanced from what I've read.

Glad to see it's supported.

**Comment by Dragnier** [comment]
I found the issue and it isn't with your mod! Since Extra Utilities isn't marked for 1.10.2, you have to manually download it instead of using the curse launcher if you intend to use it on 1.10.2. Somehow, despite my selecting the correct file and pressing the correct gray download button, curse decided to give me the 1.7.10  version anyway. That is what was causing the crash even though it wasn't showing up in the logs.

I have replaced it with the correct 1.10 version and everything works fine now.

**Comment by SonarSonic** [comment]
Well that makes a lot of sense haha, thanks for reporting. FYI my version of CoFH matched the official version.
