### ISSUE TITLE
[1.10.2] Stone Separator doesn't work with iron ore in 3.0.4

### ISSUE THREAD

**Issue by b0bst3r** [SonarSonic/Calculator#133]
Calculator-1.9.4-3.0.4
SonarCore-1.9.4-3.0.4
Forge 2008

No errors but the recipe to create reinforced iron from raw iron ore in the stone separator no longer works.  It accepts the ore but nothing happens in the machine.

~~Not sure if other recipes are broken since that's the only one I've tried~~ 

Confirmed other recipes do not work either in the SS.

**Comment by SonarSonic** [comment]
Fixed in dev
