### ISSUE TITLE
[1.10.2] Trees don't grow "fruit"

### ISSUE THREAD

**Issue by b0bst3r** [SonarSonic/Calculator#134]
I know it's not fruit but you know what I mean :)

The Diamond, Tanzanite and Amethyst trees don't bear any fruit, I know the diamond one is supposed to, not sure about the other 2.  My trees have been planted and grown now for MC weeks and still bare.

Calculator-1.9.4-3.0.5
SonarCore-1.9.4-3.0.4
Forge 2008

**Comment by SonarSonic** [comment]
Fixed in dev
