### ISSUE TITLE
Precision and processing chamber can't be automated

### ISSUE THREAD

**Issue by Skillotic0703** [SonarSonic/Calculator#14]
When i try to output circuits from them, it doesn't work. I tried with enderIO conduits and itemduct from TE. I'm sure that i didn't let the redstone control on. It only works with the analysing chamber.

**Comment by SonarSonic** [comment]
Pretty sure it does work, have you right clicked the side with a wrench?

**Comment by SonarSonic** [comment]
I'm not getting this problem in my test world. Remember soil and small stone can't go in a Processing Chamber

**Comment by Skillotic0703** [comment]
oups it does work when right-click the side
