### ISSUE TITLE
Conductor Mast export

### ISSUE THREAD

**Issue by AlphaChimaera89** [SonarSonic/Calculator#143]
The conductor mast does not seem to be exporting power through any face. 

Calculator 1.9.4 - 3.0.7
SonarCore 1.9.4 - 3.0.5
Forge Version 12.18.0.2010

**Comment by SonarSonic** [comment]
Fixed in dev

**Comment by psychofad** [comment]
has the fix for this been released yet?

**Comment by AlphaChimaera89** [comment]
not yet, no

**Comment by psychofad** [comment]
Ah, ok, built a tower of those things on a server I play on and well, they gain power nicely and the lightning show is cool, but I think access to the power would top it off nicely! :D

Will be watching for the update! Thanks!
