### ISSUE TITLE
[1.10.2] Obsidian Key doesn't break Purified Obsidian

### ISSUE THREAD

**Issue by Melakion** [SonarSonic/Calculator#146]
Made an Obsidian Key and a piece of Purified Obsidian. Placed the purified Obsidian down, tried to break it with the key, but rt clicking just makes an animation as if you are lt clicking. Right click on normal obsidian picks it up immediately. 

Forge 2018
Calculator-1.9.4-3.0.7

**Comment by Melakion** [comment]
Also - Wither breaks Purified Obsidian

Made my wither cage out of purified obsidian even though there is still a block of it stuck in the middle of my base.

Spawned wither, it immediately broke the blocks and escaped.

**Comment by SonarSonic** [comment]
Fixed in dev
