### ISSUE TITLE
Spongeforge server crash (tanzanite leaves)

### ISSUE THREAD

**Issue by Liiw** [SonarSonic/Calculator#148]
Hello!

I am playing on a private Spongeforge server with multiple mods installed. I placed down a tanzanite sapling and left it there to mature. After a while, the server crashed Judging by the crashlog, it had something to do with tanzanite leaves properties. 

I have uploaded the server crash log attached. Could you take a look at it and advise? I apologize if this is a duplicate issue, however I could not find the issue when searching for it here.

[crash-2016-07-30_02.12.16-server.txt](https://github.com/SonarSonic/Calculator/files/391564/crash-2016-07-30_02.12.16-server.txt)

**Comment by SonarSonic** [comment]
First crash i've seen from using the same version for 1.9.4 and 1.10, should be able to fix it though.

**Comment by SonarSonic** [comment]
Fixed in latest version
