### ISSUE TITLE
support for Biomes O Plenty tanzanite and ametyst

### ISSUE THREAD

**Issue by 0Navis0** [SonarSonic/Calculator#149]
There is no any support for the Biomes O Plenty gems, so they can't be used in the Calculator machines and recipes, and Calculator gems can't be used in the Biomes O Plenty recipes.

**Comment by SonarSonic** [comment]
I've just added full Ore Dictionary support. It may be that Biomes O' Plenty have decided to not register their Amethysts and Tanzanites to avoid causing imbalance in other mods. You could ask them about it if you wish.

**Comment by 0Navis0** [comment]
Ok thanks for your answer, I will ask them. ;)
https://github.com/Glitchfiend/BiomesOPlenty/issues/817
