### ISSUE TITLE
Storage chamber not storing circuits !!!!

### ISSUE THREAD

**Issue by Skillotic0703** [SonarSonic/Calculator#15]
It doesn't work even in 1.7.7 stable and in a new world.
The circuits don't want to go in it with right-clicking, shift-clicking or whatever it is.
Even with automation !!!

**Comment by DrWhoCares** [comment]
I'll test this in a bit if I get time.

**Comment by SonarSonic** [comment]
Probably a user error. Circuit can't be stored if they haven't been Analysed first.
Try a Dirty or Damaged One

**Comment by Skillotic0703** [comment]
Not working witz damaged and Dirty circuits

Le vendredi 24 juillet 2015, Ollie Lansdell <notifications@github.com> a
écrit :

**Comment by Skillotic0703** [comment]
Sorry, I tested that in an ancient world but there's some bugs that i noted in a new world. Even if it stores dirty/damaged circuits, sometime it doesn't store analysed circuits and when it stores an analysed circuit, it doesn't want to store multiple analysed circuits.

**Comment by Skillotic0703** [comment]
Sorry, i made another mistake, it stores all types of circuit. It just doesn't store circuits that are storing items but it's normal. The analysing chamber doesn't extract items from circuits if there are already items in the analysing chamber. It's not really a problem. Sorry !!
