### ISSUE TITLE
Shift-Clicking doesn't use RF (1.10.2, 3.0.7)

### ISSUE THREAD

**Issue by SweetSugarSugar** [SonarSonic/Calculator#150]
Hello!  I'm playing a custom pack for 1.10.2 with Calculator 3.0.7 and SonarCore 3.0.5 for 1.9.4 on Forge 12.18.1.2024 and I noticed a bug where if you shift click the result while using the calculator, it doesn't consume any RF.

**Comment by SonarSonic** [comment]
Fixed in dev
