### ISSUE TITLE
Conductor mast not converting Fire Diamonds

### ISSUE THREAD

**Issue by ryu2065** [SonarSonic/Calculator#152]
Conductor mast is not converting Fire Diamonds to Electric Diamonds when the mast is struck by lightning. 

Also when right clicking with a sickle on the tree leaves it does not yield the resources.
And sometimes the circuit generating machines (Precision,Restoration,Analyzing Chambers) forget which sides have been configured for output and input.

Running on Minecraft 1.10.2
Modpack - Donutcraft version 1.10.2-0.0.9
Launcher - AlLauncher
Forge - 12.18.1.2024
SonicCore - 1.9.4-3.0.7
Calculator - 1.9.4-3.0.8

**Comment by SonarSonic** [comment]
I couldn't recreate this, it's working fine for me :/

**Comment by SonarSonic** [comment]
Are you playing on a server? Or LAN or something?

**Comment by ryu2065** [comment]
Yes I am playing on a server. Using the listed versions.

**Comment by SonarSonic** [comment]
Couldn't recreate this at all

**Comment by AEnterprise** [comment]
you are using a modpack, does that include minetweaker or something similar? if so check the scripts to make sure this isn't a pack specific to the pack

**Comment by DoughnutDev** [comment]
Hi, 

I am the pack dev here are the minetweaker scripts

http://hastebin.com/qinemacipe.xml

http://hastebin.com/fokobiniwe.xml

*Edit ryu is very outdated. We are currently on 0.1.0c

**Comment by SonarSonic** [comment]
@ryu2065 try updating first :P then
