### ISSUE TITLE
[1.10 Feature request] More Crafttweaker Support

### ISSUE THREAD

**Issue by MechWarrior99** [SonarSonic/Calculator#153]
Hello, 
I was wondering if you could add more Crafttweaker (Minetweaker for 1.9/10) integration. It would be really handy for modpack developers. If you are willing to, then here are the machines that (To my knowledge) don't have CT support, and could use it.

Extraction Chamber
Restoration Chamber
Reassembly Chamber
Precision Chamber
Processing Chamber
Fabrication Chamber

Sorry if this has already be requested or there is already support for these.
Thanks for reading :)

**Comment by SonarSonic** [comment]
Well that took longer than anticipated. I've added all except the Fabrication Chamber. Since that is quite complex.

**Comment by MechWarrior99** [comment]
Cool, thank you vary much :D
