### ISSUE TITLE
[Suggestion] Add Redstone Ingot Block

### ISSUE THREAD

**Issue by hron84** [SonarSonic/Calculator#154]
Compacting drawers from Storage Drawers are one of the most effective storage systems in 1.7-1.10 era, However, for be super-efficient, they need at least a block form of ingots. While Enriched Gold and Reinforced Iron has a block form, Redstone Ingot lacks it. Please add block form for this ingot too, even if currently there is no recipe that uses it.

**Comment by SonarSonic** [comment]
Fixed in dev
