### ISSUE TITLE
[1.10 Feature request] Be able to turn off creative search bar

### ISSUE THREAD

**Issue by MechWarrior99** [SonarSonic/Calculator#157]
In the Calculator creative inventory tab there is a search bar. Which is great for trying to find things, but annoying when trying to use JEI to look up recipes. I was wondering if you could add a config option to disable the search bar, or make it so it will only function after you click on it.

**Comment by SonarSonic** [comment]
I find it annoying as well actually :P It'll be out of the next version, but not 3.0.9 which I just posted.
