### ISSUE TITLE
[1.10 Suggestion] Remove Reinforced Dirt from recipes

### ISSUE THREAD

**Issue by MechWarrior99** [SonarSonic/Calculator#159]
As I was looking at the recipes for machines, I was noticing that Reinforced Dirt being used for things like a Atomic Calculator doesn't really make sense. It's dirt, Reinforced stone makes more sense because it's stone, and it is hard. But reinforced dirt just doesn't make sense to me. 

So my 'suggestion' is to remove reinforced dirt form the ore dict, or change the recipes to not be ore dict recipes.
If you don't like this idea I can always just remove it from the ore dict for my self using Crafttweaker. But I thought it was something that may belong in the mod it self.

**Comment by SonarSonic** [comment]
Fixed in dev
