### ISSUE TITLE
[1.10.2] calculator 1.9.4-3.0.9, sonarcore 1.9.4-3.0.8 Purified obsidian been broken by wither

### ISSUE THREAD

**Issue by Gayanfalor** [SonarSonic/Calculator#161]
Hello,

All is in the tittle, i've updated from calculator 1.9.4-3.0.7 to 3.0.9, i've sen in the 3.0.8 changelog that the purified obsidian cant be broken by the wither so i wanted to test it, but in the fight he could broke them.

**Comment by SonarSonic** [comment]
I couldn't recreate this, seems to be working for me. Try when I release the next update.

**Comment by Gayanfalor** [comment]
I've updated to latest calculator and sonar core but i'm getting a crash report when launching the server
[crash-2016-08-09_09.48.36-server.txt](https://github.com/SonarSonic/Calculator/files/408445/crash-2016-08-09_09.48.36-server.txt)

**Comment by hron84** [comment]
@SonarSonic seems like you keep a strong requirement for ic2 api.

**Comment by SonarSonic** [comment]
This should be fixed now
