### ISSUE TITLE
Crash with Fluxed Redstone pipes

### ISSUE THREAD

**Issue by Shadows-of-Fire** [SonarSonic/Calculator#162]
Attaching any RF pipes from that mod causes the game to crash under this report.
https://gist.github.com/Shadows-of-Fire/1975e888c89c02010618b95341052c13

I don't know whether its on Calulator's end, Tesla's end, or @modmuss50 's end.

**Comment by Shadows-of-Fire** [comment]
Calculator 3.0.9
SonarCore 3.0.8
Tesla 1.2.1.42
Fluxed Redstone 2.3.0.48
Minecraft 1.10.2
Forge 12.18.1.2014

**Comment by SonarSonic** [comment]
Fixed in dev, the problem was Tesla deciding to change their modid

**Comment by modmuss50** [comment]
Forge now requires lower case mod ids, so tesla had to change it.

**Comment by SonarSonic** [comment]
it does? I've had no issues so far....

**Comment by AEnterprise** [comment]
it doesn't require them just yet, it's only printing warnings in the log atm but with the next MC version those warnings will turn into errors
