### ISSUE TITLE
Machines forget configuration when not loaded

### ISSUE THREAD

**Issue by mulch75** [SonarSonic/Calculator#166]
I'm playing All The Mods pack and if my calculator machines are not chunk loaded then they forget their config, things like which side is the output and what upgrades are installed are forgotten. 
If I use a chunk loader this works for a game session but then when reloading the world the config is lost again. Using the latest version of All The Mods (v1.11) which includes Calculator-1.9.4-3.1.0 & SonarCore-1.9.4-3.1.1 running on 1.10.2 forge version 12.18.1.2050

Edit: Blocks I have seen this behaviour with: Processing, Precision and Analysing Chambers and Reinforced Furnace

Edit2: It seems chuck loaders don't work either, the only one I have to test with is the new Extra Utils 2 loader so not sure if it even works!

**Comment by JonaBrackenwood** [comment]
Confirmed, got the same issue.

**Comment by SonarSonic** [comment]
Fixed in dev
