### ISSUE TITLE
Flawless Greenhouse and Carbon Dioxide Generator

### ISSUE THREAD

**Issue by Whorizon** [SonarSonic/Calculator#167]
The Flawless Greenhouse does not update size or oxygen. I've got it to work once in a creative player world but it won't work. Also the Carbon Dioxide Generator will not start burning even with controlled fuel or coal which is upsetting since it has worked once. I have power setup to both of them. I have had one to work before but cannot figure out what I had done to do so. Also the I tried relogging and updating the blocks to see if they needed to be updated like with pistons and still no fix. Please help and thankyou
PS: I am playing the latest Resonant Rise 3 with latest versions.
-Whorizon

**Comment by SonarSonic** [comment]
1.7.10 Versions are no longer supported sorry.

**Comment by Whorizon** [comment]
Oh its not ? Can you tell me how to use it tho?

**Comment by SonarSonic** [comment]
https://github.com/SonarSonic/Calculator/wiki/Flawless-Greenhouse hopefully this is up to date

**Comment by Whorizon** [comment]
I think I found the problem. The greenhouse has to be always on the left and the Carbon Dioxide Generator has to be on the left.

**Comment by SonarSonic** [comment]
Yeah that's intentional
