### ISSUE TITLE
[Suggestion] Increase the blast resistance of Reinforced Stone

### ISSUE THREAD

**Issue by erindal** [SonarSonic/Calculator#169]
![2016-08-23_01 54 22](https://cloud.githubusercontent.com/assets/12499779/17881639/036a7d1c-68d5-11e6-9d39-1fb89e915fa7.png)

This is an example of a single TNT detonated against walls of reinforced stone, reinforced stone bricks, and normal stone bricks. (A shaped charge is obsidian on all sides of the TNT except the wall).

Obviously there isn't a really difference, which doesn't make much sense for a block the starts with reinforced.

**Comment by SonarSonic** [comment]
Good point, i've changed it. Will be different in next SonarCore update

**Comment by SonarSonic** [comment]
Fixed in dev
