### ISSUE TITLE
crashing at start

### ISSUE THREAD

**Issue by Tsukiumy** [SonarSonic/Calculator#17]
i just updated the mod from 1.6.something, and when i start the game, it crashes, here is the log
http://pastebin.com/ULU8fwrU
some1 could help figure the why im getting that error.(the mod list is on the log btw)

**Comment by SonarSonic** [comment]
No idea how that could be happening. But I will have a look on the weekend.

**Comment by SonarSonic** [comment]
I think this is just a problem with your Java in some way, if you've still get the problem you should install a new version if there is one.
