### ISSUE TITLE
Calculator Locator Config

### ISSUE THREAD

**Issue by maxhenkes** [SonarSonic/Calculator#170]
Heya, great mod! We've been using it for a while, but only on the server side we use a modified version of your locator generator (reduce RF/t by half) which works fine, but we want to update to the last version and it seems the github is not up to date.

If you have the time, could you update it? :)

**Comment by AEnterprise** [comment]
mind if i point at the readme file with extra conditions to the licence?

> No re-releases of any form unless I have given expressed permission

and i'm pretty sure he would add a config option for the locator RF gen instead of having people do a custom version

**Comment by maxhenkes** [comment]
No I do not mind because it does not relate to what I am saying. I am PRIVATELY modifying the version, uploading it to my PRIVATE server and NOT on the client. The client uses the version from curse.
The rf gen is decided server side, there is not even a client desync. I am not reuploading, sharing or whatever done. 

I am modifying and privately using the file, I think I'm allowed to do that :)

Also I would love to have a config option, but I saw a few previous tickets asking for it and its not implemented yet so I decided to do my own :P

**Comment by AEnterprise** [comment]
if it's only that and you only edit that one thing then i guess it's indeed compatible with that, sorry. I assumed (wrongfully) that like most you would also be distributing it to the client and others

though it might be easier for you (and others) if there was a config, @SonarSonic has to decide that though

**Comment by maxhenkes** [comment]
Yes a config option would be easier but I assume its not an option because its a fomular and not a simple rf value :P

**Comment by SonarSonic** [comment]
Yeah I have no problem with you using it privately on a server, but yeah you can't distribute it. I might be able to add a multiplier in the config instead, so you can affect the general energy output that way instead.

**Comment by SonarSonic** [comment]
GitHub is updated now

**Comment by maxhenkes** [comment]
Awesome! I have no plans to distribute the custom jar, thanks for the super fast reply :) I'd love a multiplier config :)

**Comment by SonarSonic** [comment]
Added in dev
