### ISSUE TITLE
2 Things with Analyzing Chamber 1.9.4-3.1.1

### ISSUE THREAD

**Issue by koalalord9999** [SonarSonic/Calculator#172]
I'm not sure if this has been fixed in a later release then the one I'm using, but I guess I'll just post both of them.

First: The Analyzing chamber requires no power, so it shouldn't have a power bar inside it.

Second, and more important: When I put a Circuit into the Analyzing Chamber, it analyzes it (doh), but it keeps it in the analyzing spot, instead of moving it into the output area, so that it can be pulled from the chamber and put into an inventory next to it. It seems kind of counter intuitive, seeing as all of the other machines can be setup into a line, that would then go into a chest after processing, that this one machine, the most important one in the line for making Circuits, would of course, be unable to put the circuit into a chest >.>

I saw issue #10 which seems to have been about the same thing, but that was way back in June or July, which said it fixed it... but I don't think it actually did.

MC 1.10.2
Forge unsure, it's a modpack, and I can't seem to locate the folder in which forge is downloaded to
Calculator 3.1.1 (?)

**Comment by AEnterprise** [comment]
can you list your MC, forge and calculator versions?

**Comment by SonarSonic** [comment]
1) Some circuits output power so the bar is still needed.
2) You can still output from the circuit slot by using a wrench to configure. Also it can only be outputted if all items/energy have been removed.

**Comment by koalalord9999** [comment]
I'm using the wrench on the side I want it to output, it's red, which is the item output, green is the circuit input, correct? http://prntscr.com/cfb4rv

**Comment by AEnterprise** [comment]
see the comment above: you need to provide an way for it to output the energy

**Comment by koalalord9999** [comment]
Even when it's empty from passive drain of analyzing them, it still stays there >.>

**Comment by SonarSonic** [comment]
Green is the circuit input and output. Once the circuit is analysed it can be outputted
