### ISSUE TITLE
Dupe bug

### ISSUE THREAD

**Issue by DnTheMn** [SonarSonic/Calculator#174]
So... Calculator includes a recipe that turns 4 blaze powder into 1 blaze rod, and some crushers have the ability to output 4+ blaze powder from 1 blaze rod (macerator, SAG mill, ...)
I started with 3 blaze rods and after a few cycles was nearing a stack. I recommend disabling the calculator recipe if possible.

https://github.com/whatthedrunk/allthemods/issues/176

**Comment by Belgabor** [comment]
That's not a mod bug but a modpack configuration issue. The vanilla relation is one blaze rod to two blaze powder.

**Comment by SonarSonic** [comment]
I think I probably agree with Belgabor, surely 4+ Blaze Powder from one Blaze Rod is overpowered and probably should be changed. Or you could just remove the Calculator Recipe with Minetweaker.

**Comment by DnTheMn** [comment]
thats fine thought i would pass it on anyways :)
