### ISSUE TITLE
Issue : The storage chamber mixed up stable and non stable circuits

### ISSUE THREAD

**Issue by jonabrv1965** [SonarSonic/Calculator#177]
Hello, I'm using the Calculator-1.9.4-3.1.2. and MC 1.10.2/forge 2092.

In the past I used two chambers, one for stable and one for analyzed circuits without problems. But in this version, it seems that something happened to this "de facto" sort. Now this two chambers intermixed the circuits, it is that bad that I have two circuits types that cannot allocate (two stable ones) in neither of two chambers, so I'm ending with a mess of circuits and my inventory clogged with the two circuits

This did not happened in the past with the very same setup (I use enderio item conduits)

In the first attached image the arrows point to analyzed circuits, the rest are stable ones. Those in the circle are stable ones that I cannot place in the chamber (it simple does not allow). In the second image you can see my setup. Where the chamber in the circle is that is showed in the first image and supposedly is the "stable" one chamber, the other (within the square) is the "analyzed" chamber. Where the mod is locating two stable circuits also...

![capture](https://cloud.githubusercontent.com/assets/13445986/18850914/32bf785c-83ff-11e6-9c19-c467319c7417.JPG)
![capture1](https://cloud.githubusercontent.com/assets/13445986/18850952/63fd2310-83ff-11e6-9e5b-557beae13cf7.JPG)

**Comment by SonarSonic** [comment]
Fixed in dev
