### ISSUE TITLE
advanced power cube not outputting power

### ISSUE THREAD

**Issue by Skillotic0703** [SonarSonic/Calculator#18]
When i put a sag mill from ender io next to or on an advanced power cube it doesn't charge it. When i shift right-click a side of the power cube with bare hands, it turns the side white but when i shift right-click another side, it turns that side white but the other side become yellow. It doesn't output power even from a white side. However the input is working.

**Comment by DrWhoCares** [comment]
Advanced Power Cubes need to convert the energy first or something. Honestly i can't remember fully but its safe to say that if you route your power directly to another storage (thermal expansion etc) itll work. I cant check the specifics right now.

**Comment by SonarSonic** [comment]
The power cube is literally just a way of converting RF to EU and its power storage is very small compared to other Energy Cube designs
