### ISSUE TITLE
Flawless Greenhouse non-vanilla grass crash

### ISSUE THREAD

**Issue by whyoonowork** [SonarSonic/Calculator#182]
Issue Description: Building a Flawless Greenhouse on Biomes o' Plenty grass and powering it will crash the server. Normal minecraft grass works fine.

What happens: The Flawless Greenhouse wants to till the BoP dirt, but this must cause the issue when it tries.

What you expected to happen: Tills soil, plants crops, doesn't crash.

Steps to reproduce:
1.   Place Flawless Greenhouse and corresponding multiblock structure on Biomes o' Plenty grass (only tried silty grass)
2.   Power and fill with crop
3.   Crash

This may effect other greenhouses, didn't test.

**Comment by AEnterprise** [comment]
can you provide a crashlog? that will show exactly what crashes as well as all mods (and versions) involved

**Comment by whyoonowork** [comment]
http://pastebin.com/a8VFMj7q

**Comment by SonarSonic** [comment]
Fixed in dev
