### ISSUE TITLE
flawless greenhouse

### ISSUE THREAD

**Issue by shrael** [SonarSonic/Calculator#183]
Im using the greenhouse with wheat seeds and it doesnt seem to want to extract the wheat that gets placed tried conduits and mekanism cables not working with different chests and storage drawers.

**Comment by SonarSonic** [comment]
What versions are you using? Please put this on every issue you post

**Comment by shrael** [comment]
3.1.1

**Comment by SonarSonic** [comment]
Well try updating first then...also is that SonarCore or Calculator, just make sure it's all updated first

**Comment by SonarSonic** [comment]
Fixed in dev
