### ISSUE TITLE
Visual glitch with energy storage blocks

### ISSUE THREAD

**Issue by th4umiel** [SonarSonic/Calculator#184]
![2016-10-05_22 54 59](https://cloud.githubusercontent.com/assets/17257735/19131719/d4483c38-8b50-11e6-81ba-08d18056bd02.png)

As you can see in the image I linked (I hope I linked it right), when only one block is used, it shows an opaque texture. When I use multiple energy storage blocks, the others are correctly transparent but one remains opaque.

**Comment by SonarSonic** [comment]
What version of Flux Networks are you using?

**Comment by th4umiel** [comment]
FluxNetworks-1.9.4-1.0.7

**Comment by SonarSonic** [comment]
Some people have suggested this may be a vanilla issue, I'm not really sure about that though.

**Comment by AEnterprise** [comment]
it looks more like a GL leaked state to me

**Comment by th4umiel** [comment]
1.9.4 guess we can close it
