### ISSUE TITLE
Energy/Speed upgrades are lost

### ISSUE THREAD

**Issue by iggyk** [SonarSonic/Calculator#185]
Sometimes during the game the WAILA float "resets" to not showing upgrade information (solved when going to block inventory screen and back); regardless, when ejected, the upgrades pop out.

After save, however, they are lost completely.

**Comment by SonarSonic** [comment]
Which blocks are you losing upgrades on

**Comment by SonarSonic** [comment]
I've fixed issues with Syncing, I can't find issues with the upgrades actually being completely lost

**Comment by AEnterprise** [comment]
@SonarSonic can i sugest you make a issue template for github with questions to answer for people? things like MC version, calc version, logs, ...

**Comment by SonarSonic** [comment]
@AEnterprise that sounds like a very good idea....

**Comment by iggyk** [comment]
It was on all blocks, but then I figured I was running an outdated version.
In recent versions the upgrades didn't get lost, but still didn't show up in the tooltip. But I guess you addressed that already :+1:
