### ISSUE TITLE
[1.10.2] Direct crash after placing handcranked generator

### ISSUE THREAD

**Issue by Gayanfalor** [SonarSonic/Calculator#186]
Please fill out the details below before contributing
- Forge Version:  2113
- Calculator Version: 1.9.4-3.1.2
- SonarCore Version:  1.9.4-3.1.6
- Multiplayer or Singleplayer:  Multiplayer
- Crash Report Link: https://drive.google.com/open?id=0B9iNaLFrsdUpX0hvOXdNNDFhZEU
- Affected Features: Direct crash a,d after too when trying to relog into server
- Description:

**Comment by SonarSonic** [comment]
Fixed in dev
