### ISSUE TITLE
Machines only take coal (Bug or Feature?)

### ISSUE THREAD

**Issue by ghost** [SonarSonic/Calculator#188]
Please fill out the details below before contributing

 * Forge Version: 12.18.2.2116
 * Calculator Version: 1.9.4-3.1.2
 * SonarCore Version: 1.9.4-3.1.6
 * Multiplayer or Singleplayer: SSP
 * Crash Report Link: N/A
 * Affected Features: Powering Separator, Greenhouse, Powercube
 * Description: The devices only accept coal and coal blocks. Other fuels, even vanilla don't seem to work. Note: I've just started so I've only tried charcoal and various forms of wood.

**Comment by SonarSonic** [comment]
This is intentional. These machines are not supposed to run off typical fuel. They run off Calculator Fuels and Redstone + Coal. You'd be better off powering them with RF
