### ISSUE TITLE
Relentless console spam. Removing affected block makes it worse (1.10.2)

### ISSUE THREAD

**Issue by Boomflex** [SonarSonic/Calculator#191]
* Forge Version: 12.18.2.1271
 * Calculator Version: 1.94.-3.12
 * SonarCore Version: 1.94-3.16
 * Multiplayer or Singleplayer: Multiplayer
 * Crash Report Link: n/a
 * Affected Features: 
 * Description:  https://gyazo.com/b069eedfd3eb4ea65aa81f30a4b7fd09

Creates TPS issues when the affected block is broken, taking TPS down to less than 5...

This constantly spams console until a restart.

**Comment by SonarSonic** [comment]
Fixed in dev- although let me know if it persists...

**Comment by Boomflex** [comment]
It 100% persists.

Even worse this time.

http://pastebin.com/rTTArxKw

**Comment by whatthedrunk** [comment]
Don't know if this helps but. 
"asie - whoever makes that mod - let them know accessing neighbors in onLoad is a big no-no. They should still do it on the first update()... and adding things to the IC2 enet = accessing neighbors"

**Comment by AEnterprise** [comment]
different error this time, different cause, but asie is right, accessing anything other then the block being loaded or your own static classes that you are 100% have been initialised is bad. the world around you is still loading so you can't be sure that things are initialized and ready to go

**Comment by SonarSonic** [comment]
Ohh dam.. my bad. I did change it to the first tick but for some reason it actually complied wrong. Should have tested the mod jar

**Comment by BytesByBytes** [comment]
This is still an issue for me the continual console spam

Calculator-1.10.2-3.2.5
SonarCore-1.10.2-3.3.0
Forge Version 13.18.3.2422

[Log](https://pste.me/#/bTBsN)

Due to the amount of console spam from calculator i am unable to give a full log as it is way too big
