### ISSUE TITLE
[FEATURE] Please add back docking stations

### ISSUE THREAD

**Issue by hron84** [SonarSonic/Calculator#194]
Please fill out the details below before contributing

 * Forge Version: 2185
 * Calculator Version: 3.1.2
 * SonarCore Version: 3.1.6
 * Multiplayer or Singleplayer: both 
 * Crash Report Link: -
 * Affected Features: Calculators
 * Description: I really miss docking stations for calculators. Dynamic calculator can help at some point, but it's hard to automate. I'd prefer a block-form of each calculator type or adding back the docking station to automate things like reinforced/stable stone (one of my favorite blocks in the mod).

**Comment by SonarSonic** [comment]
Fixed in dev
