### ISSUE TITLE
[ENHANCEMENT] OreDict entries for fruits

### ISSUE THREAD

**Issue by hron84** [SonarSonic/Calculator#195]
Please fill out the details below before contributing

 * Forge Version: 2185
 * Calculator Version: 3.1.2
 * SonarCore Version: 3.1.6
 * Multiplayer or Singleplayer: both 
 * Crash Report Link: -
 * Affected Features: Trees/Fruits
 * Description: Please add cropPear and cropBroccoli OreDict entries to the matching fruits/vegetables. It would make these stuff compatible with HarvestCraft recipes.

**Comment by SonarSonic** [comment]
Fixed in dev
