### ISSUE TITLE
Flawless calculator bugged and voiding items

### ISSUE THREAD

**Issue by BloodWorkXGaming** [SonarSonic/Calculator#197]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2185
 * Calculator Version: 1.10.2-3.1.4
 * SonarCore Version: 1.10.2-3.1.9
 * Multiplayer or Singleplayer: both
 * Affected Features: Flawless calculator
 * Description:
The flawless calculator void the rightmost (fourth) item and exchanges it with the crafting result. See video for more info. If the calculator is attached to the docking station it does work however.

[Video showing bug](https://youtu.be/ah_a2_rgRIs)

**Comment by SonarSonic** [comment]
Fixed in dev
