### ISSUE TITLE
Calculator Recipes don't ignore NBT data

### ISSUE THREAD

**Issue by BloodWorkXGaming** [SonarSonic/Calculator#198]
Please fill out the details below before contributing

* Forge Version: 12.18.3.2185
* Calculator Version: 1.10.2-3.1.4
* SonarCore Version: 1.10.2-3.1.9
* Multiplayer or Singleplayer: both
 * Affected Features: most crafting recipes in calculators
 * Description:
Crafting using a calculator doesn't ignore NBT Data, therefore it is not possible to craft certain item like the Carbon Dioxide Generator. For other crafting recipes where e.g. a energie module is needed you gotta use a perfectly new one that has no added nbt data yet and isn't charged in any way.

**Comment by SonarSonic** [comment]
Fixed in dev

**Comment by AEnterprise** [comment]
how is this fixed? does it always fully ignore nbt? if so that might not be an ideal fix, if another mod like crafttweeker adds in a nbt sensitive recipe that will break now, or if you later add in multiple items only diffirentiated by nbt

**Comment by SonarSonic** [comment]
Added a constructor variable to the RecipeItemStack to enable/ignore NBT, although for craft tweaker I'll make it enabled by default.
