### ISSUE TITLE
Flawless crafting does not consume first three slots and deletes fourth slot

### ISSUE THREAD

**Issue by mandrewpowers** [SonarSonic/Calculator#199]
Please fill out the details below before contributing

 * Forge Version: `12.18.3.2185 (MC 1.10.2)`
 * Calculator Version: `3.1.4`
 * SonarCore Version: `3.1.9`
 * Multiplayer or Singleplayer: `Multiplayer`
 * Crash Report Link: `N/A`
 * Affected Features: `Flawless Calculator` / `Flawless Crafting`
 * Description: 
When using the flawless calculator in flawless crafting mode I tried to insert four iron ingots to craft an ender pearl. I insert the first three; no issue. I insert the fourth iron ingot and it immediately deletes the ingot and replaces it with an ender pearl. The first three iron ingots are not consumed. The product of the recipe appears in the fourth slot instead of the fifth.

I am able to remove the first three ingots and take the resulting ender pearl from slot four and use them.

**Comment by SonarSonic** [comment]
Same as #197

**Comment by mandrewpowers** [comment]
Forgot to check closed issues, my bad!
