### ISSUE TITLE
Circuit duplication bug

### ISSUE THREAD

**Issue by Skillotic0703** [SonarSonic/Calculator#20]
When putting a dirty/damaged circuit in a storage chamber and outputting with item conduit (from ender IO) the circuits to a processing chamber, the last circuit is duplicating. It stays in the storage chamber but there are fixed circuits generated. I putted 64 circuits and later i saw more than 200 circuits !!!

**Comment by Skillotic0703** [comment]
Calculator 1.7.7 - Stable

**Comment by SonarSonic** [comment]
Ender IO's fault but I'll see if there is anything I can do.

**Comment by SonarSonic** [comment]
Fixed in Dev
