### ISSUE TITLE
Game/Server crashes when trying to pipe item into precision chamber

### ISSUE THREAD

**Issue by BloodWorkXGaming** [SonarSonic/Calculator#200]
* Forge Version: 12.18.3.2185
 * Calculator Version: 3.1.4
 * SonarCore Version: 3.1.9
 * Multiplayer or Singleplayer: both
 * Crash Report Link: 
    - http://pastebin.com/5UjbjEaY
    - http://pastebin.com/KTkM8P0m

 * Affected Features: item exchange and precision chamber
 * Description:
When piping item like cobblestone in an precision chamber it crashes the game and server.
This happens with multiple types of pipes including extra util2 nodes and enderio conduits.

**Comment by BloodWorkXGaming** [comment]
In addition to that here is another crash log that has happened when attaching conduits to the atomic multiplicator:
[http://pastebin.com/gCtNXy3v](http://pastebin.com/gCtNXy3v)

Probably the complete item exchange implementation is broken....

Working with hoppers however is completely fine and doesn't cause a crash.

**Comment by SonarSonic** [comment]
Hopefully this should be fixed in the next update...

**Comment by SonarSonic** [comment]
You'll need to update SonarCore

**Comment by SonarSonic** [comment]
This was fixed in the latest versions of SonarCore & Calculator :)
