### ISSUE TITLE
[1.10.2] Can't extract energy from Calculator Locator

### ISSUE THREAD

**Issue by barnumbirr** [SonarSonic/Calculator#201]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2185
 * Calculator Version: 3.1.5
 * SonarCore Version: 3.2.P
 * Multiplayer or Singleplayer: both
 * Affected Features: Can't extract energy from Calculator Locator
 * Description: Have tried EnderIO / Mekanism / Solar Flux Reborn Cables, none of them seem to be able to extract energy from the bottom of the Calculator Locator. Have also tried putting EnderIO capacitors as well as Mekanism Enery Cubes directly underneath the Locator block, same result.
Have I missed something or is this broken?

Cheers.

**Comment by SonarSonic** [comment]
Can't recreate this either, all of the ones you've mentioned are working fine for me.

**Comment by barnumbirr** [comment]
I'll try and make a screencast to show the issue. Won't be before the end of the week though.

**Comment by ate0ate** [comment]
I am currently having this issue with pulling power from the bottom of the conductor mast in single player. No block or conduit/pipe in any push/pull configuration has any effect. I have not yet tried the calculator locator.
Forge: 12.18.3.2221
Calculator: 3.1.6
SonarCore: 3.2.1
I do have quite a large mod pack that isn't too dissimilar to the All The Mods pack. I do indeed use Foamfix, if that makes any difference. I will test further.

**Comment by davqvist** [comment]
So, I just had the same problem with not being able to extract power from a Conductor Mast, weirdly only on the Development Server I'm running for my upcoming modpack. In Singleplayer it works fine. The Conductor Mast outputs fine into an Advanced Power Cube, but I can't get power out of that Power Cube either, again only on the Server. I haven't tested the Calculator Locator yet on the Server, but in Singleplayer it works fine. I can give you access to the server if you want to test it or if you need more info, just contact me.

Calculator: 3.1.6
Forge 12.18.3.2215 (will update Forge probably tomorrow and test again)

**Comment by davqvist** [comment]
Quick correction: I can get power out of the Advanced Power Cube, forgot to sneak right click to change it to output, so this is a way to get power out of the Conductor Mast, but connecting other cables to it doesn't work.

**Comment by SonarSonic** [comment]
This should be fixed now. Can anyone confirm?

**Comment by davqvist** [comment]
I think this is fixed, at least I couldn't replicate it.
