### ISSUE TITLE
ModTweaker interaction broken

### ISSUE THREAD

**Issue by davqvist** [SonarSonic/Calculator#202]
* Forge Version: 12.18.3.2202
 * Calculator Version: 3.1.5
 * SonarCore Version: 3.2.0
 * Multiplayer or Singleplayer: Singleplayer, haven't tested Multiplayer
 * Crash Report Link: minetweaker.log http://pastebin.com/07RLu8v8 and ModTweaker Script: http://pastebin.com/JtGVhgAy (this is just a excerpt from all the recipes I changed because of all the mod dependencies)
 * Affected Features: Modtweaker interaction doesn't work anymore.
 * Description: 
So I updated now that the Capabilites are working (thanks again a lot) from Calculator 3.1.2 to 3.1.5 for the modpack I'm working on, but now all my ModTweaker scripts are broken. Removing a recipe leads to errors as you can see in the modtweaker.log and adding recipe (you need to add Immersive Engineering to test my linked script) leads to no errors, works but doesn't show in JEI. Flawless Calculator for example has the same issues. I'm reverting back to the old version, so that I can at least continue to test with my beta testers. 

To test for yourself, add those mods:
ModTweaker 2.0.9
CraftTweaker 3.0.17
MTLib 1.0.1
Immersive Engineering 0.10.54
JEI 3.14.2.401

**Comment by SonarSonic** [comment]
This is because in the new versions Minetweaker recipes must be removed by the Output not the Input so...

```
mods.calculator.basic.removeRecipe(<calculator:CoalDust>, <calculator:CoalDust>);
```
should now be

```
mods.calculator.basic.removeRecipe(<calculator:EnrichedCoal>);
```

**Comment by davqvist** [comment]
Oh I didn't know that. Thanks for telling me, but still JEI doesn't show the changes, neither the removed recipes disappear nor the new ones get shown. Is this a problem of JEI, Modtweaker or Calculator? I'm assuming Calculator because I don't have this issue with other mods.

**Comment by davqvist** [comment]
So I asked Jared and he said, you have to update due to the latest CraftTweaker API changes: https://github.com/jaredlll08/CraftTweaker/issues/136

**Comment by jaredlll08** [comment]
@SonarSonic nope, you need to call MinetweakerAPI.getIJEIRecipeRegistry.AddRecipe()
like in this class
https://github.com/jaredlll08/MTLib/blob/master/src/main/java/com/blamejared/mtlib/utils/BaseListAddition.java#L32

**Comment by davqvist** [comment]
Thanks for the 3.1.7 update. Not sure if I should open a new issue, so anyway: Adding recipes now are displayed in JEI correctly, but removing still isn't removed in JEI. Also /mt reload will have the effect that every recipe will be shown twice. I suspect that may be the same issue as the recipes are not removed correctly before re-adding them in.

**Comment by davqvist** [comment]
Hi, I just wanted to let you know that this is still broken, but the issue is still closed. I'm close to releasing my modpack and that removed recipes still appear in JEI is a problem. (And showing an added recipe twice after /mt reload is a problem as well, but of course less important) I would appreciate it if you have a look at it. Thanks in advance.
