### ISSUE TITLE
Advanced Greenhouse doesn't lose power for planting and harvesting anymore

### ISSUE THREAD

**Issue by davqvist** [SonarSonic/Calculator#203]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2202
 * Calculator Version: 3.1.6
 * SonarCore Version: 3.2.1
 * Multiplayer or Singleplayer: Both
 * Crash Report Link: -
 * Affected Features: Advanced Greenhouse doesn't lose power for planting and harvesting anymore
 * Description: I haven't tested it with the other Greenhouses but the Advanced Greenhouse doesn't use up power after the initial build and plant. I'm pretty sure that was different a few updates ago. I thought this is caused by the right click harvest because I noticed this bug in my Actually Additions Canola farm which you can harvest by right click but then I tested it in a test world with Prunae Seeds and there it didn't use power either.

**Comment by SonarSonic** [comment]
Fixed in dev
