### ISSUE TITLE
You can't demolish Advanced Greenhouse, it dupes Wood instead.

### ISSUE THREAD

**Issue by davqvist** [SonarSonic/Calculator#207]
* Forge Version: 12.18.3.2221
 * Calculator Version: 3.1.6
 * SonarCore Version: 3.2.1
 * Multiplayer or Singleplayer: Both
 * Crash Report Link: no crash
 * Affected Features: You can't demolish Advanced Greenhouse, it dupes Wood instead.
 * Description: So when you click on demolish on the Advanced Greenhouse (haven't tried the normal one yet), it doesn't actually demolish it, it just outputs wood logs into the internal inventory, duping it. I'm pretty sure that worked a couple updates ago, so a recent update must have caused that.

**Comment by SonarSonic** [comment]
Fixed in dev
