### ISSUE TITLE
Unable to Export [Docking Station] [1.10.2]

### ISSUE THREAD

**Issue by PureSp1r1t** [SonarSonic/Calculator#208]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2185
 * Calculator Version: 1.10.2-3.1.6
 * SonarCore Version: 1.10.2-3.2.1
 * Multiplayer or Singleplayer: Multiplayer
 * Crash Report Link: N/A
 * Affected Features: Docking Station

I'm really struggling exporting from the docking station. The wiki clearly states to export from the top or bottom of the block. I've tried EnderIO conduits, transfer pipes, Refined Storage importer and even a hopper. I've also tried a PA Wrench on every single side of the block, which of course makes no difference.

I'm aware there is an update available for both SonarCore and Calculator, however I can't see anything about the Docking Station in the changelog, plus I get the feeling I may be doing something wrong.

**Comment by dabigmoose** [comment]
I am experiencing same bug, I have all the latest version and while docking station imports fine their is no way to export. I have tried Hopper, enderio, mekanism and even a plain old chest and nada

**Comment by SonarSonic** [comment]
Fixed in dev
