### ISSUE TITLE
Circuit Processing Machines have memory leak

### ISSUE THREAD

**Issue by davqvist** [SonarSonic/Calculator#210]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2221
 * Calculator Version: 3.1.7
 * SonarCore Version: 3.2.2
 * Multiplayer or Singleplayer: Multiplayer
 * Crash Report Link: 
 * Affected Features: Circuit Processing Machines have memory leak
 * Description: So, since the last update that I did to the server with the 3.1.7 version of Calculator I was experiencing sincere TPS drops, going down to like 8 TPS, never had that happened before. I ran TickProfiler and it listed all Circuit Processing machines (Precision chamber, Reassambly Chamber, etc.) with like 50 time/tick while every other tile entities were lower than 1. Clicking on the pause button on those machines puts the server at 20 TPS again right away. Also restarting the server with the machines running let the server run at 20 tps and it's steadily slowly dropping. So it looks like a kind of memory leak or something similar. As we're experiencing it only since the 3.1.7 update I guess it has to be because of a recent change of yours. But this issue is pretty critical. If it would help you profiling this issue, I can invite you to our server, let me know.

**Comment by davqvist** [comment]
So it seems that not only circuit machines are affected. A modpack dev user noticed severe fps drops when the Algorithm Separator and the Stone Separator were running. I didn't experience those with mine, but going to his base I could confirm this. And running the TickProfiler on the server when his or my Algorithm Separator were running, it was by far the most server-tps-stressing machine in both occassions.

**Comment by SonarSonic** [comment]
Fixed in dev

**Comment by SonarSonic** [comment]
The update will be to SonarCore not calculator
