### ISSUE TITLE
Fabrication Chamber fails to fabricate recipes with different circuits

### ISSUE THREAD

**Issue by davqvist** [SonarSonic/Calculator#211]
* Forge Version: 12.18.3.2221
 * Calculator Version: 3.1.7
 * SonarCore Version: 3.2.2
 * Multiplayer or Singleplayer: both
 * Crash Report Link: 
 * Affected Features: Fabrication Chamber fails to fabricate recipes with different circuits
 * Description: 
Whatever recipe for the Fabrication Chamber requires multiple different circuits doesn't craft, tested with Atomic Module and Calculator recipes. The Calculator Assembly for example requires multiple circuits as well, but from one type and works therefore. I can't find a lot of information about the Fabrication Chamber, maybe I'm doing something wrong, but I just have two Storage Chambers on each side of the Fabrication Chamber with the needed circuits (one with normal / one with stables) in them. Does it need power for these recipes?

**Comment by SonarSonic** [comment]
Fixed in dev
