### ISSUE TITLE
Bad performance/fps when machines are crafting

### ISSUE THREAD

**Issue by Sovereignty89** [SonarSonic/Calculator#212]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2221
 * Calculator Version: 1.10.2-3.1.7
 * SonarCore Version: 1.10.2-3.2.2
 * Multiplayer or Singleplayer: Both
 * Crash Report Link: N/A
 * Affected Features: All machines
 * Description: When machines are crafting FPS drops significantly

![2017-02-10_16 39 59](https://cloud.githubusercontent.com/assets/6663736/22833004/8caba01c-efb0-11e6-802e-211faffa2258.png)
This is on the server where I play on, top right shows fps, same numbers as when I press F3. Large base so the fps is 70.

![2017-02-10_16 40 27](https://cloud.githubusercontent.com/assets/6663736/22833031/a756b9ce-efb0-11e6-88c0-d06456c3cc4d.png)
This is while the Precision Chamber is crafting, I drop down to 13 fps for no apparent reason.

![2017-02-10_16 44 36](https://cloud.githubusercontent.com/assets/6663736/22833054/be64e1e0-efb0-11e6-9ebe-e9831679895e.png)
New SSP world, empty flat, 100+ fps.

![2017-02-10_16 44 40](https://cloud.githubusercontent.com/assets/6663736/22833067/ce3ee3d6-efb0-11e6-8fd7-97a6a4b56677.png)
Down to 20 when the machine start crafting.

![2017-02-10_16 46 01](https://cloud.githubusercontent.com/assets/6663736/22833088/e8c26da4-efb0-11e6-8a7f-f580c2fe9565.png)
Different machine, again 100+ fps.

![2017-02-10_16 46 05](https://cloud.githubusercontent.com/assets/6663736/22833109/fb8a3912-efb0-11e6-9435-5e75527fdc68.png)
Crafting starts and down to the low 20s.

If more information is necessary I'll be happy to provide.

**Comment by prozacgod** [comment]
As an addendum, I was helping Sovereignty89 with seeing if I could reproduce, I have an nvidia GTX 980ti, and run under Linux, with no issues.  He has an ati RX 290X

This, also happened during our messing around. ( https://github.com/SonarSonic/Calculator/issues/213 )

**Comment by SonarSonic** [comment]
Please update sonarcore
