### ISSUE TITLE
Crash to Desktop when Moving a Fabrication chamber

### ISSUE THREAD

**Issue by prozacgod** [SonarSonic/Calculator#213]
Please fill out the details below before contributing

 * Forge Version: forge-1.10.2-12.18.3.2221-universal.jar
 * Calculator Version: Calculator-1.10.2-3.1.7
 * SonarCore Version: SonarCore-1.10.2-3.2.2
 * Multiplayer or Singleplayer: Multiplayer
 * Crash Report Link: https://gist.github.com/prozacgod/30a4944d4ad3819da02ff8c4d75ebe14
 * Affected Features: General gameplay, crash to desktop within the fabrication chamber
 * Description: A friend was moving the fabrication chamber and placing it next to a storage chamber, while I was assisting him with his diagnosis of another issue ( https://github.com/SonarSonic/Calculator/issues/212 )

Possible related, probably not likey?

**Comment by SonarSonic** [comment]
That's weird, i'll be looking into it

**Comment by AEnterprise** [comment]
how was he moving the chamber? broke and replace the block or did he use a moving wand or similar?

**Comment by SonarSonic** [comment]
Fixed in dev
