### ISSUE TITLE
Client crash Tesselating StoneSeparator

### ISSUE THREAD

**Issue by OrdinatorStouff** [SonarSonic/Calculator#214]
* **Forge Version:** 12.18.3.2221
 * **Calculator Version:** 1.10.2-3.1.7
 * **SonarCore Version:** 1.10.2-3.2.3
 * **Multiplayer or Singleplayer:** SMP
 * **Crash Report Link:** http://pastebin.com/9p3C26Cm
 * **Affected Features:** tile.StoneSeparator // sonar.calculator.mod.common.block.SmeltingBlock)
 * **Description:** This was reported to us in the AllTheMods Discord. User would CTD on login, but Server would continue/persist. Trying to /fill the reported block with air reportedly did not work either. This is a mostly brand-new world with very little progress/development.

**Comment by SonarSonic** [comment]
Fixed in dev
