### ISSUE TITLE
Water bucket not returned in crafting recipe

### ISSUE THREAD

**Issue by gioporta** [SonarSonic/Calculator#215]
* Forge Version: 1.10.2-12.18.3.2221
 * Calculator Version: 3.1.7
 * SonarCore Version: 3.2.3
 * Java Version: 1.8.0_91
 * Multiplayer or Singleplayer: Both
 * Description: 
Recipes that use a water bucket as an ingredient do not return an empty bucket afterwards. Through the process of elimination in my pack, I have narrowed the issue down to Calculator. The recipes I am testing are the ones from Harvestcraft. With only Calculator, SonarCore, and HarvestCraft installed - the issue exists. When I remove Calculator, the issue goes away.

Same issue as #47 from 2015

Example:
![Recipe Broken GIF](https://cloud.githubusercontent.com/assets/14063450/22847449/c66d5016-efa1-11e6-836c-6b9ac13d4c8c.gif)

**Comment by gioporta** [comment]
I went back through the old versions and discovered that this bug only exists in Calculator 3.1.3+ and SonarCore 3.1.7+ which were apart of the Christmas update.

This means that any change between September 21 and December 25 could be responsible for this. I'm guessing it might be 2a23973 since it makes changes to recipe handling.

**Comment by AEnterprise** [comment]
@SonarSonic if this is a result of your recipe code then there is something very wrong with how it works. Your recipe handler is somehow (didn't have time to look in the code) handeling recipes that are not your recipes or atleast impacting them

as for the bug itself: at the very least the crafting code is missing a container item check and handeling

**Comment by SonarSonic** [comment]
Was an issue with some recipes with Water Buckets. My bad.
