### ISSUE TITLE
Stone Seperator Crashes Client/Error on server.

### ISSUE THREAD

**Issue by Fundryi** [SonarSonic/Calculator#217]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2221
 * Calculator Version: 1.10.2-3.1.7
 * SonarCore Version: 1.10.2-3.2.3
 * Multiplayer or Singleplayer: Server = Error / Client = Crash
 * Crash Report Link: 
  Client: http://cdn.pasteraw.com/jsnlhn9f457pdmo3sgx8iyr9jnbsinv 
  Server: http://cdn.pasteraw.com/r5rkygcxfrvje21c0ejo86uy9arww4v
 * Affected Features: https://gyazo.com/e4ac7943ed7f1a5484c5665ef87559de
 * Description: The Client chashes after I place the Stone Seperator on the ground.

**Comment by SonarSonic** [comment]
Fixed in dev. Update Calculator to 3.1.8
