### ISSUE TITLE
Client Crash when crafting in calculator

### ISSUE THREAD

**Issue by Noobsloth** [SonarSonic/Calculator#22]
Using version 1.7.9.

Put cobble & planks into regular calculator to make reinforced stone. Try to get the stone out, and this crash happens.

http://hastebin.com/jagimexuyu.1c

**Comment by SonarSonic** [comment]
did this happen straight away or did it work for a while first?

**Comment by SonarSonic** [comment]
Try the new version :)

**Comment by Noobsloth** [comment]
Gonna test it tonight when I get home. Thank you so much for your quick response!

:D

**Comment by Tedyhere** [comment]
Well that fixed the crash but the crafting weirdness is back with the calculator

**Comment by SonarSonic** [comment]
Really?? I have no idea then.

**Comment by SonarSonic** [comment]
has it improved or changed in any way?

**Comment by SonarSonic** [comment]
i'll open the other issue again

**Comment by Tedyhere** [comment]
I asked a few people for any ideas.. Ganymede I think is taking a peek at it
