### ISSUE TITLE
Hunger/Health Processor crashes Client.

### ISSUE THREAD

**Issue by Fundryi** [SonarSonic/Calculator#220]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2221
 * Calculator Version: 1.10.2-3.1.8
 * SonarCore Version: 1.10.2-3.2.3
 * Multiplayer or Singleplayer: Playing on a server but only client side crash.
 * Crash Report Link: http://pastebin.com/raw/ge244ZVt
 * Affected Features: https://i.gyazo.com/07e2f639288587b35066b27d8f85b522.png https://i.gyazo.com/3a83fcc7048f85aa946f289406be04b0.png
 * Description: As soon as you put an Item in one of the blocks it crashes.

**Comment by SonarSonic** [comment]
Fixed in dev
