### ISSUE TITLE
Can put items in Algorithm or Stone Separator 

### ISSUE THREAD

**Issue by dabigmoose** [SonarSonic/Calculator#221]
Please fill out the details below before contributing

 * Forge Version: 2185
 * Calculator Version: 3.1.8
 * SonarCore Version: 3.2.3
 * Multiplayer or Singleplayer: mp
 * Crash Report Link: https://paste.ee/p/tIEMu
 * Affected Features: 
 * Description: Tried to place iron ore in ston seperator and crash to desktop, tried placing lapis in algorithm separator and crash to desktop

**Comment by MysticAura** [comment]
I'm also having this issue. Calc usually is a very stable mod, so all these crash bugs lately are surprising. I look forward to them being resolved.

**Comment by SonarSonic** [comment]
Fixed in dev
