### ISSUE TITLE
Flawless Greenhouse Not Planting

### ISSUE THREAD

**Issue by BigFriendlyJakey** [SonarSonic/Calculator#223]
Please fill out the details below before contributing

 * Forge Version: 1.10.2-Forge1.10.2-12.18.3.221
 * Calculator Version: 1.10.2-3.1.9
 * SonarCore Version: 1.10.2-3.2.4
 * Multiplayer or Singleplayer: Singleplayer
 * Crash Report Link: No Crash
 * Affected Features: Flawless Greenhouse
 * Description: Flawless Greenhouse does not plant Brocolli. All machines have power, CO2 Generator has fuel, and greenhouse is set up as wiki shows. Has been tested with multiple CO2 levels.

**Comment by BigFriendlyJakey** [comment]
Update: I have now realised it's not planting because it doesn't become a multiblock structure when I put the stable stone on top of the machines. Is it always meant to? It can detect how large I've made the farm either way :/

**Comment by bryce-happel-walton** [comment]
Can confirm it doesn't plant
It also uses energy when not in use

**Comment by trechetican** [comment]
same problem here. same versions as above

**Comment by SonarSonic** [comment]
Fixed in dev
