### ISSUE TITLE
Docking station

### ISSUE THREAD

**Issue by Player505** [SonarSonic/Calculator#225]
Please fill out the details below before contributing

Forge Version: 12.18.3.2221

Calculator Version: 3.1.9

SonarCore Version: 3.2.5

Multiplayer or Singleplayer: Singleplayer

Crash Report Link: No Crash

Affected Features: Docking station inventory access

Description: (Imgur.com/a/RF5PB) Docking station is not accepting item input from all 4 sides. The hoppers outlined in green can push items whilst the ones in red can't. Thus making is so that in flawless calculator crafting it can only access the first two inventory slots

**Comment by BigFriendlyJakey** [comment]
Having the same problem, hope it all gets updated soon :/

**Comment by hron84** [comment]
Fixed ImgUr link: http://imgur.com/a/RF5PB

**Comment by FSDel** [comment]
For me docking stations will not even craft items.
Calculator works if it's in my hand, but place it on the docking station.. can't craft.
Yes, it does have power.

**Comment by SonarSonic** [comment]
Item accepting has been fixed. I can't recreate the crafting issue @FSDel . It works for me, what recipe are you trying?

**Comment by FSDel** [comment]
I tried 4 wood -> Obsidian just now, trying with just enderio and calculator installed via Curse.

although it seems any recipe fails for me. However, trying it in a SP world... it will craft if i leave the recipe in the docking station, and relog....

**Comment by SonarSonic** [comment]
So it's a client/server sync issue in that case. which i think I may have resolved anyway. see how you get on when the new version comes out @FSDel

**Comment by FSDel** [comment]
Great! looking forward to it!

**Comment by SonarSonic** [comment]
New version is out.
