### ISSUE TITLE
Ticking block entity: Reinforced Furnace

### ISSUE THREAD

**Issue by bryce-happel-walton** [SonarSonic/Calculator#226]
* Forge Version: 12.18.3.2239
 * Calculator Version: 3.1.9
 * SonarCore Version: 3.2.5
 * Multiplayer or Singleplayer: Singleplayer
 * Crash Report Link: http://pastebin.com/e4g7NKgs
 * Affected Features: World
 * Description: I don't know what happened but from the report it looks like the electric furnace was smelting something

**Comment by SonarSonic** [comment]
Fixed in dev
