### ISSUE TITLE
Minetweaker Recipe Removal

### ISSUE THREAD

**Issue by jumpsplat120** [SonarSonic/Calculator#228]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2221
 * Calculator Version: 3.1.9
 * SonarCore Version: 3.2.5
 * Multiplayer or Singleplayer: Singleplayer
 * Crash Report Link: Not a crash, but a failure to remove a recipe via minetweaker.
 * Affected Features: Minetweaker integration
 * Description: Attempting to remove the lantern recipe from the basic calculator gives a error

`a method available but none matches the parameters (minetweaker.item.IItemStack, minetweaker.item.IItemStack) This is usually an error in your script, not in the modremoveRecipe(ZenTypeNative )`

The line used that is causing the error is 

`mods.calculator.basic.removeRecipe(<minecraft:torch>, <calculator:ReinforcedIronIngot>);`

I also have a line adding a recipe to replace the one that I am removing, and I'm not having any problems with it. That line is

`mods.calculator.basic.addRecipe(<realistictorches:TorchLit>, <calculator:ReinforcedIronIngot>, <calculator:Lantern>);`

**Comment by Bartz24** [comment]
Also, when adding a calculator recipe (any type is effected), JEI leaves the recipe after reloading the recipes.
I haven't tested removing a recipe, but I would assume it would leave the recipe in JEI.

The recipes still work though.

**Comment by SonarSonic** [comment]
@jumpsplat120 to remove a recipe you must put in the output not the input

**Comment by jumpsplat120** [comment]
Ah. The examples page Minetweaker provides is not correct then.

`https://gist.github.com/AEnterprise/b209f9bd2432286eaf79`

**Comment by SonarSonic** [comment]
@jumpsplat120 that is very outdated. I'll add a new one some time
