### ISSUE TITLE
Calculator Locator Energy Generation

### ISSUE THREAD

**Issue by zzApotheosis** [SonarSonic/Calculator#23]
First of all, thank you for maintaining such a fun and creative mod! I've definitely had a lot of fun with it!

I tested this on a creative world and it seems that a Calculator Locator of any size will always generate 100,000 RF/t when the energy is exported through something like a Cryo-Stabilized Fluxduct (Thermal Dynamics) even when the Locator itself states a specific power output. And I discovered that the power output stated in the Locator itself (i.e. 1000 RF/t) will be correct when exporting the energy through a Flux Plug. These are the only transfer methods that I tested.

I don't know if this was intentional (probably not), but I'm not complaining... 100,000 RF/t is incredible and I'd honestly like to keep it the way it is. It's a pet peeve of mine to maintain accuracy in most cases, so the actual power output should match what the Locator states is the output. 

Perhaps you could have the maximum Calculator Locator size (21x21) output 100 kRF/t and have the minimum Calculator Locator size (3x3) output 1000 RF/t. That could further balance the mod.

**Comment by SonarSonic** [comment]
Thank You. Sounds like a bug to me, they are meant to have a formula to calculate it for each one and 100,000 RF/t is very over-powered. So i'll probably have to fix this.

**Comment by zzApotheosis** [comment]
Also, I noticed that the Calculator Locator would continue to output power even after the Locator Module is removed. Definitely a bug there.

**Comment by SonarSonic** [comment]
Yeah I'll sort that one out.

**Comment by SonarSonic** [comment]
Fixed in 1.8.2
