### ISSUE TITLE
Implementation with the Ender IO Farming station (Tool ID's)

### ISSUE THREAD

**Issue by TheChaosWitcher** [SonarSonic/Calculator#231]
Hello Everybuddy,

on a local Moddpackserver (The GoldenCobblestone) i want to use the Calculator Tools in the Ender IO Farming station but I need the Tool ID's therefor.
I tryed Calculator:EndForgedHoe and so on.

Sincerely
TheChaosWitcher

**Comment by davqvist** [comment]
Just press F3+H and look in JEI. calculator:EndForgedHoe should work though, I did that as well.

**Comment by AEnterprise** [comment]
yes calculator:EndForgedHoe should work, notice calculator is with a small c, modid's have to be lowercase now
