### ISSUE TITLE
 Piping Server Crash

### ISSUE THREAD

**Issue by TheLimePixel** [SonarSonic/Calculator#232]
On the latest 1.11.2 version of the mod whenever you connect any type of piping system to the machines for exporting the world/server crashes. It happens with any kind of modded pipe so I'll only give a crash log if needed. It works fine when inputting.

**Comment by AEnterprise** [comment]
a crashlog is required to know what's going on, without it we don't know what's heapening

**Comment by TheLimePixel** [comment]
Ok here's an example with an ExtraUtils 2 Transfer Node:
https://pastebin.com/yy8rUUU8

If you need a crash log with a different piping system I'll have no problem sending it. Also sorry for being so late.

**Comment by AEnterprise** [comment]
no need for another crashlog, this one tells exactly what's going on: the way an empty itemstack (so no items in the slot) are represented changed from 1.10 to 1.11 and the old way is still used in that one place of the sonarcore inventory handler

should be a simple fix when @SonarSonic gets arround to it

**Comment by Mohron** [comment]
Looks like that paste disappeared/expired but it's still happening for sure.
https://hastebin.com/ijexelovob.php

**Comment by AEnterprise** [comment]
@Mohron that's another crash, that's an api issue

**Comment by TheLimePixel** [comment]
Will the 1.11.2 version ever update? You can't have a crash like this for such a long time.

**Comment by austragus** [comment]
Still happening on my 1.11.2 server.

**Comment by BigFriendlyJakey** [comment]
This is happening on my 1.11.2 Single Player world as well; not trying to be annoying, just updating this thread

**Comment by TheLimePixel** [comment]
It's on the 1.12 version as well. );
https://pastebin.com/wKG7uTTP

**Comment by SonarSonic** [comment]
@EmosewaGamer could you post a crash for 1.12?

**Comment by TheLimePixel** [comment]
... I already posted it.

**Comment by BigFriendlyJakey** [comment]
#283 has a 1.12.1 crash report relating to this issue

**Comment by SonarSonic** [comment]
Fixed in dev

**Comment by SonarSonic** [comment]
Only for 1.12.1 for now. 1.11 maybe later
