### ISSUE TITLE
Advanced Power Cube doesn't output power

### ISSUE THREAD

**Issue by davqvist** [SonarSonic/Calculator#235]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2254
 * Calculator Version: 3.2.1
 * SonarCore Version: 3.2.6
 * Multiplayer or Singleplayer: tested only in Singleplayer
 * Crash Report Link: -
 * Affected Features: Advanced Power Cube doesn't output power
 * Description: 

Another user reported this to me and I tested and can confirm. No matter what energy cable I use (IE Wire Connectors / EnderIO Conduits) or if I put a capacitor (EnderIO or IE) directly to it, energy isn't transferred. The Advanced Power Cube was completely full and I did shift right click to change the side to output (white).

**Comment by SonarSonic** [comment]
Fixed in dev
