### ISSUE TITLE
EnderIO Conduits do not insert into Storage Chambers if there are already circuits of a different subtype in the storage chamber.

### ISSUE THREAD

**Issue by KAfable** [SonarSonic/Calculator#236]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2254
 * Calculator Version: 3.2.1
 * SonarCore Version: 3.2.6
 * Multiplayer or Singleplayer: Multiplayer
 * Crash Report Link: N/A
 * Affected Features: EnderIO Conduits do not insert into Storage Chambers if there are already circuits of a different subtype in the storage chamber.
 * Description: Was attempting to automate circuits using ender IO item conduits by pulling out of the input (green side) of an Analysing Chamber and into a Storage Chamber. It transfers the circuit if the Storage Chamber was originally empty but refuses to insert additional circuits of a different subtype/color thereafter. I made sure that both of the circuits were Analysed and not 'Stable'. I added a vanilla chest to item conduit network and it was able to immediately transfer that circuit from the analyser to the chest without issues.

After emptying the Storage Chamber, the item conduit was able transfer the circuit into the chamber without any issues, but would freeze again when the analysing chamber would produce a circuit of a different subtype. This was the same issue with Stable Circuits.

Right now my current workaround is making 14 Storage Chambers, one for each circuit subtype.

edit: Realized what I typed was a little bit convoluted, but after some testing (hopper, ExU2 Transfer nodes), these forms of piping only seem to recognize the first slot of a storage chamber. it will input any circuits that match the subtype as well as normal type (stable, analysed, etc) of the circuit in the first slot. Even if I prime the rest of the storage chamber with all 14 types of circuits, they still wont get inserted into the storage chamber.

edit2: Tried using transfer upgrades within the mod itself in the Analysing Chamber, and get the same issue, it will not transfer circuits into the storage chamber if the first slot is filled with a different circuit.

**Comment by Dilnu** [comment]
I'm also seeing this issue.

**Comment by BattleNachos** [comment]
Straight Analyzing Chamber to Storage Chamber doesn't work either.  It doesn't appear to be possible to automate this process.

3.2.1 - Single Player - Age of Engineering modpack

**Comment by MalfooGames** [comment]
Did anyone find a solution to this problem please ?

**Comment by Dilnu** [comment]
My work around is to tweak the stack size of the circuits with minetweaker. That lets you store circuits efficiently in other inventories.
`<calculator:CircuitBoard:12>.maxStackSize = 32;`

**Comment by davqvist** [comment]
Oh nice, I may try that and add it in the next version of AOE. Didn't even think of that

**Comment by Zirica** [comment]
Also having the same issue

**Comment by ImTheStigHonest** [comment]
Same issue confirmed, only first slot will allow a circuit then the chamber will not allow any more circuits via autotransfer

**Comment by jmarler** [comment]
I've discovered that the storage chamber maxes out at 1024 for each unique circuit type. If you add the minetweaker like Dilnu posted above, you can bump that number up to 1024x whatever you set the maxStackSize to. I set the maxStackSize to 64 in my AOE world and was able to go beyond 1024 circuits in the storage chamber, and all of the circuits I had in storage drawers automagically stacked. Automation is easy with storage drawers once the circuits stack.

**Comment by SonarSonic** [comment]
Fixed in dev
