### ISSUE TITLE
Precision Chamber JEI recipe of Damaged Circuit 3 not showing

### ISSUE THREAD

**Issue by davqvist** [SonarSonic/Calculator#238]
Please fill out the details below before contributing

 * Forge Version: 2254
 * Calculator Version: 3.2.1
 * SonarCore Version: 3.2.6
 * Multiplayer or Singleplayer: Singleplayer, haven't tested Multiplayer
 * Crash Report Link: -
 * Affected Features: Precision Chamber JEI recipe of Damaged Circuit 3 not showing
 * Description: 

When looking up all 100% recipes of the Precision Chamber, the Damaged Circuit with the metadata 3 doesn't show the required input in JEI. I can't tell if it's only not showing in JEI or if the whole recipe doesn't work because I don't know what the intended item is.

**Comment by davqvist** [comment]
Update: I just remembered I could just look up the code, and found out that it needs Reinforced Stone. I can confirm that the recipe works, so it's only not showing in JEI.

**Comment by SonarSonic** [comment]
Fixed in dev
