### ISSUE TITLE
Extraction Chamber Crash

### ISSUE THREAD

**Issue by TheLimePixel** [SonarSonic/Calculator#239]
On the 1.11.2 version of Calculator whenever you get a Dirty or Damaged Circuit in the Extraction Chamber, the server crashes: https://pastebin.com/GRBEv4Kh

**Comment by Kaisoul** [comment]
i am also on 1.11.2
forge-1.11.2-13.20.0.2285
Calculator-1.11.2-4.0.0

went to use an extraction chamber with dirt got a dirty circuit then crash
[Crash Report](https://pastebin.com/70m7VUL2)

Kinda stuck on my Lan World at this time crash was bad enough i was forced to load a back up.

**Comment by EmosewaGamer** [comment]
Will the 1.11.2 version ever update? You can't have a crash like this for such a long time.

**Comment by kwpugh** [comment]
I am on 1.11.2, same crash.

Calculator-1.11.2-4.0.0.jar
forge-1.11.2-13.20.0.2345-universal.jar

report: https://gist.github.com/kwpugh/586a40d8262ca42c57833f15d280527d

Since it crashed on the dirty circuit, I used NBExplorer to remove the contents of the chamber and was able to recover.

**Comment by SonarSonic** [comment]
Fixed in dev
