### ISSUE TITLE
Conductor Mast Infinite Energy

### ISSUE THREAD

**Issue by zzApotheosis** [SonarSonic/Calculator#24]
When the Conductor Mast is NOT at maximum capacity (5 MRF), it will output the correct amount of power (10 kRF/t). However, I noticed that when the Conductor Mast is at maximum capacity, it will hold that maximum capacity indefinitely, therefore infinitely supplying 10 kRF/t.

**Comment by SonarSonic** [comment]
Yeah I'll fix that too :D

**Comment by SonarSonic** [comment]
Fixed in 1.8.2
