### ISSUE TITLE
Lightning Mast and Calculator Locator don't output power anymore

### ISSUE THREAD

**Issue by davqvist** [SonarSonic/Calculator#240]
Please fill out the details below before contributing

 * Forge Version: 2281
 * Calculator Version: 3.2.1
 * SonarCore Version: 3.2.6
 * Multiplayer or Singleplayer: Singleplayer
 * Crash Report Link: -
 * Affected Features: Lightning Mast and Calculator Locator don't output power anymore
 * Description: 

While succesfully fixing the Advanced Power Cube in the newest version, a new bug got introduced. I only tested the Lightning Mast and the Calculator Locator, but both don't output power anymore, at least to anything from other mods like Conduits or Batteries. The only thing those output to are the Power Cubes from Calculator themselves.

**Comment by popps73x** [comment]
I am having a similar issue with the lightning rod in 3.2.2 core version 3.2.7.  singleplayer world.  when i place a capacitor bank under the lightning rod it outputs power to the lightning rod and stores it there.  Wondering if the bottom of the lightning rod was inadvertently changed from an output to input face in some way?  does not output power to a advanced energy cube either.  thanks.  the mod is alot of fun.

**Comment by EpiclyDelicious** [comment]
@SonarSonic 

Yep... can confirm. This is definitely a bug. And it's been a bug that's been an issue in the past. This has been very frustrating for me and my friend who have been trying to troubleshoot why the hell it isn't working. We tried every living cable, energy container, you name it. I even tried outputting to Calculator's own Energy Cubes. Nothing!

- Forge Version: 2297
- Calculator Version: 3.2.2
- SonarCore Version: 3.2.7
- Multiplayer or Singleplayer: Singleplayer AND Multiplayer
- Crash Report Link: - None.
- Affected Features: Lightning Mast & Calculator Locator/Power Generation
- Description: Lightning Mast and Calculator Locator DO NOT output power to ANYTHING.

**Comment by SonarSonic** [comment]
Fixed in dev.
