### ISSUE TITLE
Another Dupe Bug with the Fabrication Chamber

### ISSUE THREAD

**Issue by davqvist** [SonarSonic/Calculator#243]
Please fill out the details below before contributing

 * Forge Version: 1.10.2
 * Calculator Version: 3.2.2
 * SonarCore Version: 3.2.7
 * Multiplayer or Singleplayer: Singleplayer
 * Crash Report Link: -
 * Affected Features: Another Dupe Bug with the Fabrication Chamber
 * Description: 

This is different than https://github.com/SonarSonic/Calculator/issues/237
and also way more worrying. If you shift click any item into the Fabrication Chamber it just dupes it. It is not limited to Calculator items, so any item works. In very rare cases it doesn't work (not sure what is different) but I could dupe like any Assembly, Power Cubes, Calculator Plugs. But I can also put any item from any other mod in and it dupes them, like Capacitors or even Creative Capacitors. This is really gamebreaking and I would appreciate it if you could have a look.

**Comment by SonarSonic** [comment]
Fixed in dev

**Comment by davqvist** [comment]
I appreciate it so much. Thanks for fixing.
