### ISSUE TITLE
Docking station eats buckets on fire coal recipe

### ISSUE THREAD

**Issue by Benedictum** [SonarSonic/Calculator#246]
Please fill out the details below before contributing

Forge Version: 12.18.3.2254
Calculator Version: 3.2.1
SonarCore Version: 3.2.6
Multiplayer or Singleplayer: both
 * Affected Features:  Docking Station, Scientific Calculator, Fire Coal
 * Description:  When you craft an enriched coal with a bucket of lava in the scientific calculator, it returns the empty bucket as well as the fire coal. When you pipe enriched coal and a lava bucket into a docking station with the scientific calculator mounted, it produces the fire coal but does not return an empty bucket, making automation difficult / impossible.

**Comment by SonarSonic** [comment]
Fixed in dev

**Comment by JaSpr** [comment]
Has this fix been released?

**Comment by SonarSonic** [comment]
@JaSpr Hasn't been released I don't think....so it'll be in the next version
