### ISSUE TITLE
Reinforced Chest does not drop contents when broken.

### ISSUE THREAD

**Issue by elgefe** [SonarSonic/Calculator#248]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2316
 * Calculator Version: 1.10.2-3.2.2
 * SonarCore Version: 1.10.2-3.2.7
 * Multiplayer or Singleplayer: Singleplayer
 * Crash Report Link: N/A
 * Affected Features: Reinforced Chest
 * Description: Reinforced Chest destroys all contents when broken. At first I assumed an interaction with another mod caused it, so I made a new instance with only Calculator and SonarCore and the behavior persists. Don't know if it's a bug or intended behavior but if it's intended, a tooltip indicating the behavior would be appreciated.

**Comment by SlyCedix** [comment]
Experienced on multiplayer as well, same versions.

**Comment by SonarSonic** [comment]
Fixed in dev
