### ISSUE TITLE
Nutrition Module Bug

### ISSUE THREAD

**Issue by zzApotheosis** [SonarSonic/Calculator#25]
Back again with another concern.

I know that the point of the nutrition module is to automatically maintain your health and hunger, but it seems that the hunger part of the Nutrition Module, when it is not 0, will effectively disable any hunger drops in my hunger bar. I think the module is constantly trying to refill my hunger to max hunger (which makes sense), but the game is also constantly resupplying my saturation level at no cost to the Nutrition Module, which means that I never get hungry, and the Nutrition Module never loses hunger points.

**Comment by SonarSonic** [comment]
Ah I see what you mean. I may change how quickly it refills then.

**Comment by SonarSonic** [comment]
Fixed in 1.8.2
