### ISSUE TITLE
Advanced Greenhouse eating seeds

### ISSUE THREAD

**Issue by togreglove** [SonarSonic/Calculator#250]
Please fill out the details below before contributing

Minecraft 1.10.2
 * Forge Version: 2316
 * Calculator Version: 3.2.2
 * SonarCore Version: 3.2.7
 * Multiplayer or Singleplayer: Multiplayer
 * Crash Report Link: No Crash
 * Affected Features: Advanced Greenhouse
 * Description: Mystical Agriculture seeds are being consumed by greenhouse.

Sometimes, when more than one seed is in the inventory of the greenhouse, it will delete all the seeds. As a test, I filled the available plots with wheat, then put 15 wheat and 15 inferium essence seeds in the greenhouse.  Within a minute, the number of wheat seeds had increased by a lot and the inferium seeds were all gone.  Pack includes Crop Dusting, Pam's Harvestcraft, Mystical Agriculture, Mystical Aggraditions, and Actually Addition worms. 
The seeds never build up in the machine, and I often come back and all of the seeds of a type are gone. If you need me to test scenarios, just let me know.

**Comment by togreglove** [comment]
Further Testing:
Put 15 seeds in each slot. All plots full. It seems to be harvesting a plant, putting that seed in the inventory, then taking one seed out of each stack inside the machine, but only planting one of them. Slowly all the stacks reduce in size. The first stack seems to take the longest to disappear.

**Comment by SonarSonic** [comment]
So is this issue only occurring with Mystical Agriculture seeds? @togreglove

**Comment by togreglove** [comment]
hard to tell, as the other plants (vanilla and pams) produce so many seeds that I can't tell if its eating them or not. The numbers go up, but if it's eating one of each type per cycle, and harvest 2-3 from each plant, that would happen either way.

**Comment by togreglove** [comment]
tested again with 6 varieties of pams and wheat. 2 types of pams got extra seeds, it ate all extra seeds

**Comment by togreglove** [comment]
I attribute this to the first 2 crops "overtaking" the others and crowding them out. A couple of the other seeds are gone completely now
so, yes, any seeds

**Comment by togreglove** [comment]
If you need to come see, I can give you a link to the multimc instance and you can join my server where I can op you to test.

**Comment by togreglove** [comment]
Just tested with flawless greenhouse and it's the same behavior.

**Comment by togreglove** [comment]
Just ran a test instance on Twitch with just Calculator and Mystical Agriculture enabled and it ate the seeds.  Also, it seems the recipe for the Speed Upgrade is messed up too. Odd.

**Comment by JaSpr** [comment]
Confirmed.  I've watched as the advanced greenhouse tries to plant 1 prunae seed, it pulls 1 seed from EACH STACK, instead of just the first available stack.  I also watched it pull 45 seeds from each stack all at once (when planting 45)
