### ISSUE TITLE
conductor mast

### ISSUE THREAD

**Issue by piterrcousin** [SonarSonic/Calculator#251]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2281
 * Calculator Version: 3.2.1
 * SonarCore Version: 3.2.7
 * Multiplayer or Singleplayer: Singleplayer
 * Crash Report Link: .
 * Affected Features: .
 * Description: I can't transfer enerfy from the conductor mast to any type of conduits or energy cubes and I don't know why, i saw a few videos and I do de same, but it doesn't works

**Comment by SonarSonic** [comment]
Update to the latest version, this issue no longer occurs. For reference, the energy conduit, cube always needs to be underneath the Conductor Mast
