### ISSUE TITLE
Dupe bug with automated extraction from chambers

### ISSUE THREAD

**Issue by cpw** [SonarSonic/Calculator#254]
Please fill out the details below before contributing

Playing Age of Engineering pack.

 * Forge Version: 1.10.2.2316
 * Calculator Version: 3.2.1
 * SonarCore Version: 3.2.6
 * Multiplayer or Singleplayer: single
 * Crash Report Link: none
 * Affected Features: automaticing circuit production
 * Description: 
Getting a dupe bug when extracting circuits from the reassembly chamber. Using conduits to do so. Looks like it's not removing the item from the virtual inventory?

Screenshot on my twitter: https://twitter.com/voxcpw/status/888883420205649922

**Comment by cpw** [comment]
Confirming it happens with latest Sonar Core (3.2.8) and Calculator (3.2.2) mods.

**Comment by cpw** [comment]
Update: EU2 item nodes don't cause it. Must be an interaction between EIO conduits and the circuit machines?

**Comment by 5aaee9** [comment]
The Extraction Chamber, Processing Chamber and Analysing Chamber has same problem when I use EIO item conduits

**Comment by Zirica** [comment]
Seeing the same issue
[EnderIO]: NetworkedInventory.itemExtracted: Inserted 1 Circuit but only removed null from sonar.core.inventory.AbstractSonarInventory$EmbeddedHandler@3ed9dca3 at BlockPos{x=-9, y=41, z=-258}

Repeating very fast with no end

**Comment by SonarSonic** [comment]
I can't recreate this. Either Ender IO has fixed this, or I did and I've forgotten. So please try again with the latest versions once I've uploaded it.

**Comment by davqvist** [comment]
Okay, I got just reported this bug again.
I couldn't replicate myself at first like when cpw reported it, but I took another look and now after a while I figured it out.

Basically any machine that I tested so far, has this bug.

To replicate, 2 examples: 

1.) Use a Reinforced Furnace, wrench two sides to output, attach 4 sides of the Furncace with EnderIO Conduit and connect the Conduits together. Configure the Conduits on the 2 Output sides to extract and always active and the input sides to input. Place an inventory like a chest or a drawer to the circuit circle and configure the Conduit to insert. Insert max speed upgrades (not sure if required). Then hook up the Furnace to power on one of the 2 remaining sides and put potatoes in. I got around double of cooked potatoes, Others have reported to set 3 sides on insert and one on output, but that didn't work for me.

2.) Use a Docking Station with an Atomic Calculator in it and hook it up to power from the bottom. Maker a horizontal circle of conduits around the Docking Station and configure 3 sides to insert and one to extract (always active). Connect the Conduit Circle to the top of the Docking Station and configure it to extract (always active). Above this conduit, place an inventory like a chest or drawer. Place anything, like a Nether Star in an inventory slot of the Atomic Calculator in the Docking Station. They get duped in the chest.

This is a serious issue, please investigate that.
