### ISSUE TITLE
Server performance

### ISSUE THREAD

**Issue by Symphonizd** [SonarSonic/Calculator#255]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2316
 * Calculator Version: 3.2.1
 * SonarCore Version: 3.2.6
 * Multiplayer or Singleplayer: Multiplayer
 * Crash Report Link: N/A
 * Affected Features: Server performance when more than one block of the same type is placed
 * Description: When there is more than one block of the same type placed in the world the server becomes extremely laggy almost to the point that it's unplayable. Every time someone logs in we get this message:

>Tile sonar.calculator.mod.common.tileentity.machines.TileEntityAdvancedPowerCube@397acb9a (dim 0: -2815/91/-654), sub tile -2815/91/-654 (sonar.calculator.mod.common.tileentity.machines.TileEntityAdvancedPowerCube@397acb9a) addition is conflicting with a previous registration at the same location

When the blocks are removed the server is stable.

**Comment by everseeking** [comment]
Don't know how much of a performance impact this is having on my server, but I'm seeing the same message.

While it's the power cube, [IC2 energy net appears to be throwing it](https://i.imgur.com/UQ46iDP.png).

**Comment by AndrewGraber** [comment]
This is not an issue with the placement of blocks, but rather that tile entities sometimes are not deleted when the blocks are broken, so if you place a new tile entity there, your server doesn't like the fact that there are two TEs there. This same issue is mentioned in issue #256

**Comment by SonarSonic** [comment]
Fixed in dev
