### ISSUE TITLE
[1.11.2 - v4.0.0] Crash from seeds in Advanced greenhouse

### ISSUE THREAD

**Issue by VallenFrostweaver** [SonarSonic/Calculator#257]
* Forge Version: 13.20.1.2429
 * Calculator Version: 4.0.0
 * SonarCore Version: 4.0.0
 * Multiplayer or Singleplayer: Single
 * Crash Report Link: https://pastebin.com/yVCa1nA0
 * Affected Features: Advanced Greenhouse
 * Description: I placed an advanced greenhouse in survival but was in gamemode 1 and had no power in the greenhouse though it still built, added all acacia woods and light grey glass. Built the greenhouse by pressing Build. Once it was done I placed oak chest in front of Adv. Greenhouse block and placed a melon seed in it. Crash. Tried to enter again and game is now frozen.
EDIT: I cannot reproduce the building without power part. I previously had a basic greenhouse that I had demolished with the button on the same spot. I _can_ reproduce crashing with seeds in a chest though.

**Comment by SonarSonic** [comment]
Fixed in dev
