### ISSUE TITLE
Question about upgrade (Possibly a bug)

### ISSUE THREAD

**Issue by noobyaran9** [SonarSonic/Calculator#258]
* Forge Version: 12.18.3.2316
 * Calculator Version: 3.2.1
 * SonarCore Version: 3.2.6
 * Multiplayer or Singleplayer: Multiplayer
 * Crash Report Link: -
 * Affected Features: Speed & Energy Upgrade
 * Description: What is the formula used to calculate the amount of power usage and speed of the machine for each upgrades? And the machine stats doesn't show the actual usage and amount of ticks to craft at times. 

Speed = 0, Energy = 0
![2017-08-08_13 54 52](https://user-images.githubusercontent.com/13598309/29058243-e44de672-7c41-11e7-965a-28999e9a24e6.png)

Speed = 1, Energy = 1, Increament = 1.06x,
![2017-08-08_13 55 02](https://user-images.githubusercontent.com/13598309/29058244-e4523a7e-7c41-11e7-8370-718de2dbd053.png)

Speed = 2, Energy = 2, Increament = 1.075x,
![2017-08-08_13 55 10](https://user-images.githubusercontent.com/13598309/29058246-e45596d8-7c41-11e7-8f00-2f0cd52a14ad.png)

Speed = 3, Energy = 3, Increament = 1.07x,
![2017-08-08_13 55 19](https://user-images.githubusercontent.com/13598309/29058247-e455937c-7c41-11e7-9e70-4ad0717a4cf2.png)

Speed = 4, Energy = 4, Increament = 1.065x,
![2017-08-08_13 55 28](https://user-images.githubusercontent.com/13598309/29058248-e456073a-7c41-11e7-8919-7c9e291182a3.png)

Speed = 5, Energy = 5, Increament = 1.092x,
![2017-08-08_13 55 36](https://user-images.githubusercontent.com/13598309/29058249-e45781aa-7c41-11e7-99f9-7202c40b4c41.png)

Speed = 6, Energy = 6, Increament = 1.085x,
![2017-08-08_13 55 46](https://user-images.githubusercontent.com/13598309/29058250-e4582880-7c41-11e7-8855-2c99f56c9598.png)

Speed = 7, Energy = 7, Increament = 1.104x,
![2017-08-08_13 56 15](https://user-images.githubusercontent.com/13598309/29058245-e455318e-7c41-11e7-98b9-7449a2993e79.png)

Speed = 8, Energy = 8, Increament = 1.117x,
![2017-08-08_13 57 03](https://user-images.githubusercontent.com/13598309/29058251-e480cef2-7c41-11e7-84f3-29cd5712e8c8.png)

Speed = 9, Energy = 9, Increament = 1.116x,
![2017-08-08_13 57 12](https://user-images.githubusercontent.com/13598309/29058255-e4975f50-7c41-11e7-87ac-becf4ac7d5bc.png)

Speed = 10, Energy = 10, Increament = 1.151x,
![2017-08-08_13 57 19](https://user-images.githubusercontent.com/13598309/29058252-e4832c38-7c41-11e7-82bf-6f859ec2f11d.png)

Speed = 11, Energy = 11, Increament = 1.164x,
![2017-08-08_13 57 27](https://user-images.githubusercontent.com/13598309/29058253-e484f28e-7c41-11e7-8e9d-83a785bd07e9.png)

Speed = 12, Energy = 12, Increament = 1.197x,
![2017-08-08_13 57 34](https://user-images.githubusercontent.com/13598309/29058254-e487d026-7c41-11e7-8741-1cdbae1f102f.png)

Speed = 13, Energy = 13, Increament = 1.253x,
![2017-08-08_13 57 41](https://user-images.githubusercontent.com/13598309/29058256-e49d70fc-7c41-11e7-9385-9c7e11b33d6f.png)

Speed = 14, Energy = 14, Increament = 1.333x,
![2017-08-08_13 57 50](https://user-images.githubusercontent.com/13598309/29058258-e4bd4634-7c41-11e7-9611-c24892f0bd58.png)

Speed = 15, Energy = 15, Increament = 1.507x,
![2017-08-08_13 57 58](https://user-images.githubusercontent.com/13598309/29058259-e4c45c12-7c41-11e7-986e-9613ac18055b.png)

Speed = 16, Energy = 16, Increament = 12.850x,
![2017-08-08_13 58 16](https://user-images.githubusercontent.com/13598309/29058257-e4af2f36-7c41-11e7-8322-702fc60f1444.png)

I'm not sure if the increament from 15 to 16 speed and energy upgrade is intended.

**Comment by SonarSonic** [comment]
Thanks for bringing my attention to this. it appears the machines are not using the expected amount of energy. They will be in the next update.
