### ISSUE TITLE
Dupe bug with fabrication chamber

### ISSUE THREAD

**Issue by ninja0773** [SonarSonic/Calculator#261]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2422
 * Calculator Version: 1.10.2-3.2.1
 * SonarCore Version: 1.10.2-3.2.6
 * Multiplayer or Singleplayer: Both
 * Crash Report Link: N/A
 * Affected Features: N/A
 * Description: 
When bringing up the fabrication chamber interface, shift clicking stackable items will double them. Tested on both singleplayer and multiplayer.

**Comment by SonarSonic** [comment]
Update SonarCore and Calculator. This bug doesn't occur in the latest versions.
