### ISSUE TITLE
Found a typo on the wiki

### ISSUE THREAD

**Issue by ThatOneTraitor** [SonarSonic/Calculator#265]
Please fill out the details below before contributing

 * Forge Version: N/A
 * Calculator Version: N/A
 * SonarCore Version: N/A
 * Multiplayer or Singleplayer: N/A
 * Crash Report Link: N/A
 * Affected Features: The Wiki
 * Description: 

https://github.com/SonarSonic/Calculator/wiki/Circuits

"Increases the energy consumption of certain machines Installed with Right Click. Removed by removing the machine block."

Shouldn't It be Decrease?

**Comment by SonarSonic** [comment]
Thanks! Fixed it.
