### ISSUE TITLE
Analysing Chamber Bug

### ISSUE THREAD

**Issue by zzApotheosis** [SonarSonic/Calculator#27]
The Analysing Chamber does not accept any RF. Ender IO conduits and directly placing an energy module/flawless calculator in the input slot doesn't transfer RF.

**Comment by SonarSonic** [comment]
Analysing Chambers don't require power to operate. Instead they output power! From the circuits they analyse, circuits could store anything from 0 ->100000 RF !!

**Comment by SonarSonic** [comment]
https://github.com/SonarSonic/Calculator/wiki/Analysing-Chamber
