### ISSUE TITLE
Advanced Greenhouse NullPointerException

### ISSUE THREAD

**Issue by CrazyCodeUK** [SonarSonic/Calculator#279]
Forge 1.10.2-12.18.3.2422
Calculator-1.10.2-3.2.3
SonarCore-1.10.2-3.2.9
Both SP and MP
Crash Log: https://pastebin.com/H80qyFnx

On completion of the Advanced Greenhouse the server crashes with a Ticking block entity caused by NullPointerException at sonar.core.integration.planting.vanilla.Planter.canTierPlant(Planter.java:27). The server then will crash on every attempted start of the server after until the block is removed from the world.

**Comment by CrazyCodeUK** [comment]
This may have been fixed in #43304421d7e9c71a56614266dfbd94847c73f7ba looking at the code. Unable to test/verify though.

**Comment by davqvist** [comment]
I just updated Age of Engineering to the new Calculator version and someone reported this. Will this get fixed soon or should I downgrade the Calculator version again?

**Comment by AEnterprise** [comment]
there is already a PR to fix this, it all depends when @SonarSonic has time and can do a new release

**Comment by davqvist** [comment]
Cool, thanks for the answer.

**Comment by hottentottententententoonstelling** [comment]
@davqvist, you can downgrade to the previous version of the calculator mod without any trouble, but you should upgrade when a fix is released to profit from the fixes included in the latest version (not sure if the library mod should be downgraded, but I think that you should downgrade that one too).

Always make a backup when downgrading something in modded

**Comment by AEnterprise** [comment]
@hottentottententententoonstelling he's talking about downgrading the mod in the pack in general for everyone

**Comment by hottentottententententoonstelling** [comment]
SonarSonic has released a new version on curseforge which fixes this

**Comment by SonarSonic** [comment]
Fixed in 1.2.5
