### ISSUE TITLE
Outputting Items From Anything Crashes

### ISSUE THREAD

**Issue by BigFriendlyJakey** [SonarSonic/Calculator#283]
Please fill out the details below before contributing

 * Forge Version: 1.12.1-forge1.12.1-14.22.1.2485
 * Calculator Version: calculator-1.12.1-5.0.0
 * SonarCore Version: sonarcore-1.12.1-5.0.0
 * Multiplayer or Singleplayer: Single
 * Crash Report Link: https://pastebin.com/RSDgVqGH
 * Affected Features: Transferring Items from machines i.e. outputting
 * Description: It doesn't matter how the items are being output or what they're being output from, but it's only with machines from Calculator, and I have to go into MCEdit and delete whatever block is outputting the items. 
A classic way I keep getting this crash is trying to automate circuits; whether it be the processing chamber, the analysing chamber, or any part of the system, if a transfer upgrade and a method of outputting the items (another Calculator machine that can use the output items, storage, e.t.c.) the game freezes for about a second & crashes. 

Here's my mod list:
> appliedenergistics2-rv5-alpha-4
> AutoRegLib-1.3-13
> Baubles-1.12-1.5.1
> bdlib-1.14.2.8-mc1.12.1
> Botania r1.10-347
> calculator-1.12.1-5.0.0
> CodeChickenLib-1.12-3.1.2.297-universal
> CoFHCore-1.12-4.3.5.13-universal
> CoFHWorld-1.12-1.0.1.8-universal
> cucumber[1.12]-1.0.2
> environmentaltech-1.12.1-2.0.2d
> extrautils2-1.12-1.6.3
> FastLeafDecay-v14
> generators-0.9.20.7-mc1.12.1
> ImmersiveEngineering-0.12-72
> ImmersiveEngineering-0.12-72-core
> InventoryTweaks-1.63+beta.108
> jei_1.12.1-4.7.8.95
> journeymap-1.12.1-5.5.0b4
> Mantle-1.12-1.3.1.21
> mcjtylib-1.12-2.4.4
> Mekanism-1.12.1-9.4.1.326
> MekanismGenerators-1.12.1-9.4.1.326
> mysticalagriculture[1.12]-1.6.3
> Psi-r1.1-53
> RedstoneFlux-1.12-2.0.1.2-universal
> Reliquary-1.12-1.3.4.710
> rftools-1.12-6.13
> rftoolsdim-1.12-5.05
> sonarcore-1.12.1-5.0.0
> TConstruct-1.12-2.7.3.30
> ThermalDynamics-1.12-2.3.5.12-universal
> ThermalExpansion-1.12-5.3.5.19-universal
> ThermalFoundation-1.12-2.3.5.14-universal
> TinkerToolLeveling-1.12-1.0.2b
> valkyrielib-1.12.1-2.0.2c

This same issue was also in 1.11.2, which I created a thread about: #273 Had basically the same mod list there too.

**Comment by AEnterprise** [comment]
looks like the base inventory is still using null instead of empty item stacks

**Comment by SonarSonic** [comment]
Fixed in dev
