### ISSUE TITLE
Storage chamber making AE system really slow

### ISSUE THREAD

**Issue by Nidaelie** [SonarSonic/Calculator#284]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2477
 * Calculator Version: 3.2.5
 * SonarCore Version: 3.2.9
 * Multiplayer or Singleplayer: both
 * Crash Report Link: no crash
 * Affected Features: storage chamber from calculator
 * Description:  conecting a storage chamber with a storage bus to a ae system makes it really slow to just craft a single recipe, removing it fix the speed issue

**Comment by xepps** [comment]
I noticed this too. Playing on latest Age of Engineering release.

**Comment by SonarSonic** [comment]
Fixed in dev
