### ISSUE TITLE
Automatically inserting into Storage Chambers creates huge tps lag

### ISSUE THREAD

**Issue by landrus** [SonarSonic/Calculator#288]
Age of Engineering 1.1.1c

 * Forge Version: 1.10.2-12.18.3.2477
 * Calculator Version: 3.2.5
 * SonarCore Version: 3.2.9
 * Multiplayer or Singleplayer: single
 * Crash Report Link: 
 * Affected Features: 
 * Description: Filling a storage chamber with enderio item conduits (I guess any kind of automatic insert method) creates huge tps lag. I profiles with TickProfiler and found the following calls:

https://pastebin.com/HBGunJNi

I guess this is the same issue as this:

https://github.com/SonarSonic/Calculator/issues/284

**Comment by LemADEC** [comment]
You can use filtered transfer nodes to work around that

**Comment by JolyGoodDay** [comment]
Big issue, drops server tps to 2-3 from 20, replicated multiple times by new users unaware.

**Comment by Cavesnakes** [comment]
It is critical problem in AoE modpack server 
I hope this problem is solved as soon as possible

**Comment by Nagapito** [comment]
@LemADEC filtered transfer nodes are a work around until you actually filter them! set the filter to one item or one stack and lag returns

**Comment by LemADEC** [comment]
Filtered exactly means that: it's filtered...

**Comment by SonarSonic** [comment]
Fixed in dev
