### ISSUE TITLE
Conductor Mast power output issue

### ISSUE THREAD

**Issue by LeChuckXIV** [SonarSonic/Calculator#289]
Please fill out the details below before contributing

 * Forge Version: 14.23.0.2501
 * Calculator Version: 1.12.2-5.0.1
 * SonarCore Version: 1.12.2-5.0.1
 * Multiplayer or Singleplayer: MP
 * Crash Report Link: N/A
 * Affected Features: Conductor mast
 * Description: i have a fairly large setup for my conductor mast that produces ~100k rf/t, i'm trying to output it to a cryo stabilised fluxduct from thermal dynamics, my issue is that because the duct has no power buffer the mast isn't outputting power into it at the max rate

TD Issue: https://github.com/CoFH/Feedback/issues/568

Setup Images: 
https://i.imgur.com/magGozq.png
https://i.imgur.com/hls2zbx.png

**Comment by SonarSonic** [comment]
The Conductor Mast did have an internal limit from when it produced less energy, definitely didn't account for the addition of weather stations / transmitters. I've removed the limit now.
