### ISSUE TITLE
Storage Chamber item storage method implementation issues

### ISSUE THREAD

**Issue by LeChuckXIV** [SonarSonic/Calculator#291]
Please fill out the details below before contributing

Forge Version: 14.23.0.2501
Calculator Version: 1.12.2-5.0.1
SonarCore Version: 1.12.2-5.0.1
Multiplayer or Singleplayer: MP
Crash Report Link: N/A
Affected Features: Storage Chamber

Description: Storage Chamber creates a new stack for each extra stack that is inside of it, this can cause extensive lag when combined with other mods that read from the chamber such as pipes and refined storage external storage.
Was causing considerable tps lag on a server with only a few thousand chipsets, this is the same issue with collosal chests and formerly YABBA, if you check the source for YABBA or industrial foregoing you would find a fix for this issue

**Comment by SonarSonic** [comment]
Fixed in dev
