### ISSUE TITLE
Dynamic Calculator should be automatable

### ISSUE THREAD

**Issue by taleteller** [SonarSonic/Calculator#296]
I think the dynamic Calculator as block version of the flawless calculator is missing is purpose. Unlike other blocks it can not be automated. It should be able to accept items and extract items from nearby hoppers and pipes. Also there should be a gui option to select the desired calculation operation to lock unwanted slots for automation.

**Comment by Skillotic0703** [comment]
That's too complicated and useless because you can already automate all the other calculators with docking stations.

**Comment by SonarSonic** [comment]
The Docking Station can already be automated.
