### ISSUE TITLE
[Suggestion]Alter the Analyzing Chamber for convenience

### ISSUE THREAD

**Issue by AncientShotgun** [SonarSonic/Calculator#298]
Perhaps it would be a good idea to add a dedicated circuit output slot to the Analyzing Chamber, to which the analyzed circuit is moved after it is analyzed. This would make it easier to automate, which is the entire point of some modpacks.

Is the lack of a dedicated circuit output slot incidental, or is it purposely to inhibit automation?
I can understand both, but many people probably won't be able to understand the latter.

**Comment by SonarSonic** [comment]
You can still automate with it in that slot as the circuit cannot be extracted until the circuit has been analysed. If you try and extract from a Green side you will retrieve the circuit.

**Comment by AncientShotgun** [comment]
Ah, I see. Thank you for the answer!
