### ISSUE TITLE
[BUG] Removing stuff with CraftTweaker

### ISSUE THREAD

**Issue by Leftorius** [SonarSonic/Calculator#302]
Please fill out the details below before contributing

 * Forge Version: 14.23.0.2517
 * Calculator Version: calculator-1.12.2-5.0.1
 * SonarCore Version: sonarcore-1.12.2-5.0.2
 * Multiplayer or Singleplayer: both
 * Crash Report Link: -
 * Affected Features: CraftTweaker (CraftTweaker2-1.12-4.0.9)
 * Description: I'm using this to remove stuff from stone separator:
mods.calculator.stoneSeparator.removeRecipe(<minecraft:iron_ore>);
mods.calculator.stoneSeparator.removeRecipe(<minecraft:gold_ore>);

but this doesnt seem to work and gives me this error:
[INITIALIZATION][CLIENT][ERROR] A StoneSeparator recipe was the wrong size
[INITIALIZATION][CLIENT][INFO] ERROR: RECIPE IS NULL
[INITIALIZATION][CLIENT][ERROR] StoneSeparator: Removing Recipe - Couldn't find matching recipe null
[INITIALIZATION][CLIENT][ERROR] A StoneSeparator recipe was the wrong size
[INITIALIZATION][CLIENT][INFO] ERROR: RECIPE IS NULL
[INITIALIZATION][CLIENT][ERROR] StoneSeparator: Removing Recipe - Couldn't find matching recipe null

but documentary says IIngrediant (https://gist.github.com/AEnterprise/b209f9bd2432286eaf79), not output. My guess is, those two are the only ones who are using oredict. But if I try to use <ore:oreGold>, this error occurs (same as above):
[INITIALIZATION][CLIENT][ERROR] A StoneSeparator recipe was the wrong size
[INITIALIZATION][CLIENT][INFO] ERROR: RECIPE IS NULL
[INITIALIZATION][CLIENT][ERROR] StoneSeparator: Removing Recipe - Couldn't find matching recipe null
[INITIALIZATION][CLIENT][ERROR] A StoneSeparator recipe was the wrong size
[INITIALIZATION][CLIENT][INFO] ERROR: RECIPE IS NULL
[INITIALIZATION][CLIENT][ERROR] StoneSeparator: Removing Recipe - Couldn't find matching recipe null

**Comment by SonarSonic** [comment]
Fixed in dev
