### ISSUE TITLE
[Suggestion] Better NBT on circuits

### ISSUE THREAD

**Issue by DerTollUdo** [SonarSonic/Calculator#303]
Please fill out the details below before contributing

 * Forge Version: 2477
 * Calculator Version: 1.10.2-3.2.5
 * SonarCore Version: 1.10.2-3.2.9
 * Multiplayer or Singleplayer:  Both
 * Crash Report Link: -
 * Affected Features: -
 * Description: 
While playing age of engineering, it has come to my knowledge that the circuits don't have different names. While that could be offset by at least having different NBT numbers, the same type of circuit in stable vs. analyzed have the same NBT numbers. This makes it frustrating at times to make sure you are doing the correct recipe as you can't check names or NBT always to verify.

So I was wondering if you could either name the circuits differently, even just 1, 2, 3, etc, or make sure that they all have different NBT numbers.

**Comment by AEnterprise** [comment]
all the circuits do have different textures so you can diferenciate them that way

**Comment by DerTollUdo** [comment]
Different textures only is not a good way for people to figure things out. It doesn't make sense to have to constantly compare an image when a simple word or number would make the mod much more accessible. And how do you tell someone which circuit you need? "I need the green squiggly one" isn't exactly conducive to team work.

**Comment by AEnterprise** [comment]
well better NBT isn't a good solution eighter as you can't easely check the NBT of things

a unique name to all of them might help but we need a lot of different names (or number them but that's also pretty boring)

**Comment by DerTollUdo** [comment]
Most can easily check NBT if they have JEI. But, you shouldn't have a forced dependency on another mod I agree. Numbers would solve it very easily. And I know a lot of people would be happier with different numbers than no change.

**Comment by andrelinslima** [comment]
While playing AoE, what I did was to enable advanced tooltips. it will display the item ID and also an identifier for each of the variations, like the 2nd green circuits is #5783/7.

press F3+H to enable advanced tooltips

**Comment by DerTollUdo** [comment]
The issue with that approach is both the stable and analyzed have the same metadata tag. So in your example the shiny and regular 2nd green circuit are both #5783/7. And also, the point is in exactly how you had to describe that. Which 2nd green one? There is no simple way for anyone to say a specific circuit. If they just put that metadata tag (0-13) after the circuit name, you could easily say I need circuit 7 shiny, or 7b, or some other way to distinguish what you are talking about. 

As it is, why keep the current confusing situation, when 14 numbers and a letter distinction between stable and analyzed makes everything more understandable?
