### ISSUE TITLE
[1.12] Item names don't appear in calculators

### ISSUE THREAD

**Issue by Skillotic0703** [SonarSonic/Calculator#304]
* Forge Version: 1.12.2 - 14.23.0.2529
 * Calculator Version: Calculator-1.12.X-5.0.1
 * SonarCore Version: Sonar-Core-1.12.X-5.0.2
 * Multiplayer or Singleplayer: Singleplayer
 * Affected Features: GUIs
 * Description: When hovering over an item with your mouse while in a calculator GUI will not display the item name and the background isn't darkened like it normally should.

**Comment by SonarSonic** [comment]
Fixed in dev
