### ISSUE TITLE
[BUG] Storage chamber shenanigans + looses inventory when using ender IO wrench

### ISSUE THREAD

**Issue by lucasSTU** [SonarSonic/Calculator#305]
Please fill out the details below before contributing

 * Forge Version: forge-12.18.3.2477
Age of Engineering
 * Calculator Version: 1.10.2-3.2.5
 * SonarCore Version: 1.10.2-3.2.9
 * Multiplayer or Singleplayer: Multiplayer
 * Affected Features:  storage chamber

 * Description: 
I was trying to make the storage chamber works with ender IO conduits (which ultimately did not workout because storage chamber works in a really weird way) and i noticed one bug and one weird behaviour:
- almost all calculators blocks have green or red on their faces to indidcate output or input. Storage chamber has that, but it cannot be changed. When you click with the wrench you open the block UI but the color of the face does not change. Is it a Bug or we cannot output from the strogare chamber ? It would be a shame for a storage block. I had to stop using storage chamber because i could not integrate it to any automated circuit.

- **Now the main problem**: When playing with conduits and storage chamber, i accidentally clicked on my storage chamber with my enderIO wrench; which made it change orientation (normal) but surprise, when i opened back the storage, it was empty. 
I tried several times and every time the inventory would disapear. I tried with the calculator wrench and it remove the block, but upon placing it back the inventory would still be there.

**Comment by KaesBuerschtl** [comment]
This issue also occurs when using the Immersive Engineering Hammer on the storage chamber.

**Comment by JaSpr** [comment]
I've seen the same thing on many mods.  It seems like a common problem, so probably an easy one to resolve.  [Example](https://github.com/lumien231/Random-Things/issues/253)

**Comment by SonarSonic** [comment]
Fixed in dev - for 1.12.2, 1.10.2 Fix may come later.
