### ISSUE TITLE
Scientific Calculator in Docking Station not returning buckets from Fire Coal recipe

### ISSUE THREAD

**Issue by welch3694** [SonarSonic/Calculator#308]
* Forge Version: 14.23.0.2532
 * Calculator Version: 1.12.2-5.0.1
 * SonarCore Version: 1.12.2-5.0.2
 * Multiplayer or Singleplayer: Multiplayer
 * Crash Report Link: Not a crash
 * Affected Features: Docking Station & Scientific Calculator
 * Description: The recipe for Fire Coal does not return the bucket when it is automated using the Docking Station & Scientific Calculator. When manually using the Scientific Calculator or Dynamic Calculator, it does return the bucket.

**Comment by SonarSonic** [comment]
Fixed in dev - bucket will now be dropped.
