### ISSUE TITLE
[1.12.2] Cannot Remove StoneSeparator and ExtractionChamber recipes

### ISSUE THREAD

**Issue by TheLimePixel** [SonarSonic/Calculator#312]
Please fill out the details below before contributing

 * Forge Version: 14.23.0.2554
 * Calculator Version: 1.12.X-5.0.1
 * SonarCore Version: 1.12.X-5.0.2
 * Multiplayer or Singleplayer: SP
 * Description: 
 Stone Separator and Extraction Chamber recipes cannot be removed via CraftTweaker as they require only one IIngredient, but it they have 2 outputs.

**Comment by SonarSonic** [comment]
Fixed in dev
