### ISSUE TITLE
Rotating algorithm separator with wrench loses items/upgrades

### ISSUE THREAD

**Issue by sei-mwd** [SonarSonic/Calculator#318]
Please fill out the details below before contributing

 * Forge Version: 12.18.3.2511
 * Calculator Version: 1.10.2-3.2.5
 * SonarCore Version: 1.10.2-3.2.9
 * Multiplayer or Singleplayer: single
 * Description: Rotating an algorithm separator with an yeta wrench (which I did by accident) causes the separator to void all contained items and upgrades.

**Comment by SonarSonic** [comment]
Fixed in dev
