### ISSUE TITLE
[1.12.2] Placable Calculator Dupe Bug

### ISSUE THREAD

**Issue by TheLimePixel** [SonarSonic/Calculator#319]
Please fill out the details below before contributing

 * Forge Version: 14.23.1.2562
 * Calculator Version: 5.0.1
 * SonarCore Version: 5.0.2
 * Multiplayer or Singleplayer: both 
 * Affected Features: breaking Atomic and Dynamic Calculators
 * Description: 
 If you place items in an Atomic or Dynamic Calculator, leave the items in them without taking the output and break them, you will get those items and the output. For example: If you put 2 Blaze Rods and a Flawless Diamond in an Atomic Calculator or the 3rd row of a Dynamic Calculator and you break it, you'll get 2 Blaze Rods, a Flawless Diamond and a Fire Diamond.

**Comment by SonarSonic** [comment]
Fixed in dev
