### ISSUE TITLE
Fabrication chamber

### ISSUE THREAD

**Issue by ShadwDrgn** [SonarSonic/Calculator#321]
Please fill out the details below before contributing

 * Forge Version: 14.23.1.2554
 * Calculator Version: 5.0.2
 * SonarCore Version: 5.0.2
 * Multiplayer or Singleplayer: Multiplayer
 * Crash Report Link: https://pastebin.com/f6LPQFdB
 * Affected Features: Fabrication Chamber/Processing Chamber/Precision chamber
 * Description: I placed a fabrication chamber above a storage chamber with some circuits in it (1-5 of each). I was unable to click any recipes on the left at all, and i noticed a ton of stacktraces in my server log. After that I was no longer able to even open the gui for the processing or precision chambers. Clicking something in the fabrication chamber is what's causing the stacktraces.

**Comment by Messiah7** [comment]
This problem fixed in Sonar Core ver. 5.0.3. Upgrade them
