### ISSUE TITLE
[Suggestion] Change Weather Controller to add time rather than set time.

### ISSUE THREAD

**Issue by JonathanPCode** [SonarSonic/Calculator#322]
Please fill out the details below before contributing

 * Forge Version: 14.23.1.2566
 * Calculator Version: 1.12.2-5.0.2
 * SonarCore Version: 1.12.2-5.0.3
 * Multiplayer or Singleplayer: MP/SP
 * Crash Report Link: No crash.
 * Affected Features: Weather Controller
 * Description: The weather controller, when changing between day and night, sets the time. This isn't a problem for changing between day and night, but it does reset the day to 0, which is a problem for mods that rely on such things as the moon phase. As someone that uses Astral Sorcery frequently and can never reach a solar eclipse that happens every 36 days, Adding enough time to make it the next morning or night would be a much better fix.

**Comment by 7OOTnegaTerces** [comment]
I Second This Request!!!

**Comment by SonarSonic** [comment]
Fixed in dev
