### ISSUE TITLE
Conductor mast not working

### ISSUE THREAD

**Issue by aerde** [SonarSonic/Calculator#323]
Please fill out the details below before contributing

 * Forge Version: .2562
 * Calculator Version: 1.12.2 - 5.02
 * SonarCore Version: 5.0.3
 * Multiplayer or Singleplayer: LAN (single)
 * Crash Report Link: none
 * Affected Features: conductor mast, electric diamonds
 * Description: 

Conductor mast neither generating power, nor creating electric diamonds from fire diamonds. Playing in Modern Skyblock 2 modpack, doublechecked all recipes, and moved mast to different chunks and heights. There is a lightning flash in the sky (not vanilla, calculator's), but it doesn't have any effect on conductor mast.

**Comment by Wolflairovi4** [comment]
At me it also does not work :(
calculator-1.12.2-5.0.2
sonarcore-1.12.2-5.0.3
forge-1.12.2-14.23.1.2577

**Comment by JonathanPCode** [comment]
I have a similar problem, I can't extract energy from the calculator locator or the conductor mast.
Calculator: 5.0.2
Sonar Core: 5.0.3
Forge: 14.23.1.2556

**Comment by Leftorius** [comment]
any news or do we need to roll back?

**Comment by aerde** [comment]
I just added electric diamond recipe to the atomic reconstructor from AA via crafttweaker. As I’m playing solo, it’s faster to wait, and acceptable for me.

**Comment by Chunkey** [comment]
Same problem. DNS techpack.
calculator-1.12.2-5.0.2
sonarcore-1.12.2-5.0.4
forge-1.12.2-14.23.1.2555

**Comment by futurerealm** [comment]
1.12.2 for all
calculator - 5.0.2
sonarcore - 5.0.3
forge - 14.23.1.2566

Multiplayer server, Conductor mast not producing power during strikes, which obviously leads to not being able to create electric diamonds. Playing on Horizons III 1.5.0

**Comment by NewtonAppolonius** [comment]
Not working for me as well.
Calculator - 5.02
SonarCore - 5.04
Forge 14.23.1.2583
  
Playing on Horizons III

**Comment by nolaw70** [comment]
Same on FTB Horizons III 1.6.0 (current locked version on the launcher as of 7 Jan 18):

Calculator - 5.02
SonarCore - 5.04
Forge 14.23.1.2573

Conductor mast set alone (no weather stations, cables, etc) receives strikes, but the fire diamond does not change. No energy is stored in the Conductor mast after the strike.

**Comment by Chefbarbie** [comment]
25 Days and not even a response? Count me the same, Horizons III 1.6.0 nothing changed.

**Comment by AEnterprise** [comment]
the mod author barely has time to respond to tickets or update the mod, it might take a while to get looked it, if anyone wants dig into and and make a PR to fix it i'm sure he'll welcome it

**Comment by PaulMurrayCbr** [comment]
Same thing, New Horizons |||. Looks like I'll have to build an enderman farm after all :( .

**Comment by SonarSonic** [comment]
The Conductor Mast & Calculator Locator's were fixed in Calculator 5.0.3 / Sonar Core 5.0.5
Please Update :)
