### ISSUE TITLE
Conductor Mast not generating power

### ISSUE THREAD

**Issue by Gpax971** [SonarSonic/Calculator#327]
Please fill out the details below before contributing

 * Forge Version: 14.23.1.1566
 * Calculator Version: 1.12.2-5.0.2
 * SonarCore Version: 1.12.2-5.0.3
 * Multiplayer or Singleplayer: Multiplayer (Not tested singleplayer)
 * Crash Report Link: N/A
 * Affected Features: Conductor mast RF generation
 * Description: When I place a Conductor Mast down, no matter what I do, it will never generate any actual power. It gives stats on the previous strike and give the timing but whenever lightning strikes, there is no power generated.

**Comment by AGkizlis** [comment]
Same here with modpack FTB Horizons III.

**Comment by Gpax971** [comment]
Edit : mod pack is Horizons III V1.6.0 but the issue was also in 1.5.0.

**Comment by kwpugh** [comment]
Same here.

**Comment by chrixian** [comment]
Playing Modern Skyblock 2 and same problem.

**Comment by trechetican** [comment]
same problem here on 5.0.2

**Comment by chrixian** [comment]
5.0.3 appears to close this issue, yay.

**Comment by SonarSonic** [comment]
Fixed in 5.0.3
