### ISSUE TITLE
Locator not outputting power

### ISSUE THREAD

**Issue by wakelicious** [SonarSonic/Calculator#328]
Please fill out the details below before contributing

 * Forge Version: 14.23.1.2575
 * Calculator Version: calculator-1.12.2-5.0.2
 * SonarCore Version: sonarcore-1.12.2-5.0.4
 * Multiplayer or Singleplayer: Both
 * Crash Report Link: N/A
 * Affected Features: Power output of Locator
 * Description: I've created a 7x7 setup with plugs and a locator. It is generating power (~12krf/t) however it won't output power. I've used flux plugs, rftools powercell, thermal dynamics fluxducts and nothing will take its power.

Additional: Modpack I'm playing is FTB Revelation, I manually added calculator.

**Comment by jonabrv1965** [comment]
Hi. Same here. But with forge 2555. 
sonarcore-1.12.2-5.0.4,
calculator-1.12.2-5.0.2
It happened as soon as I updated the sonarcore package.. If I rollback to an earlier sonarcore, the generator works fine (but calculator´s circuits manipulation machines do not). I found that if you create a new locator (without power stored) and put in place it generates the 25M RF internal buffer, but not output anything using any cable/cell as wakelicious mentions.

**Comment by AGkizlis** [comment]
Same here with modpack FTB Horizons III.

**Comment by grav0r** [comment]
Same here with Modern Skyblock 2.
It currently runs 
Sonarcore-1.12.2-5.0.4,
Calculator-1.12.2-5.0.2
on Forge 2582
- no way to extract power from Locator, and you can´t even charge things in it.

**Comment by SonarSonic** [comment]
Fixed in Calculator 5.0.3 / Sonar Core 5.0.5
