### ISSUE TITLE
Prunae and Fiddledew can be planted in all tiers of Greenhouses

### ISSUE THREAD

**Issue by Lykrast** [SonarSonic/Calculator#329]
* Forge Version: 14.23.1.2582
 * Calculator Version: 5.0.2
 * SonarCore Version: 5.0.4
 * Multiplayer or Singleplayer: Singleplayer, probably both
 * Crash Report Link: N/A
 * Affected Features: Prunae Seeds, Fiddledew Fruit, Greenhouse
 * Description: Prunae Seeds and Fiddledew Fruits can be planted and farmed by all Greenhouses (including the basic one) despite their tooltip stating that they need an Advanced or higher (for Prunae) or a Flawless one (for Fiddledew) to be planted.

**Comment by SonarSonic** [comment]
Fixed in dev
