### ISSUE TITLE
[QUESTION] Greenhouses support Agricraft?

### ISSUE THREAD

**Issue by hron84** [SonarSonic/Calculator#33]
I'd like to include this mod in my modpack, however I already use Agricraft in hard mode, so no planting allowed other than AC crop sticks. How Calculator can fit in this world?

**Comment by SonarSonic** [comment]
Let me get this straight. You want a way to remove compatibility with Agricraft?

**Comment by hron84** [comment]
@SonarSonic Absolutely not, I just do not know if calculator supports or not Agricraft's hard mode. Does it?

**Comment by SonarSonic** [comment]
In that case no. Currently you greenhouse's don't place down cropsticks or plant things into them. I could add a feature which lets Crops be planted into crop sticks but it would make more sense if you had to place the crop sticks yourself.

**Comment by hron84** [comment]
@SonarSonic I can live with it if otherwise greenhouses can plant/harvest things correctly. This is not trivial with cropsticks since you cannot break the whole block, just reset the growth stage.

**Comment by SonarSonic** [comment]
Yeah that's not a problem. As long as the maker of Agricraft has clear code I can do it :)

**Comment by hron84** [comment]
@InfinityRaider should help you :-)

**Comment by InfinityRaider** [comment]
I'm not familiar with this mod and I don't know what this is about, but if you have a question about Agricraft, I'm happy to help out.

**Comment by SonarSonic** [comment]
@InfinityRaider Well basically along with loads of other things I have some Green houses which automate crop growth. I am wondering if there is an API or some other way of planting into Crop Sticks and removing them automatically once fully grown?

**Comment by InfinityRaider** [comment]
Yes there is: https://github.com/InfinityRaider/AgriCraft/blob/master/src/main/java/com/InfinityRaider/AgriCraft/api/v1/APIv1.java

**Comment by SonarSonic** [comment]
@InfinityRaider Hey, i'm having trouble using your mod in my dev environment trying to use the API. It just crashes every time because it can't find the APISelector class. Is there a dev jar version?
This is how i'm getting the API at the moment 	

public static Object getAgricraftAPI() {
		if (Loader.isModLoaded("Agricraft")) {
			APIBase api = API.getAPI(1);
			if (api.getStatus().isOK() && api.getVersion() == 1) {
				return api;
			}
		}
		return null;
	}

**Comment by InfinityRaider** [comment]
A dev jar version of the API or one for AgriCraft?

**Comment by SonarSonic** [comment]
It's launching now but the above method is always returning null despite agricraft being loaded.

**Comment by InfinityRaider** [comment]
Hmm, do you have AgriCraft as a lib as well as the api seperatly? It might be grabbing from the duplicate API, which is not initialized.

**Comment by SonarSonic** [comment]
@InfinityRaider what is the best method for creating/using the Agricraft API??

**Comment by InfinityRaider** [comment]
Give me some time, I'll make a PR

**Comment by SonarSonic** [comment]
done!

**Comment by hron84** [comment]
@SonarSonic @InfinityRaider thanks for your hard work and great assistance in this integration!

**Comment by SonarSonic** [comment]
A few little problems with the current build, servers may not work but should be sorted tonight/tommorrow
