### ISSUE TITLE
Calculator v1.12.2-5.0.3 crash on load

### ISSUE THREAD

**Issue by NewtonAppolonius** [SonarSonic/Calculator#335]
Please fill out the details below before contributing

 * Forge Version:  1.12.2-14.23.1.2594 (Version required by Industrial Foregoing)
 * Calculator Version:  calculator-1.12.2-5.0.3
 * SonarCore Version:  sonarcore-1.12.2-5.0.5
 * Multiplayer or Singleplayer: Single
 * Crash Report Link: 
[crash-2018-01-30_11.04.08-server.txt](https://github.com/SonarSonic/Calculator/files/1677470/crash-2018-01-30_11.04.08-server.txt)

 * Affected Features: Minecraft failed to load. Rollback to previous versions of Calculator&SonarCore and it works.
 * Description:  I ran this past the XNet developer first as the crash report contains references to XNet. He said to pass it to you as he cannot see any problems with XNet. Thank you.

**Comment by zackeezy** [comment]
it appears to be caused by xnet. Post the issue there as well.

**Comment by SonarSonic** [comment]
Please See #345, Fix should be out later today.
