### ISSUE TITLE
Calculator crash when items are inserted into machines 

### ISSUE THREAD

**Issue by superfluke** [SonarSonic/Calculator#336]
* Forge Version:  forge-1.12.2-14.23.1.2594
 * Calculator Version: calculator-1.12.2-5.0.3.jar
 * SonarCore Version: sonarcore-1.12.2-5.0.5.jar
 * Multiplayer or Singleplayer: Both
 * Crash Report Link: 
[Crash report using Exu2 to insert into calc chamber](https://pastebin.ubuntu.com/26498036/)
[Crash report using TE to insert into calc chamber](https://pastebin.ubuntu.com/26498082/)
 * Affected Features: Calc machines 
 * Description: Trying to insert items into calc machines (the precision chamber and I believe the extraction chamber) causes a crash. Tested using a two different mod item pipes.

**Comment by Deregorn** [comment]
I get a similar crash with the docking station (I was able to get items into it with xnet, but as soon as I try to extract something the server crashes and I have to restore a backup).

**Comment by SonarSonic** [comment]
Please see #345, Fix should be out later today.
