### ISSUE TITLE
Crash on load using version 5.0.3

### ISSUE THREAD

**Issue by Vacosa** [SonarSonic/Calculator#337]
Please fill out the details below before contributing

 * Forge Version: forge-14.23.1.2587
 * Calculator Version: 5.0.3
 * SonarCore Version: 5.0.4
 * Multiplayer or Singleplayer: Single
 * Crash Report Link: 
 * Affected Features: 
[crash-2018-02-04_19.48.42-client.txt](https://github.com/SonarSonic/Calculator/files/1693253/crash-2018-02-04_19.48.42-client.txt)

 * Description: modded version of the Direwolf220 1.12.2 pack, when i run Calc 5.0.2 it loads fine, however when i upgrade my Calc version to 5.0.3 (because masts are broken in 5.0.2) it does not finish prelaunch loading of the mods.

**Comment by SonarSonic** [comment]
Bad compile, should be fixed in next version.

**Comment by SonarSonic** [comment]
Please See #345, Fix should be out later today.
