### ISSUE TITLE
[1.12.2] Server Crash with Extraction Chamber and vanilla chest

### ISSUE THREAD

**Issue by kwpugh** [SonarSonic/Calculator#341]
Please fill out the details below before contributing

 * Forge Version: forge-1.12.2-14.23.2.2613-universal.jar
 * Calculator Version: calculator-1.12.2-5.0.3.jar
 * SonarCore Version: sonarcore-1.12.2-5.0.5.jar
 * Multiplayer or Singleplayer: MP
 * Crash Report Link: https://gist.github.com/kwpugh/0bacb70638059b9b1c137fa3984a182f
 * Affected Features: Extraction Chamber transfer 
 * Description: added a transfer upgrade to an Extraction Chamber, placed a vanilla chest on the side and crash

**Comment by SonarSonic** [comment]
Will be fixed in next SonarCore / Calculator Version
