### ISSUE TITLE
[1.12.2] Server / Clientcrash when using importbus from RS on Reinforced Furnace!

### ISSUE THREAD

**Issue by Patrick1005de** [SonarSonic/Calculator#343]
Please fill out the details below before contributing

 * Forge Version: 2616
 * Calculator Version: 5.0.3
 * SonarCore Version: 5.0.5
 * Multiplayer or Singleplayer: MP and SP
 * Crash Report Link: https://pastebin.com/ymDMd1Xp
 * Affected Features: 
 * Description: The Server and Client crashed when I installed a importbus from Refined Storage on the Reinforced Furnace.

**Comment by SonarSonic** [comment]
Please see #345, Fix should be out later today.
