### ISSUE TITLE
World crash from using hopper with a storage chamber... now I cant load the world anymore crash on load

### ISSUE THREAD

**Issue by trader94** [SonarSonic/Calculator#346]
Please fill out the details below before contributing

 * Forge Version: forge-1.12.2-14.23.1.2555.jar
 * Calculator Version: calculator-1.12.2-5.0.3.jar
 * SonarCore Version:  sonarcore-1.12.2-5.0.5.jar
 * Multiplayer or Singleplayer: Singleplayer
 * Crash Report Link: 
 * Affected Features: when attempting to use a hopper under a storage chamber to funnel things out
 * Description: i had a hopper feeding damaged circuits into a storage chamber.  every slot was occupied in the chamber and i had a few hours worth of circuits in there, i attempted to use a hopper to funnel the circuits out of the storage chamber and into a processing chamber but as soon as i placed the hopper the game crashed.  this is the second time this happened to me.  the first time i was only using calculator mod, optifine, finder compass and carryon mod.  ive lost so many hours of progress because of this.  im not sure how to roll back my game world to before i placed the hopper... i dont know if thats even possible.   here is the crash report, ive got lots of mods installed but i was only using calculator machines at the time this happened, and it happened once before as well so im pretty sure this is the problem.

I Also have the whole save file and everything in this particular world save in a folder, if this would help you just let me know and i can send it to you somehow.

---- Minecraft Crash Report ----

WARNING: coremods are present:
  FCFMLCorePlugin (Finder-Compass-Mod-1.12.1.jar)
Contact their authors BEFORE contacting forge

// Why is it breaking :(

Time: 2/28/18 11:26 PM
Description: Ticking block entity

java.lang.AbstractMethodError
	at net.minecraftforge.items.VanillaInventoryCodeHooks.isFull(VanillaInventoryCodeHooks.java:234)
	at net.minecraftforge.items.VanillaInventoryCodeHooks.insertHook(VanillaInventoryCodeHooks.java:132)
	at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:194)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:137)
	at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:122)
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at net.minecraftforge.items.VanillaInventoryCodeHooks.isFull(VanillaInventoryCodeHooks.java:234)
	at net.minecraftforge.items.VanillaInventoryCodeHooks.insertHook(VanillaInventoryCodeHooks.java:132)
	at net.minecraft.tileentity.TileEntityHopper.func_145883_k(TileEntityHopper.java:194)
	at net.minecraft.tileentity.TileEntityHopper.func_145887_i(TileEntityHopper.java:137)
	at net.minecraft.tileentity.TileEntityHopper.func_73660_a(TileEntityHopper.java:122)

-- Block entity being ticked --
Details:
	Name: minecraft:hopper // net.minecraft.tileentity.TileEntityHopper
	Block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (62,65,133), Chunk: (at 14,4,5 in 3,8; contains blocks 48,0,128 to 63,255,143), Region: (0,0; contains chunks 0,0 to 31,31, blocks 0,0,0 to 511,255,511)
	Actual block type: ID #154 (tile.hopper // net.minecraft.block.BlockHopper)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1829)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:612)

-- Affected level --
Details:
	Level name: calculator + buildcraft 1
	All players: 0 total; []
	Chunk stats: ServerChunkCache: 625 Drop: 0
	Level seed: 2975522109624043146
	Level generator: ID 00 - default, ver 1. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-40,64,256), Chunk: (at 8,4,0 in -3,16; contains blocks -48,0,256 to -33,255,271), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 713639 game time, 909181 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 57580 (now: false), thunder time: 137327 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:252)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524)
	at java.lang.Thread.run(Unknown Source)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_161, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 462110128 bytes (440 MB) / 1298280448 bytes (1238 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 14, tallocated: 94
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 Optifine OptiFine_1.12.2_HD_U_C8 33 mods loaded, 33 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State     | ID                  | Version      | Source                                | Signature                                |
	|:--------- |:------------------- |:------------ |:------------------------------------- |:---------------------------------------- |
	| UCHIJAAAA | minecraft           | 1.12.2       | minecraft.jar                         | None                                     |
	| UCHIJAAAA | mcp                 | 9.42         | minecraft.jar                         | None                                     |
	| UCHIJAAAA | FML                 | 8.0.99.99    | forge-1.12.2-14.23.1.2555.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | forge               | 14.23.1.2555 | forge-1.12.2-14.23.1.2555.jar         | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJAAAA | anvils              | 1.4.0.0      | Anvil-Enchantments-Mod-1.12.2.jar     | None                                     |
	| UCHIJAAAA | appliedenergistics2 | rv5-alpha-8  | Applied-Energistics-2-Mod-1.12.2.jar  | None                                     |
	| UCHIJAAAA | buildcraftlib       | 7.99.15      | buildcraft-7.99.15.jar                | None                                     |
	| UCHIJAAAA | buildcraftcore      | 7.99.15      | buildcraft-7.99.15.jar                | None                                     |
	| UCHIJAAAA | buildcraftbuilders  | 7.99.15      | buildcraft-7.99.15.jar                | None                                     |
	| UCHIJAAAA | buildcraftenergy    | 7.99.15      | buildcraft-7.99.15.jar                | None                                     |
	| UCHIJAAAA | buildcraftfactory   | 7.99.15      | buildcraft-7.99.15.jar                | None                                     |
	| UCHIJAAAA | buildcraftrobotics  | 7.99.15      | buildcraft-7.99.15.jar                | None                                     |
	| UCHIJAAAA | buildcraftsilicon   | 7.99.15      | buildcraft-7.99.15.jar                | None                                     |
	| UCHIJAAAA | buildcrafttransport | 7.99.15      | buildcraft-7.99.15.jar                | None                                     |
	| UCHIJAAAA | buildcraftcompat    | 7.99.14      | buildcraft-compat-7.99.14.jar         | None                                     |
	| UCHIJAAAA | ic2                 | 2.8.16-ex112 | Industrialcraft-1.12.jar              | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJAAAA | sonarcore           | 5.0.5        | sonarcore-1.12.2-5.0.5.jar            | None                                     |
	| UCHIJAAAA | calculator          | 5.0.3        | calculator-1.12.2-5.0.3.jar           | None                                     |
	| UCHIJAAAA | carryon             | 1.7.2        | CarryOn+MC1.12.2+v1.7.2.jar           | None                                     |
	| UCHIJAAAA | torohealthmod       | 1.12.2-11    | Damage-Indicators-1.12.2.jar          | None                                     |
	| UCHIJAAAA | enchantchanger      | 1.12-1.9.11  | EnchantChanger-1.12.2.jar             | None                                     |
	| UCHIJAAAA | energyconverters    | 1.0.1.2      | Energy-Converters-Mod-1.12.1.jar      | None                                     |
	| UCHIJAAAA | ezstorage           | 2.5.0        | EZ-Storage-2-1.12.2.jar               | None                                     |
	| UCHIJAAAA | fencejumper         | 1.0.1        | Fence-Jumper-1.12.2.jar               | None                                     |
	| UCHIJAAAA | findercompass       | 1.12         | Finder-Compass-Mod-1.12.1.jar         | None                                     |
	| UCHIJAAAA | giacomos_exp        | 1.2.1        | GiacomosExperienceSeedling-1.12.2.jar | None                                     |
	| UCHIJAAAA | waila               | 1.8.23       | Hwyla-1.8.23-B38_1.12.jar             | None                                     |
	| UCHIJAAAA | journeymap          | 1.12.2-5.5.2 | JourneyMap-1.12.2.jar                 | None                                     |
	| UCHIJAAAA | jei                 | 4.8.0.114    | Just-Enough-Items-Mod-1.12.2.jar      | None                                     |
	| UCHIJAAAA | jeresources         | 0.8.5.26     | JustEnoughResources-1.12.2.jar        | None                                     |
	| UCHIJAAAA | recipehandler       | 0.10         | NoMoreRecipeConflict-0.10(1.12.2).jar | None                                     |
	| UCHIJAAAA | quickleafdecay      | 1.2.4        | QuickLeafDecay-1.12.2.jar             | None                                     |
	| UCHIJAAAA | switchbow           | 1.5          | Switch-Bow-Mod-1.12.2.jar             | None                                     |

	Loaded coremods (and transformers): 
FCFMLCorePlugin (Finder-Compass-Mod-1.12.1.jar)
  atomicstryker.findercompass.client.coremod.FCTransformer
	GL info: ~~ERROR~~ RuntimeException: No OpenGL context found in the current thread.
	AE2 Version: alpha rv5-alpha-8 for Forge 14.23.0.2491
	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, InvTweaks:OFF, JEI:ON, Mekanism:OFF, OpenComputers:OFF, THE_ONE_PROBE:OFF, TESLA:OFF
	Profiler Position: N/A (disabled)
	Player Count: 0 / 8; []
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	OptiFine Version: OptiFine_1.12.2_HD_U_C8
	Render Distance Chunks: 28
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: SEUS Renewed 1.0.0.zip
	OpenGlVersion: 4.6.0 NVIDIA 388.71
	OpenGlRenderer: GeForce GTX 1080/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12

**Comment by SonarSonic** [comment]
Thanks for reporting I know what's causing, should have a fix out tonight

**Comment by SonarSonic** [comment]
Also you're running old version of Calculator and Sonar Core already
