### ISSUE TITLE
Crash on load world

### ISSUE THREAD

**Issue by BreadtheRipper** [SonarSonic/Calculator#354]
Please fill out the details below before contributing

 * Forge Version: forge-14.23.1.2582
 * Calculator Version: 1.12.2-5.0.4
 * SonarCore Version:1.12.2-5.0.6
 * Multiplayer or Singleplayer: Singleplayer
 * Crash Report Link: [crash-2018-03-22_12.06.50-server.txt](https://github.com/SonarSonic/Calculator/files/1838364/crash-2018-03-22_12.06.50-server.txt) (I'm unsure if this is the relevant report, but this was what generated when it crashed)
 * Affected Features: Unable to load world
 * Description: Updated from 5.0.2 (to fix the masts not working), and now the world I've been playing in crashes when I try to load it up, however generating a new world works fine

**Comment by SonarSonic** [comment]
Update Flux Networks
