### ISSUE TITLE
Storage Chamber not rendering circuits

### ISSUE THREAD

**Issue by pupnewfster** [SonarSonic/Calculator#356]
Please fill out the details below before contributing

 * Forge Version: 1.12.2 14.23.2.2654
 * Calculator Version: 1.12.2-5.0.4
 * SonarCore Version: 1.12.2-5.0.7
 * Multiplayer or Singleplayer: Multiplayer
 * Crash Report Link: Not a Crash
 * Affected Features: Storage Chamber rendering
 * Description: Once the storage chamber gets to a certain number of circuits it does not render them in the gui anymore. (I have over 160 of each circuit in the storage chamber). I have a circuit processing setup that has been running overnight with a chunk loader so I am not sure how many circuits are needed to cause them to stop rendering. I am able to pull circuits out of it by clicking them though I cannot tell ahead of time which circuit it is that I am grabbing.

**Comment by Axylxys** [comment]
Same issue here. The storage chamber is a nightmare since 1.10 version, and it carries over to 1.12. Not rendering circuits, not accepting some of them from automatic systems with no real pattern involved, i just can't get it to work properly or interact with any kind of item transport.

**Comment by SonarSonic** [comment]
Fixed in dev - 1.12.2 only at the moment.
