### ISSUE TITLE
1.12.2 - 5.0.4 Flawless greenhouse output nothing to box, and pipes can only pull out seeds.

### ISSUE THREAD

**Issue by templefox** [SonarSonic/Calculator#357]
* Forge Version: 1.12.2- 14.23.2.2654
 * Calculator Version: 1.12.2- 5.0.6
 * SonarCore Version: 1.12.2- 5.0.6
 * Multiplayer or Singleplayer: single
 * Crash Report Link: 
 * Affected Features: Flawless greenhouse
 * Description: 

1. The texture not changes when I finish the flawless greenhouse, but the greenhouse does work.

1. A box in front of the flawless greenhouse is useless. No automatic output as other greenhouses.
I can use pipe to pull the items out, but only seeds are pulled. The wheat(or other result) still in the greenhouse block. Finally it will spew out all result and seeds, and won't replant because the inventory is full of wheat.

**Comment by SonarSonic** [comment]
Fixed in dev
