### ISSUE TITLE
Reinforced Furnace - producing gold out of rf only

### ISSUE THREAD

**Issue by AbieTheFishman** [SonarSonic/Calculator#359]
Please fill out the details below before contributing

 * Forge Version: 14.23.3.2702
 * Calculator Version: 1.12.2-5.0.4
 * SonarCore Version: 1.12.2-5.0.9
 * Multiplayer or Singleplayer: Single
 * Crash Report Link: 
 * Affected Features: Reinforced Furnace
 * Description: When placed and powered - produces gold ingots (2)! never stops

**Comment by SonarSonic** [comment]
I couldn't recreate this at all. So you place a Furnace and it just produces ingots, from RF only, you don't input gold ore or anything? To me sounds like could be a mod pack issue.

**Comment by AbieTheFishman** [comment]
Yep, also tried in a "new" creative world... same thing. It makes to 2 ingots per cycle.
rolled my own modpack

FYI mod list

- [1.12]MoVillages-1.5.4.jar
- ActuallyAdditions-1.12.2-r135.jar
- ActuallyBaubles-1.12-1.1.jar
- AnvilEnchantments-1.12.2-1.4.0.0.jar
- AppleSkin-mc1.12-1.0.9.jar
- Aroma1997Core-1.12.2-1.3.0.2.jar
- Aroma1997s-Dimensional-World-1.12-1.3.0.0.b37.jar
- AromaBackup-1.12.2-2.1.1.3.jar
- BaseMetals-1.12-2.5.0-beta5.214.jar
- Baublelicious-1.4.0-4.jar
- Baubles-1.12-1.5.2.jar
- bdlib-1.14.3.12-mc1.12.2.jar
- bedpatch-2.2-1.12.2.jar
- BetterBuildersWands-1.12-0.11.1.245+69d0d70.jar
- BetterFps-1.4.8.jar
- BiomesOPlenty-1.12.2-7.0.1.2384-universal.jar
- calculator-1.12.2-5.0.4.jar
- ChestTransporter-1.12.2-2.8.8.jar
- Chisel-MC1.12.2-0.2.0.31.jar
- CodeChickenLib-1.12.2-3.1.8.341-universal.jar
- CommonCapabilities-1.12-1.4.0.jar
- CompositeGear-1.12.2-1.4.jar
- Controlling-3.0.6.jar
- CraftTweaker2-1.12-4.1.8.jar
- CsokiCraftUtil-1.3.6.jar
- CTM-MC1.12-0.2.3.12.jar
- CyclopsCore-1.12.2-0.11.6.jar
- Dungeons2-mc1.12.2-f14.23.1.2555-v1.3.3.jar
- EnderStorage-1.12.2-2.4.2.126-universal.jar
- extrautils2-1.12-1.7.6.jar
- FinderCompass-1.12.1.jar
- Flopper-1.12.2-1.0.2.jar
- fluxnetworks-1.12.2-3.0.10.jar
- forestry_1.12.2-5.8.0.291.jar
- ForgeMultipart-1.12.2-2.4.2.58-universal.jar
- FTBLib-5.1.0.19.jar
- FTBUtilities-5.1.0.23.jar
- furnus-1.12.2-2.1.5.jar
- gendustry-1.6.5.8-mc1.12.2.jar
- generators-0.9.20.12-mc1.12.2.jar
- GottschCore-mc1.12.2-f14.23.2.2611-v1.3.5.jar
- Harvest-1.12-1.2.6-18.jar
- hopperducts-mc1.12-1.5.jar
- industrialcraft-2-2.8.73-ex112.jar
- IntegratedDynamics-1.12.2-0.11.12.jar
- IntegratedTunnels-1.12.2-1.5.6.jar
- InventoryTweaks-1.63.jar
- iridiumsource-2.0.1.jar
- IvToolkit-1.3.3-1.12.jar
- jei_1.12.2-4.9.1.188.jar
- jeibees-0.9.0.5-mc1.12.2.jar
- jeiintegration_1.12.2-1.5.1.36.jar
- journeymap-1.12.2-5.5.2.jar
- JustEnoughResources-1.12.2-0.8.5.27.jar
- limelib-1.12.2-1.7.11.jar
- mcjtylib-1.12-2.6.7.jar
- MCMultiPart-2.5.1.jar
- MobGrindingUtils-0.3.6.jar
- ModernConverter-2.1.1.jar
- ModernCraftCore-2.0.2.jar
- modtweaker-4.0.12.jar
- modular-routers-1.12.2-3.1.4.jar
- morebees-1.12.2-1.4.4.jar
- moreoverlays-1.13-mc1.12.1.jar
- MrTJPCore-1.12.2-2.1.1.27-universal.jar
- MTLib-3.0.4.jar
- NetherEx-1.12-2.1.14.15.jar
- NetherMetals-1.12-1.2.0-beta3.52.jar
- NoMoreRecipeConflict-0.10(1.12.2).jar
- OpenBlocks-1.12.2-1.7.6.jar
- OpenModsLib-1.12.2-0.11.5.jar
- OptiFine_1.12.2_HD_U_D1_MOD.jar
- OreExcavation-1.4.118.jar
- oreshrubs-1.4.4-1.12.2.jar
- OreSpawn-1.12-3.3.0.136.jar
- pressure-1.3.1.6-mc1.12.1.jar
- ProjectRed-1.12.2-4.8.6.74-Base.jar
- ProjectRed-1.12.2-4.8.6.74-integration.jar
- ProjectRed-1.12.2-4.8.6.74-lighting.jar
- ProjectRed-1.12.2-4.8.6.74-mechanical.jar
- ProjectRed-1.12.2-4.8.6.74-world.jar
- QuantumStorage-1.12-4.5.0.jar
- QuickLeafDecay-MC1.12.1-1.2.4.jar
- rangedpumps-0.5.jar
- RebornCore-1.12.2-3.8.3.279-universal.jar
- RebornStorage-1.12.2-3.1.0.50.jar
- RecurrentComplex-1.4.7.jar
- refinedstorage-1.5.34.jar
- refinedstorageaddons-0.3.jar
- rftools-1.12-7.33.jar
- RoguelikeDungeons-1.12.2-1.8.0.jar
- SimplyEnchanting-1.12-1.0.3.jar
- sonarcore-1.12.2-5.0.9.jar
- theoneprobe-1.12-1.4.22.jar
- tinyprogressions-1.12.2-3.3.27-Release.jar
- topaddons-1.12.2-1.6.0.jar
- torchmaster_1.12.2-1.6.4.62.jar
- toroquest-1.12.2-5.2.jar
- Translocators-1.12.2-2.5.0.70-universal.jar
- TrashSlot_1.12.1-8.4.6.jar
- TreeChopper-1.12.2-1.2.4.jar
- UniDict-1.12.2-2.5c.jar
- utilitybaseores-1.12.2-1.2.0.1.jar
- WanionLib-1.12.2-1.5.jar
- WearableBackpacks-1.12.2-3.1.2.jar
- World-Stripper-1.5.1-1.12.2.jar
- xnet-1.12-1.6.9.jar
- YABBA-1.1.2.8.jar

I do appreciate your work - Thanks

**Comment by SonarSonic** [comment]
Does it do this for all items?

**Comment by AbieTheFishman** [comment]
If I through something else in it will smelt it ( let's say cobble >> stone ) but once I pull the stone out it will start turning air into gold again.
![airtogold](https://user-images.githubusercontent.com/19936438/40691734-8de77b6e-637b-11e8-9dde-0b9dd9521c98.gif)

**Comment by SonarSonic** [comment]
I've fixed it my end, I shouldn't allow it to smelt empty stacks anyway, but one of your mods is adding a mapping of Air -> Gold Ingots
