### ISSUE TITLE
Caluclator 1.12.2- 5.0.5 Power Cube - Placing Power Cube - Crash and world corruption 

### ISSUE THREAD

**Issue by AbieTheFishman** [SonarSonic/Calculator#360]
Please fill out the details below before contributing

 * 
[crash-2018-05-27_08.02.47-server.txt](https://github.com/SonarSonic/Calculator/files/2046188/crash-2018-05-27_08.02.47-server.txt)
Forge Version: 14.23.3.2702
 * Calculator Version: 1.12.2-5.0.5
 * SonarCore Version: 1.12.2-5.0.9
 * Multiplayer or Singleplayer: Single
 * Crash Report Link: 
 * Affected Features: 
 * Description:

**Comment by SonarSonic** [comment]
I know what's causing this but won't be able to get a fix out for a few days, use Calculator 5.0.4 until then.

**Comment by AbieTheFishman** [comment]
Ok
Thank you

**Comment by Knito58** [comment]
I second this. Same error.

**Comment by SonarSonic** [comment]
Fixed version is out.

**Comment by Knito58** [comment]
Fix confirmed. Can place power cube without crashing the game.
