### ISSUE TITLE
[Bug] Wrenching a machine duplicates it

### ISSUE THREAD

**Issue by Skillotic0703** [SonarSonic/Calculator#366]
Please fill out the details below before contributing

 * Forge Version: 1.12.2 - 14.23.4.2705
 * Calculator Version: 1.12.2-5.0.6
 * SonarCore Version: 1.12.2-5.0.10
 * Multiplayer or Singleplayer: Singleplayer
 * Affected Features: Wrenching
 * Description: When using a wrench to dismantle a machine, it isn't dismantled but a duplicate of the machine is dropped.

**Comment by NewtonAppolonius** [comment]
Just to say I am seeing this as well. Same setup as above.
Edited to add: I tried deploying the duplicated masts and although they seem to work they crash Minecraft when you try to remove them via a pick.

**Comment by SonarSonic** [comment]
All issues mentioned fixed!
