### ISSUE TITLE
Something error about the conductormast

### ISSUE THREAD

**Issue by Coloryr** [SonarSonic/Calculator#372]
Something error about the conductormast

 * Forge Version: 1.12.2-14.23.4.2705
 * Calculator Version: calculator-1.12.2-5.0.8-4
 * SonarCore Version: sonarcore-1.12.2-5.0.13-11
 * Multiplayer or Singleplayer: Multiplayer
 * Crash Report Link: https://paste.ubuntu.com/p/yqR28GQDQ9/
 * Affected Features: 
 * Description: When I placed the conductormast,i destroyed it,when i placed again, it crashed.

**Comment by SonarSonic** [comment]
Fixed in dev: duplicate #371
