### ISSUE TITLE
Can't pull from Analyzing chamber

### ISSUE THREAD

**Issue by therodet** [SonarSonic/Calculator#373]
Forge: 14.23.4.2712
Calculator: 5.0.8-4
SonarCore: 5.0.13-11
Single-player
No crash report

Items can be piped to/from precision chamber, and processing chamber, and to the analyzing chamber, but cannot be piped out of analyzing chamber (both circuit and extra items slots)
I have tried using Ender I/O conduits, Extra Utilities transfer node, and a vanilla hopper.
This is in the Modern Skyblock 3 (v 3.4.1.4) mod pack

--- Update

Mekanism Logistical Transporter *IS* working

**Comment by SonarSonic** [comment]
Fixed in dev
