### ISSUE TITLE
Conductormast crashes game when EnderIO conduit connects with it

### ISSUE THREAD

**Issue by ridinginstyle00** [SonarSonic/Calculator#375]
* Forge Version: 1.12.2 - 14.23.4.2729 
 * Calculator Version: Calculator-1.12.2-5.0.8
 * SonarCore Version: Sonar-Core-1.12.2-5.0.13 
 * Multiplayer or Singleplayer: Singleplayer
 * Crash Report Link: Not available at this time, steps can be easily reproduced to cause the error.
 * Affected Features: EnderIO conduits, and Conductormast
 

* Description: When placing the Condunctormast next to an EnderIO conduit the game will immediately crash. It will continue to crash until you edit the world and remove the conduit connectivity to the Conductormast then will load normally. EnderIO conduits are connecting to other machines of different mods (i.e. Thermal Expansion, RFTools) with no issues, but crash specifically with Calculator's Conductormast. I have not found any other machines that produce a crash with the EnderIO conduit.

**Comment by SonarSonic** [comment]
Fixed in dev
