### ISSUE TITLE
[1.12.2] Automating machines and the love story with transferring items

### ISSUE THREAD

**Issue by 8Times** [SonarSonic/Calculator#376]

**Comment by thebigcarp321** [comment]
I am not able to to export either using EnderIO or AE2. I have attempted from the top or bottom. Importing works fine.

**Comment by scotty9090** [comment]
I ended up using Mekanism Logistical Transporters (since they seem to extract everything ... indiscriminately) to dump into a buffer chest, then filtered from there.

**Comment by Addramyr84** [comment]
Same issue with refined storage. This makes automating calculator very hard :(

**Comment by depressed-pho** [comment]
I could successfully export circuits from the green side of Analysing Chamber, using Xnet connectors. You apparently need to apply a Transfer Upgrade on that side to enable automation.

**Comment by SashaGelert** [comment]
Please fill out the details below before contributing

Forge Version: 14.23.4.2739
Calculator Version: 1.12.2-5.0.8-4
SonarCore Version: 1.12.2-5.0.13-15
Multiplayer or Singleplayer: Both
Crash Report Link: None
Affected Features: Docking Station

Description:
Docking Station does not export items from top or bottom (or any) side.
Tested with and without the transfer upgrade, no change.  Finished products refuse to be exported with EnderIO conduits, EnderIO item buffers, AE2 ME Import Bus, Extra Utilities 2 Transfer Node, or the Vanilla Hopper.

EDIT: Let's just list all the issues:
Storage Chamber
 - When broken by any means does not drop items.
 - Does not drop itself when broken.  Have to craft a new one.

Precision Chamber, Processing Chamber
 - Do not drop any upgrades when broken. 
 - Have no change in power use or speed regardless of number of upgrades installed (only tested up to eight of each before giving up)

**Comment by SonarSonic** [comment]
All Issues Fixed, Sonar Core will also need to be updated.
**Docking Station:** Outputting from top/bottom with any mods conduit or the transfer upgrade will now work.
**Analysing Chamber:** Outputting from assigned sides (via wrench) with any mods conduit or the transfer upgrade will now work.
**Storage Chamber:** Will now drop (with it's upgrades stored in NBT tag)
**ALL CHAMBERS:** Upgrades will now be dropped and should affect speed (and show it in gui)
