### ISSUE TITLE
Conductor mast/weather station/transmitter models are invisible!!

### ISSUE THREAD

**Issue by tawraven** [SonarSonic/Calculator#377]
* Forge Version: 14.23.4.2749
 * Calculator Version: 1.12.2-5.0.8-4
 * SonarCore Version: 1.12.2-5.0.15-13
 * Multiplayer or Singleplayer: SP
 * Crash Report Link: No crash
 * Affected Features: Conductor mast/weather station/transmitter
 * Description: Playing Modern Skyblock 3 ver 3.4.2.  I have 5 full size conductor mast setups with max weather stations and transmitters located in the nether.  Recently I updated the pack to this version and when i came into nether, all of the models (mast/station/transmitter) were missing and the mast wasn't working.  However I could see a hitbox of the item and WAILA/TheOneProbe/NEI (whatever it is called) showed the blocks still there.  I restarted my client and no change.  

So I spent the time destroying all of the invisible blocks and started to lay them all out again.  Conductor masts and weather stations are showing up but transmitters still do not have a visible model.  

I get no indication of anything going wrong in the log files.

**Comment by tawraven** [comment]
So apparently there are two different versions of each of the items shown in NEI.  I had cheated in the items to replace the broken ones, not realizing there was a difference.  One version has a missing model and the other shows up properly.  I'm guessing this is why my RF farm disappeared?

**Comment by SonarSonic** [comment]
These will now be hidden from JEI.
