### ISSUE TITLE
Flawless Greenhouse doesn't support Ender Lilly from Extra Utilities 2

### ISSUE THREAD

**Issue by depressed-pho** [SonarSonic/Calculator#378]
* Forge Version: 14.23.4.2758
 * Calculator Version: 1.12.2-5.0.8-4
 * SonarCore Version: 1.12.2-5.0.15-13
 * Multiplayer or Singleplayer: Singleplayer
 * Crash Report Link: N/A
 * Affected Features: Flawless Greenhouse
 * Description: 

1. The greenhouse plants Ender Lilly on neither Dirt nor End Stone, even though it accepts the lily as a valid seed. The seed won't be consumed either.

This might be because [the lily has a special plant type](https://github.com/rwtema/Extra-Utilities-2-Source/blob/master/1.10.2/src/main/java/com/rwtema/extrautils2/blocks/BlockEnderLilly.java#L43) so the [canSustainPlant() check](https://github.com/SonarSonic/Sonar-Core/blob/1.12.2/src/main/java/sonar/core/integration/planting/vanilla/Planter.java#L46) will never succeed?

2. The greenhouse *can* grow the lily insanely rapidly as expected, when you manually plant it.
3. However, it cannot harvest fully grown lilies.

[Not all custom plants are BlockCrops](https://github.com/SonarSonic/Sonar-Core/blob/1.12.2/src/main/java/sonar/core/integration/planting/vanilla/Harvester.java#L26). The lily doesn't extend it either. [Harvester::canHarvest](https://github.com/SonarSonic/Sonar-Core/blob/1.12.2/src/main/java/sonar/core/integration/planting/vanilla/Harvester.java#L25) should probably use IGrowable::canGrow instead, to see if it can still grow further. When it returns false it means it can be harvested.

**Comment by SonarSonic** [comment]
Fixed in dev
