### ISSUE TITLE
Game "Crash" Singleplayer

### ISSUE THREAD

**Issue by ghost** [SonarSonic/Calculator#388]
Please fill out the details below before contributing

 * Forge Version: forge-14.23.5.2838
 * Calculator Version: Calculator-1.12.2-5.0.11
 * SonarCore Version: Sonar-Core-1.12.2-5.0.19
 * Multiplayer or Singleplayer: Singleplayer
 * Crash Report Link: [Crash Report](https://pastebin.com/tdcGj3Zw)
 * Affected Features: On the Info Calculator.
 * Description: When im on a Info Calculator press the last button then crash my game complete.

**Comment by SonarSonic** [comment]
Fixed in dev
