### ISSUE TITLE
Feature Suggestion: Durability on tools

### ISSUE THREAD

**Issue by Badcholo** [SonarSonic/Calculator#39]
maybe a config option for tools to take durability and or to be RF powered.
some of the tools are just too easy to make and with no durability loss they are just too op.
I really like the damage and tool speeds. It just would be nice if they took damage or we were able to power them with RF like using a Capacitor.

**Comment by SonarSonic** [comment]
Which tools are you talking about? most the ones I can think of have durability other than the End Forged ones.
