### ISSUE TITLE
Automating Diamond Tree with Integrated tunnels

### ISSUE THREAD

**Issue by Kuperus** [SonarSonic/Calculator#390]
* Forge Version: 14.23.5.2847
 * Calculator Version: calculator-1.12.2-5.0.11-12.jar
 * SonarCore Version: 	sonarcore-1.12.2-5.0.19-20.jar
 * Multiplayer or Singleplayer: MP
 * Crash Report Link: N/A
 * Affected Features: Using sickle with player simulator from Integrated tunnels
 * Description: 
Since the higher tier assimilator is disabled in the pack, i thought of using a sickle in combination with a player simulator from Integrated Tunnels to harvest the diamonds (flawless and the other one) from a diamond tree... 

only result was that the beeds in the leaves disappear, but the diamonds are not put into an inventory. (as a player the diamonds are directly imported into your inventory).

Integrated Tunnels points to the calculator mod for inventory management in this. is it possible to let the diamonds drop into the "real world" when harvesting them by hand?

**Comment by SonarSonic** [comment]
The behavior will remain, that items are given to the player harvesting. However, when the next update comes out, the modpack can reactivate the Assimilator as this will be fixed.
