### ISSUE TITLE
Unable to use calculator in multiplayer. (Inventory shifting)

### ISSUE THREAD

**Issue by AutomaticDragon** [SonarSonic/Calculator#4]
Hi

We're having an issue on a multiplayer server whereby item stacks in the inventory seem to change randomly whenever a calculator UI is open, even if by luck you can get the correct items into the calculator UI it's impossible to retrieve the crafted item.

Thanks for your help :)

**Comment by SonarSonic** [comment]
I'm working on the fix at the moment, hopefully I can find the problem, I've had this bug for a long time :(
