### ISSUE TITLE
[Arbitrariness] Stablility of a Calculator Locator Multiblock Generator

### ISSUE THREAD

**Issue by condensedapple** [SonarSonic/Calculator#41]
First of all, thx for your awesome mod! For me, your mod is at least as important as Thermal Expansion or Applied Energistics. Unfortunately, the really cool Calculator Locator I've just built requires more stability, using these circuits. However, how do you determine whether a configuration is "stable" or "unstable"? Are there any hints how to set up a "good" Calculator Locator? You might also consider adding this topic to your detailed wiki. Thanks in advance!

**Comment by SonarSonic** [comment]
Stability is determined by how many of the Calculator Plugs as part of the Calculator Locator have stable circuits. If you don't have any stable circuits you need a circuit extraction system. When every Calculator Plug has a stable circuit you are then completely safe! You can find out if a circuit is stable either in the Analysing Chamber or just on the Tool Tip. I would recommend storing all the circuits you extract in two Storage Chambers one for Stable and one for normal Analysed ones. Hope this helps! Glad you like the mod! If you can think of any ways to improve aspects of it or add new things feel free to suggest them!

**Comment by condensedapple** [comment]
Thank you very much for your quick reply. Everything is working now! Keep up the great work!
