### ISSUE TITLE
[QUESTION] Is there a way to automate pear/diamond trees with Thaumcraft?

### ISSUE THREAD

**Issue by hron84** [SonarSonic/Calculator#42]
I just wondering if there's any way to automate your fruit trees with thaumcraft. Use golems can use sickle on leaves, but I dunno if user-placed leaves with some wood behind can work, or you handle trees as a multiblock construct that cannot be re-constructed any other way than planting a sapling. Could you help me to figure it out?

**Comment by SonarSonic** [comment]
in the latest versions there are assimilators which automate harvesting trees for you! :)

**Comment by hron84** [comment]
Wow. They're operating like greenhouses (taking power, putting fruits into chest)?

**Comment by SonarSonic** [comment]
they don't actual use power in the current version, they might later. They have internal inventories but you can export as needed. There is an Algorithm Assimilator for Pear & Diamond and the Stone Assimilator for Amethyst & Tanzanite.

**Comment by hron84** [comment]
Last question: what is the range?

**Comment by SonarSonic** [comment]
One is required per tree, but trees now grow back, so don't need to be replanted.
https://github.com/SonarSonic/Calculator/wiki/Assimilators
