### ISSUE TITLE
Cannot Import Items Into Algorithm Separator

### ISSUE THREAD

**Issue by XenoStone1009** [SonarSonic/Calculator#49]
I have tried many ways to input items automatically to the Algorithm Separator: AE, Item Ducts, Transfer Nodes... None of them work for me. I made sure that the color was correct but nothing has yet to happen.

**Comment by SonarSonic** [comment]
Could you post screenshots?

**Comment by SonarSonic** [comment]
I have found the issue, thanks for reporting it. It seems to effect a number of machines

**Comment by SonarSonic** [comment]
Fixed in 1.8.9
