### ISSUE TITLE
Documentation for Minetweaker?

### ISSUE THREAD

**Issue by Tedyhere** [SonarSonic/Calculator#51]
Could we get some Documentation for the Minetweaker support added?

**Comment by SonarSonic** [comment]
https://github.com/SonarSonic/Calculator/wiki/Integration-and-APIs#mine-tweaker
Is this okay?

**Comment by Tedyhere** [comment]
Good enough

**Comment by SonarSonic** [comment]
@AEnterprise Anything else I should add?

**Comment by AEnterprise** [comment]
nope looks good to me, just give me a poke if you ever change anything and i'll update that gist
