### ISSUE TITLE
[1.8.9] Flawless Greenhouse

### ISSUE THREAD

**Issue by Skillotic0703** [SonarSonic/Calculator#52]
1) The Flawless Greenhouse doesn't want to plant the crops I put in it. However, it harvests crops that I plant manually (Tested with carrots, prunae seeds, broccoli seeds). That's not a problem when using agricraft crops because seeds on crops are not broken when harvested by the greenhouse (Tested with platiolus seed : shiny seed).

2) The Flawless Greenhouse is outputting its harvested resources by the input (left side according to the wiki) even if there's a chest on the right side of the Greenhouse.

3) The Flawless Greenhouse is working without placing the two chests (which are necessary for the greenhouse to work according to the wiki).

4) The Advanced Greenhouse is inputting and outputting to the same chest (the chest that is placed in front of the Greenhouse block) but that's a cool feature because it detects automatically what item to input and what item to output. That would be cool if the Flawless Greenhouse could do the same thing because it is currently not outputting anything into the chest (the chest on the left) unless the Greenhouse itself is full and not outputting at all on the right so the Flawless Greenhouse is useless at the moment unless we use it with agricraft crops.

5) I didn't tested the Basic Greenhouse.

**Comment by SonarSonic** [comment]
1) I can't recreate this, they plant perfectly in the test world. Does the greenhouse have power? Does it give a size read out?
2 & 3) My bad the Greenhouses all only need on chest now. I'll update that
4)The Flawless Greenhouse should be doing the same. 

I think issue 1) is to do with playing a pack which has normal planting disabled, try using crop sticks, if this doesn't work I'll make some changes to the code

**Comment by Skillotic0703** [comment]
1) That's working with crop sticks but prunae and broccoli seeds can't be planted on crop sticks.
It still doesn't plant automatically the other plants even with crop sticks already planted. I tested without agricraft and it is working very well when using a new world.

2) New bug : When I place a chest from the Iron chest mod in front of The Flawless Greenhouse block of a working Greenhouse and I break The Flawless Greenhouse block then replace it, the chest is replaced by a copper chest.

3) The Flawless Greenhouse still doesn't output to the chest without being full.

**Comment by SonarSonic** [comment]
1) Prunae and Broccoli shouldn't work with Crop Sticks anyway.
2) Bit strange I'll have a look later
3)That is the correct thing to do. It fills its own inventory first then overflows to the chest.

**Comment by Skillotic0703** [comment]
Ok thanks but the Flawless Greenhouse doesn't want to plant prunae and broccoli seeds when agricraft is installed.

**Comment by Skillotic0703** [comment]
Fiddledew fruit is also not being planted when agricraft is installed.

**Comment by Skillotic0703** [comment]
And that's a problem because it can't be planted with the advanced greenhouse.

**Comment by SonarSonic** [comment]
Is the Advanced not planting them either for you?

**Comment by SonarSonic** [comment]
Also could you send me the AgriCraft Config file in your instance?

**Comment by Skillotic0703** [comment]
The Advanced is working very well but the fiddledew fruit can't be planted by the Advanced Greenhouse (It's written in its tooltip)

**Comment by Skillotic0703** [comment]
http://pastebin.com/8zhtfkzt

**Comment by Skillotic0703** [comment]
I don't no why but github doesn't let me upload files even if I compress them to a zip file.

**Comment by Skillotic0703** [comment]
I reinstalled agricraft and that's working now. Sometimes even without agricraft it doesn't want to place crops until I break the greenhouse and replace it.

**Comment by SonarSonic** [comment]
Very Strange, can't recreate this at all

**Comment by Skillotic0703** [comment]
And the iron chest bug ? Can you recreate it ?

**Comment by SonarSonic** [comment]
Haven't tested that one yet

**Comment by Skillotic0703** [comment]
This one is happening without agricraft

**Comment by Skillotic0703** [comment]
Thank you and sorry for wasting your time

**Comment by Skillotic0703** [comment]
I tested with the crop sticks just now and this isn't working unless I break and replace the greenhouse

**Comment by Skillotic0703** [comment]
this wasn't*

**Comment by Skillotic0703** [comment]
It's also working with platiolus seeds

**Comment by Skillotic0703** [comment]
!!!!!!!!!!!!!!!!!WEIRD!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
About the iron chest bug: When replacing the chest with a copper chest it keeps the same inventory (same number of slots and same items)
