### ISSUE TITLE
[ENHANCEMENT] Advanced power cube does not put energy to Immersive machine

### ISSUE THREAD

**Issue by hron84** [SonarSonic/Calculator#53]
I trying to use Advanced Power Cube with an Immersive Engineering pump, and even if I activate the output side via sneak+right click, cube does not emits the power to the pump, I needed a cable too. Maybe, just maybe, it should be changed - but only if it is possible.

Calculator 1.8.9
Immersive Enigneering 0.6.2

**Comment by SonarSonic** [comment]
Haven't looked into this yet, but I will get onto it eventually.

**Comment by SonarSonic** [comment]
Fixed in dev

**Comment by hron84** [comment]
Thanks.
