### ISSUE TITLE
Flawless Greenhouse outputting crops to itself instead of chest

### ISSUE THREAD

**Issue by Mysteryem** [SonarSonic/Calculator#54]
I built a flawless greenhouse in version 1.8.9, but it seems to be extracting the harvested crops into itself. Furthermore, the greenhouse is actually extracting items from the chest placed in front of the greenhouse. Having no chest makes no difference to its behaviour. Here's some images of the setup: http://imgur.com/a/Ix2wt

Annoyingly, I can't even extract the Coal Dust from the greenhouse using pipes from other mods, I can extract the Prunae seeds, but not the Coal Dust.

**Comment by godluck** [comment]
There is another serious problem attached to above one: the flawless greenhouse in version 1.8.9 will stop working if there is any item that can not be planted to the ground, which it also don't output to outer container, making potato and crops impossible to grow inside the greenhouse. Only carrots can be produced without problem.

**Comment by SonarSonic** [comment]
The Greenhouse is meant to put crops into its own inventory which can be planted and put items which can't be replanted into the chest.

**Comment by SonarSonic** [comment]
That's a duplicate with #52. I haven't had much chance to fix these recently but I have more time now.

**Comment by Mysteryem** [comment]
Well, the flawless greenhouse is taking all items that I put in the adjacent chest regardless of whether they can be planted. The advanced greenhouse worked fine with prunae seeds and coal dust.

**Comment by SonarSonic** [comment]
Yeah i've noticed this, problems with the inventory helper, It might take me a while to fix.

**Comment by SonarSonic** [comment]
Okay all issues have been fixed as far as I can see! I'm just wondering what would be the best way for the chests to function? Should there be an input and output, or one chest used for both? Should the Greenhouse draw plantable items from the outputs?

**Comment by Mysteryem** [comment]
Might be a bit late, but I would match the behaviour of the other greenhouses. Keep them consistent with one another.

**Comment by SonarSonic** [comment]
They all match at the moment :) but what would the perfect config be?

**Comment by Mysteryem** [comment]
Considering there's usually only two sides that are accessible on the standard and advanced greenhouses and one of these is needed for power, I would continue to have the greenhouse output seeds to itself and output the harvested crops to the adjacent chest.

I'm not sure how they work with crops that are also the seed (such as carrots), I think in this case, the greenhouse should output the carrots into the chest only if the greenhouse is fully planted (so the greenhouse itself will never run out of carrots, but won't fill its own inventory).

When this is not the case, e.g. prunae seeds and coal dust, currently, the greenhouse slowly fills up with the seeds, once full, it'll output the seeds to the chest instead. Being able to apply the void upgrade to the greenhouse to make it delete the excess seeds instead of outputting them to the chest might be a nice addition.

**Comment by Skillotic0703** [comment]
There should be an input chest and an output chest. This is more reliable, mostly when using other mods pipes.

**Comment by SonarSonic** [comment]
Okay, I'll change this in the next update :)
