### ISSUE TITLE
[Enhancement] Add stairs, walls and slabs for reinforced stone+bricks

### ISSUE THREAD

**Issue by hron84** [SonarSonic/Calculator#55]
It would be very nice if we could make stairs/slabs and possible walls (fences) from this wonderful material. Standard stair/slab/cobble wall  recipes should work.

**Comment by SonarSonic** [comment]
Okay will add this in next update

**Comment by hron84** [comment]
Thanks

**Comment by SonarSonic** [comment]
![image](https://cloud.githubusercontent.com/assets/10425594/12076240/bafd3214-b19a-11e5-95b8-a52722ec0093.png)
Added in dev. No slabs I'm afraid, If I get time I'll add them, but no other Calculator blocks have slabs atm so I'll have to see.

**Comment by hron84** [comment]
Stairs and fences are a lot more than we had before, thanks for your hard work!

**Comment by SonarSonic** [comment]
Yeah it's a darker version of stone
