### ISSUE TITLE
AE2 Networks

### ISSUE THREAD

**Issue by DeathCorps69** [SonarSonic/Calculator#56]
Would it be possible to configure the storage chambers to work with the AE2 storage buses? As of right now the network is oblivious to the contents inside of the storage chambers.

**Comment by SonarSonic** [comment]
Sure, i'll add that when I next update Calculator

**Comment by SonarSonic** [comment]
Having Trouble implementing Extract and Insert, I may just leave it with being able to read the contents but not alter it.

**Comment by DeathCorps69** [comment]
If you leave it with being able to read it only would that break AE if you try to extract from the terminal or would it just do nothing?

**Comment by SonarSonic** [comment]
It just does nothing :) So it should be fine.

**Comment by DeathCorps69** [comment]
Hmmm... i might not be worth just being able to see them, might be better off just not having it as it would serve no real purpose i guess. At least until there is a way to insert and extract.

**Comment by SonarSonic** [comment]
Having another look, i've got Insert working now

**Comment by SonarSonic** [comment]
Okay yeah I've done it now. I misread some of the documentation, my bad...
