### ISSUE TITLE
[Enhancement] Redstone Sword does not glow if enchanted

### ISSUE THREAD

**Issue by hron84** [SonarSonic/Calculator#58]
I tried to enchant a Redstone Sword and enchatment applied but the glowing effect is not. Maybe it would be good if enchanted tools could glow as all other items in the game glows if enchanted.

Calculator 1.9.0

**Comment by SonarSonic** [comment]
I'm not the best at Rendering, I'm not sure how to do this tbh, although if you know a mod that does this for custom models It'd be great to know then I could try and see how it's done :)

**Comment by AEnterprise** [comment]
just return true in isEnchanted or one of the related functions and MC will apply the glow effect

**Comment by SonarSonic** [comment]
that doesn't work for custom models

**Comment by AEnterprise** [comment]
then you're gona have to dig through the MC code and apply something similar

**Comment by hron84** [comment]
I ping @rwtema here, IIRC he knows a lot about custom rendering stuffs. Also, IIRC he have a custom sword too.

**Comment by hron84** [comment]
@SonarSonic A simple question about this topic: can you add a glowing effect at least to the inventory item rendering (probably as an overlay)? It's fine if the dropped/hold item (that 3D stuff) does not actually start glowing, but if you play with a bunch of other players on a same base, it would be hard to distinguishe enchanted/unenchanted items. Currently as a workaround i rename all my tools to ensure I can find it across our storage solutions but I would still like a better solution (other players tend to not enchant Calculator tools, but have a lot of for case of break). I'm a huge fan of vanilla enchantments, I collect them with a passion and utilize them on my most favorite tools (Calculator ones, if it wouldn't be clear :smile:).

**Comment by SonarSonic** [comment]
I'm not working on 1.7.10 Calculator anymore, this will be in 1.8.9

**Comment by SonarSonic** [comment]
![image](https://cloud.githubusercontent.com/assets/10425594/13896624/692d5f00-ed8a-11e5-9ce5-4a035c0eb39f.png)
done ;)

**Comment by hron84** [comment]
Cool :heart:

**Comment by SonarSonic** [comment]
First release will be in the coming weeks

**Comment by hron84** [comment]
Can't wait! :smile:
