### ISSUE TITLE
[QUESTION] Scarecrow can work with Agricraft crops?

### ISSUE THREAD

**Issue by hron84** [SonarSonic/Calculator#59]
Just I wonder if Scarecrow can increase growth speed of Agricraft crops. I place this guy anyway because it looks really awesome, but if he can make my crops more effective... it would be good.

Note: I do not know how do you doing this thing now, but for the balance, we need nearly same effect on Agricraft crops like how ExtraUtils cans work (increases "growth ticks" IIRC), since bonemealing is works a bit differently on crops (they can skip a growth stage if you apply a bonemeal, and also there is a lot of plants that does not work with normal bonemeal, but a special one like MagCrops Magical Fertilizer).

**Comment by SonarSonic** [comment]
It'll increase the growth of ones that work with bone meal but not ones which require over types of fertilizer.

**Comment by hron84** [comment]
Cool, thanks
