### ISSUE TITLE
Basic Greenhouse isn't building properly

### ISSUE THREAD

**Issue by Divineaspect** [SonarSonic/Calculator#62]
It's starting to build and then claiming that the blocks it's placed are in it's way.

**Comment by Divineaspect** [comment]
I found it, railcraft tracking blocks seemed to be the source.

**Comment by Divineaspect** [comment]
was able to double check it this time, reproduced without railcraft.

If a greenhouse is interupted in building, it uses up resources to start the building, and then demands enough resources to build the entire thing, and claims already placed blocks as obstructions.

**Comment by AEnterprise** [comment]
i suspect your are comparing the block to the air block? you should call the isBlockAir() on the block or so so the fake blocks from RC and other mods are no longer in the way

**Comment by hron84** [comment]
And we also expect to greenhouses be able to continue the work, and not stop the process if go out of resources. Quite hard if you miscount 1 or 2 wood you have to dismantle all the building and restart the process. Could you please take a bit deeper look into greenhouses?

**Comment by Peach774** [comment]
So, railcraft invisible blocks cause the problem?
