### ISSUE TITLE
Clarification: Is the greenhouse supposed to only grow one plant?

### ISSUE THREAD

**Issue by Divineaspect** [SonarSonic/Calculator#63]
I put more then one seed type into the greenhouse but it's only growing the first one, is this intentional behaviour?

**Comment by SonarSonic** [comment]
Yeah it is. Doesn't choose seeds randomly or anything at the moment

**Comment by Divineaspect** [comment]
Can I request a reset button in the GUI, so we can change what we grow in them without tearing it down and loosing all that CO2?

**Comment by togreglove** [comment]
I never tear mine down. I remove all seeds from the greenhouse, manually harvest what is planted, then place new seeds in the greenhouse.  It then takes and plants those seeds instead. Hope this helps while we wait on the feature.

**Comment by SonarSonic** [comment]
Available in the latest version! Crops will maintain their positions once harvested, and you can now pause the greenhouse ;)  
![image](https://cloud.githubusercontent.com/assets/10425594/21597284/24b5a63a-d140-11e6-8d7e-7cb6e6456dc5.png)
