### ISSUE TITLE
Advance Greenhouse Crash 1.9.3

### ISSUE THREAD

**Issue by parcel31u** [SonarSonic/Calculator#69]
http://pastebin.com/ywzTAS2i

**Comment by SonarSonic** [comment]
I'll probably be replacing the current Inventory Sorting System soon, making Practical Logistics Fluid Handling, Item Handling and Energy Handling part of Sonar Core so they can be used in Calculator, the new one will fix this... hopefully haha

**Comment by SonarSonic** [comment]
The Inventory System was replaced :)
