### ISSUE TITLE
Missing NEI recipes

### ISSUE THREAD

**Issue by Stephenator0316** [SonarSonic/Calculator#7]
Hey, playing with version Calculator-1.7.10-1.7.5 and for some reason, some recipes aren't showing up, such as the reinforced stone and dirt. This is the only thing I see when I click on them in  NEI... http://imgur.com/WdfNw7V

**Comment by DrWhoCares** [comment]
If you open the calculator, and click on the result arrow (equals sign). It should show you recipes. This is a known issue.

**Comment by Stephenator0316** [comment]
Ok, is there a way I can fix it temporarily? If not when can we get a fix? I'm basing my SP modpack around this o3o

**Comment by DrWhoCares** [comment]
My best advice is to use the in Calculator GUI, research everything you can, and check the wiki, not a ton of recipes are on there but eventually I plan on adding most if not all.

**Comment by Stephenator0316** [comment]
Ok, still est. date on a fix?

**Comment by DrWhoCares** [comment]
Probably within a week IF it can get pinned down, I'd say.

**Comment by Stephenator0316** [comment]
:/ Ok, thanks

**Comment by DrWhoCares** [comment]
Sorry dude, I'm in same boat, calculator is pretty much the only mod i use.

**Comment by DrWhoCares** [comment]
In the mean time, recipe for reinforced stone is cobble plus wood planks, dirt plus woodplanks is reinforced dirt.

**Comment by Stephenator0316** [comment]
Thanks

**Comment by SonarSonic** [comment]
I have never witnessed the default recipe disappearing, however I am aiming to improve the research system in 1.7.6

**Comment by SonarSonic** [comment]
Fixed in 1.7.6
