### ISSUE TITLE
Calculator 1.9.4 crash

### ISSUE THREAD

**Issue by Skillotic0703** [SonarSonic/Calculator#72]
The server crashes when putting down an advanced furnace. Then, it crashes every time I join it. 
http://pastebin.com/piLp9WUH
Sonar core and practical logistics are up to date!

**Comment by SonarSonic** [comment]
Fixed in dev...speed and energy upgrades will be deleted...

**Comment by Skillotic0703** [comment]
thanks
I'm looking forward the update
