### ISSUE TITLE
[QUESTION] Do you plan to upgrade Calculator to 1.8.9?

### ISSUE THREAD

**Issue by hron84** [SonarSonic/Calculator#73]
See the title. This is one of my favorite mods, even if mod pack creators aren't discovered this hidden gem - yet. Is there any plan to support 1.8.9 world?

**Comment by SonarSonic** [comment]
Yes, I have no idea when though, 1.8.9 is a big task and I just don't have the time right now, but I think Calculator will make it some day.

**Comment by hron84** [comment]
Cool. Let me know if you need some testing.

**Comment by SonarSonic** [comment]
I'm going to be needing some testing very soon :)

**Comment by hron84** [comment]
@SonarSonic I'm here, just call my name :stuck_out_tongue:

**Comment by SonarSonic** [comment]
what's the best way of sending you details/files etc?

**Comment by hron84** [comment]
Just find me on hrgyster's GMail address, or look up on popular social networks for my GitHub nick. This name is occupied for me. :smile:

**Comment by SonarSonic** [comment]
I followed you on twitter, can't message till you follow back :P

**Comment by hron84** [comment]
Fixed
