### ISSUE TITLE
Crash putting calculator in calculator.

### ISSUE THREAD

**Issue by superreg** [SonarSonic/Calculator#76]
My ignorant friend tries to put the number "5" in his calculator. Slot 5 is where his calculator was. It crashed the server.

**Comment by SonarSonic** [comment]
Haha okay, Crash Report?

**Comment by superreg** [comment]
http://pastebin.com/bnFbkk6P

**Comment by SonarSonic** [comment]
Erm okay, I'll have to look into this not 100%% sure why this is happening yet

**Comment by superreg** [comment]
I'm not too sure, but the calculator didn't like being put inside itself.

**Comment by AEnterprise** [comment]
you put the calc in itself? i don't know the code but that indeed sounds like the best way to cause an infinite loop like this

**Comment by superreg** [comment]
I believe so. My friend said he tried to put "5" in the calculator. It seems to me like the calculator was probably in slot 5.

**Comment by MineWitherMC** [comment]
Confirmed. Took storage module and put it in slot 2. Then opened it and put slot 2 there. Luckily the result was only lost storage module not corrupted world (luckily? I believe I didn't put atomic multiplier in there...)

**Comment by SonarSonic** [comment]
can't recreate this at all, I could get a calculator within a calculator within a calculator within a calculator

**Comment by superreg** [comment]
Hmm... I'll try to recreate it again today to see if there's anything else needed to recreate.

**Comment by superreg** [comment]
I have been able to reproduce it again today. I think you misunderstood my original comment. To reproduce, right-click to open the calculator interface (tested with the plain calculator) and click the number that corresponds with where the SAME calculator is on your hotbar. For example, I right click with slot 9 on my hotbar (the calculator), then I press "9" on my keyboard to put the item from slot 9 on my hotbar in to the calculator (also slot 9).

The problem is putting the SAME calculator inside itself.

**Comment by MineWitherMC** [comment]
And then server crashes and calculator vanishes.

**Comment by SonarSonic** [comment]
Fixed in dev
