### ISSUE TITLE
Greenhouse is eating my crops

### ISSUE THREAD

**Issue by Peach774** [SonarSonic/Calculator#78]
The crops in my greenhouse are agricraft crops with 10, 10 ,10 pumpkins. They grow to full are immediately harvested, then disappear. It is powered. I tried removing the chest, I tried everything, but it won't give me my pumpkins.

**Comment by SonarSonic** [comment]
Thanks for reporting i'll get a fix out soon

**Comment by SonarSonic** [comment]
the fix is uploading now
