### ISSUE TITLE
Calc Plug

### ISSUE THREAD

**Issue by Stephenator0316** [SonarSonic/Calculator#8]
Ok, so it turns out if you put items into the calculator plug, it doesn't realize theres a circuit in there, and you have to go around and right click each one for it to update, BUs dont work

**Comment by Stephenator0316** [comment]
Oh, nvm, just relog xD

**Comment by SonarSonic** [comment]
I'll make sure it updates in next update :)

**Comment by Stephenator0316** [comment]
Thanks xD
