### ISSUE TITLE
This isn't a issue, just a question

### ISSUE THREAD

**Issue by Silly511** [SonarSonic/Calculator#81]
I was look at your purified obsidian textures and I noticed that their wasn't a no-borders texture, for when the block is surrounded on all sides. So just out of curiosity, where do you get the no-borders texture?

**Comment by SonarSonic** [comment]
The no borders texture is number 15 https://github.com/SonarSonic/Calculator/blob/master/src/main/resources/assets/calculator/textures/blocks/connected/purifiedobsidian_15.png

**Comment by Silly511** [comment]
But thats for if the blocks are in a plus sign, what about when its surrounded on all sides(like if it was in a 3x3)?

**Comment by Silly511** [comment]
Never mind, I figured it out.
