### ISSUE TITLE
Server console spam for Calculator Locator multiblock

### ISSUE THREAD

**Issue by mille449** [SonarSonic/Calculator#85]
Using version 1.7.10-1.9.8. Getting this message repeatedly in the server console:

[elec332.core.multiblock.dynamic.AbstractDynamicMultiBlockWorldHolder:addTile:114]: ERROR!!!  Tile at (-426,68,555) is trying to register whilst already being registered!

![screenshot 2016-04-23 13 16 08](https://cloud.githubusercontent.com/assets/204860/14763245/8f25cc92-0955-11e6-8d4a-3f0bc4ad6603.png)

Also, each plug has a stable circuit in it, but the stability only shows up as 37%.

**Comment by mille449** [comment]
Also, coordinates are different each time, so they seem to be coming from different blocks.

**Comment by SonarSonic** [comment]
This is not an issue with Calculator Locators. The issue is caused by mods which depend on Elec Core. So it'll be one of them instead.

**Comment by mille449** [comment]
Opps, should have read that more closely.  Thought this was the only multiblock in the world at that point - it is caused by Deep Resonance tank multiblocks btw.
