### ISSUE TITLE
Amethyst leaves dupe

### ISSUE THREAD

**Issue by MineWitherMC** [SonarSonic/Calculator#89]
I don't know if it works on Tanzanite/Pear/Diamond as didn't got to that stage yet but if you shift-LMB-click amethyst leaves 2 will be dropped per 1 broken. Yep this is in 1.9.8.

**Comment by MineWitherMC** [comment]
Just realised that this is working on Tanzanite. And it's interesting what would be there if it was working on Diamond...

**Comment by MineWitherMC** [comment]
Found some interesting details.
This dupe works on all 4 trees. And with any shears (tested vanilla, thermal foundation, extra utilities precision shears (both LMB and Shift-RMB methods), RC steel shears and RA omniwrench), I can say more: the leaves duplicate even without Shift. And I think I caught the reason: they can be harvested by hand, but the CalculatorLeaves class is implementing IShearable so when I harvest they with shears they drop 1 block as expected + 1 block as harvested with shears = 2 blocks from 1. Please fix.

**Comment by SonarSonic** [comment]
Fixed in dev
