### ISSUE TITLE
[Blacklist] Atomic Multiplier

### ISSUE THREAD

**Issue by MrFootman** [SonarSonic/Calculator#90]
Hello!

I'm wondering how is working your config files (AtomicMultiplier-BlackList.cfg)
Am i able to use item ID instead of  Mod:Item ? 
Because i'm looking to blacklist the "Green heart canister" from Tinkers' Construct, and i can't find the right syntax.

Thank you in advance for any answer, and thank you again for your amazing mod!

MrFootman

**Comment by SonarSonic** [comment]
no you can't use item ID at the moment

**Comment by AEnterprise** [comment]
using an item id is a very bad idea as those can chang when mods are added and removed as they are dependant on loading order. They will persist in the same world but if a new world is made after an id shift the config will work for the original world but not the new one

**Comment by SonarSonic** [comment]
Completely forgot about that. Okay then maybe not then ;)
