### ISSUE TITLE
Stone Assimilator doesn't let hunger module hunger go above 1k

### ISSUE THREAD

**Issue by MineWitherMC** [SonarSonic/Calculator#91]
There is a bug with Stone Assimilator harvesting Amethyst Tree so if the hunger module inside has 1k hunger it doesn't raise. But if I RMB amethyst leaves manually the hunger can get to 1010 and maybe more

**Comment by MineWitherMC** [comment]
![2016-04-29_22 07 00](https://cloud.githubusercontent.com/assets/18210824/14926780/8a287180-0e56-11e6-9bd1-3e9a9c3ee072.png)

**Comment by SonarSonic** [comment]
Fixed in dev (The hunger module is meant to only go to 1000, so I fixed the leaf right clicking not the assimilator)

**Comment by MineWitherMC** [comment]
Found that issue in the code :) didn't check max when RMB-ed the amethyst leaves, lol. Same was for tanzanite.

**Comment by SonarSonic** [comment]
Yeah some of that code was written like 2 years ago lol. I've posted the new version now.
