### ISSUE TITLE
EnderIO Capacitor Issues

### ISSUE THREAD

**Issue by DeathCorps69** [SonarSonic/Calculator#93]
I am using the Flux Point/Plug and while they do work with conduits it seems they will not connect to a vibrant capacitor block directly. Can you take a look at this?

Running:
EnderIO 2.3.0.424_beta
EnderCore 0.2.0.34_beta
Calculator 1.9.8
SonarCore 1.1.0
Forge 10.13.4.1558

**Comment by DeathCorps69** [comment]
Quick update - Doesn't seem to connect to any EnderIO machine directly. Is this intentional?

**Comment by SonarSonic** [comment]
Fixed in dev
