### ISSUE TITLE
Purified obsidian ez break

### ISSUE THREAD

**Issue by MineWitherMC** [SonarSonic/Calculator#94]
I noticed that the purified obsidian isn't unbreakable. According to Waila Harvestability, it has harvest level of 0 and thus can be broken with any pickaxe. I just tested it with wooden pick and it worked. And EIO empowered dark pick or RA empowered flux infused pick can break it less than in 2 seconds.

**Comment by MineWitherMC** [comment]
I think you should considering setting it hardness to -1 instead of using setBlockUnbreakable function (or how is it called). Or simply set hardness and harvest level over 9k.

**Comment by SonarSonic** [comment]
#83

**Comment by MineWitherMC** [comment]
But why isn't it fixed anyway? That issue was 'fixed'...

**Comment by SonarSonic** [comment]
there have been no new builds since then
