### ISSUE TITLE
Redstone dupe with Calc + TE and/or Mekanism

### ISSUE THREAD

**Issue by MineWitherMC** [SonarSonic/Calculator#95]
1) Take a redstone dust and place it into algorithmic separator. You'll get 2 ingots.
2) Place ingots into pulveriser (TE) or crusher (Mek). Get 1 dust per 1 ingot, so 1 dust = 2 dust + 2 small stone.
3) Profit!

**Comment by SonarSonic** [comment]
Removed from Ore Dictionary (Fixed in dev)
