### ISSUE TITLE
Bad Recipe

### ISSUE THREAD

**Issue by Shadehunter81** [SonarSonic/Calculator#99]
i added Calculator to a pack i put together so i could do a spotlight/tutorial for it and the recipe for the Redstone Separator generator thing is fire+starch Separator+fire in the atomic calculator. is that suppose to be Blaze powered because i tried and it didnt work...please help....thanks

**Comment by MineWitherMC** [comment]
Look #97, #98. You should use minetweaker or 1.9.8 version as 1.9.9 fixed dupe but there are uncraftable Red Extractors, RF Points, and Adv Terra Modules at the moment.

**Comment by SonarSonic** [comment]
Fixed in dev

**Comment by Shadehunter81** [comment]
thank you SonarSonic for the fix
